import { randomUUID } from "node:crypto";
import { actualCommandSchema, type ActualCommand, type ActualVersion, type ReportSnapshot } from "@/lib/programs/work-program/reporting";
import { reimbursementTotals, type ReimbursementDraft } from "@/lib/programs/work-program/reimbursement";
export function fixture() {
 const element = randomUUID(), task = randomUUID();
 const command: ActualCommand = actualCommandSchema.parse({ requestId: randomUUID(), entryId: randomUUID(), expectedVersion: 0, revisionId: randomUUID(), kind: "labor", status: "approved", entryDate: "2026-08-01", sourceKey: "synthetic-1", sourceReference: "Synthetic payroll source", description: "Engineering fixture, no agency spending", hours: "1.00", amount: "12.35", basis: "recorded", allocations: [{ elementId: element, taskId: task, share: 10000 }] });
 const actual: ActualVersion = { id: randomUUID(), entry_id: command.entryId, version: 1, revision_id: command.revisionId, source_key: command.sourceKey, entry_date: command.entryDate, kind: command.kind, staff_id: randomUUID(), staffName: "Synthetic staff", amount: command.amount, hours: command.hours, status: "approved", valuation_basis: "recorded", detail: command, created_at: "2026-09-01T00:00:00Z", allocations: [{ element_id: element, task_id: task, deliverable_id: null, share: 10000, amount: command.amount, hours: command.hours }] };
 const snapshot: ReportSnapshot = { schemaVersion: 1, period: { id: randomUUID(), name: "Synthetic August", starts_on: "2026-08-01", ends_on: "2026-08-31", baseline_id: command.revisionId, source_cutoff: "2026-09-01T01:00:00Z", version: 1, state: "review", progress: [{ elementId: element, taskId: null, asOf: "2026-08-31", completed: "First draft", outstanding: "Review", issues: "None reported", remainingCost: "20.01", remainingHours: "2.00", estimateBasis: "Synthetic remaining work estimate" }], note: "Synthetic", review_snapshot: null }, baseline: { id: command.revisionId, revision: 1, content_sha256: "a".repeat(64), source_ids: [], content_json: { schemaVersion: 1, documentKind: "owp", agency: "Synthetic agency", responsibleAuthority: "Synthetic board", authorityBasis: "No agency authority", periodStart: "2026-07-01", periodEnd: "2027-06-30", introduction: "", staffing: "", financialNotes: "", currency: "USD", priorBalance: null, priorBalanceBasis: "", elements: [{ id: element, source: null, code: "100", title: "Synthetic work", disposition: "continuing", decisionNote: "Continue synthetic work", objective: "", discussion: "", responsible: "", schedule: "", personMonths: null, budgetTreatment: "included", budgetTreatmentNote: "", tasks: [{ id: task, description: "Draft", responsible: "", schedule: "" }], products: [], budget: [{ id: randomUUID(), kind: "cost", label: "Cost", amount: 100.01, fundingYear: "2026", basis: "proposed", note: "" }], projectId: null }] } }, actuals: [actual], valuationHistory: [actual], reviewNote: "Synthetic review" };
 return { command, actual, snapshot, element, task };
}

export function packetFixture() {
 const { snapshot, actual } = fixture();
 const fundId = randomUUID(), matchId = randomUUID();
 snapshot.baseline.content_json.preparation = { formatVersion: 2, extractionSelections: [], funds: [fundId, matchId].map((id, i) => ({ id, sourceRefs: [], name: i ? "Synthetic match" : "Synthetic fund", vintage: "000123.45", periodStart: "2026-07-01", periodEnd: "2027-06-30", kind: "proposed", amount: 100, basis: "reference", note: "" })), allocations: [], costs: [], staffing: [], indirectPools: [], mappings: [], sourceSections: [], amendments: [], conflicts: [] };
 const draft: ReimbursementDraft = { reportId: randomUUID(), title: "Synthetic packet", authorityEvidence: "Synthetic agreement", formEvidence: "Synthetic required packet review", costs: [{ actualVersionId: actual.id, eligibleAmount: "12.35", eligibilityEvidence: "000123.45", shares: [{ fundId, amount: "10.00", treatment: "reimbursement", evidence: "Synthetic reimbursement share" }, { fundId: matchId, amount: "2.35", treatment: "match", evidence: "Synthetic match contribution" }] }] };
 const report = { id: randomUUID(), period_id: snapshot.period.id, version: 2, snapshot, snapshot_hash: "b".repeat(64), issued_at: "2026-09-01T01:00:00Z", corrects_report_id: null };
 snapshot.reimbursement = { ...draft, ...reimbursementTotals(draft, report), claimId: randomUUID(), packetVersion: 1, sourceReportHash: "c".repeat(64), reviewedBy: randomUUID(), reviewedAt: report.issued_at, reviewNote: "Synthetic review", history: [], deliverables: [], deliverableEvents: [] };
 return { draft, report, actual };
}
