"use client";

import { useMemo, useState } from "react";
import { useRouter } from "next/navigation";
import { Languages, Loader2 } from "lucide-react";

import { Button } from "@/components/ui/button";
import { useConfirmDialog } from "@/components/ui/confirm-dialog";
import { StatusBadge } from "@/components/ui/status-badge";
import { Textarea } from "@/components/ui/textarea";
import type { StatusTone } from "@/lib/ui/status";
import {
  PORTAL_DEFAULT_LOCALE,
  PORTAL_LOCALE_DIRECTION,
  PORTAL_LOCALES,
  resolvePortalLocale,
  type PortalLocale,
} from "@/lib/engagement/portal-i18n/locales";
import { buildPortalMessageBundle, portalMessageCoverage } from "@/lib/engagement/portal-i18n/messages";
import { createPortalTranslator } from "@/lib/engagement/portal-i18n/translator";
import { portalTextDisclosureView } from "@/lib/engagement/portal-i18n/provenance";
import {
  machineTranslationUnavailableReason,
  TRANSLATION_LANGUAGE_LABELS,
  TRANSLATION_LANGUAGE_NATIVE_LABELS,
} from "@/lib/engagement/translation-languages";
// TYPE-ONLY, and it has to stay that way: `campaign-translations.ts` imports
// node:crypto for the source-text hash, and a value import from here would drag
// it into a browser bundle. Everything this panel needs at runtime is
// precomputed server-side and arrives as a prop.
import type {
  CampaignLocaleCoverage,
  CampaignTranslatableField,
  CampaignTranslationEntry,
} from "@/lib/engagement/campaign-translations";

/**
 * WHERE AN AGENCY WRITES ITS OWN WORDS IN SOMEBODY ELSE'S LANGUAGE.
 *
 * The engagement module could translate a resident's comment into every language
 * it carries and could not ask its own question in any of them. The storage, the
 * resolver and the participant surfaces existed; nothing wrote them. This panel
 * is the missing half, and it has four jobs it is not allowed to get wrong.
 *
 * 1. THE TWO KINDS OF TRANSLATION MUST STAY VISIBLY DIFFERENT. Operator-authored
 *    text is the agency's statement and carries no caveat. Machine output is a
 *    convenience that may be wrong and that nobody at the agency ever said, and
 *    the portal labels it every single time it renders it. Those are different
 *    promises to a member of the public, and under Title VI the difference is the
 *    one that matters — so this screen never shows them with the same badge, and
 *    it shows the machine caveat IN THE PARTICIPANT'S LANGUAGE, generated by the
 *    same `portalTextDisclosure` the portal itself calls. Not a copy of the
 *    sentence: the sentence.
 *
 * 2. ACCEPTING MUST ANNOUNCE ITS OWN CONSEQUENCE. Accepting a machine
 *    translation promotes it to operator-authored, which means the caveat a
 *    resident was reading DISAPPEARS and the words become the agency's own. That
 *    is the operator taking responsibility, and it is not something to discover
 *    afterwards, so it is stated on the control and again in the confirmation.
 *
 * 3. "COMPLETE" IS A CLAIM, SO IT IS MEASURED. "We published in Spanish" is a
 *    sentence an agency will say out loud from this screen. It is only true when
 *    EVERY string a participant reads has a translation — and a page whose
 *    operator text is fully translated is still part English if OpenPlan's own
 *    chrome is not, so both halves are counted and both are shown.
 *
 * 4. AN UNKNOWN STATE IS NOT AN EMPTY ONE. When the translations could not be
 *    read, coverage arrives as `null` and this panel says so instead of drawing
 *    a "Not translated" card for every language it carries — that would be a
 *    statement about the agency made out of a database failure.
 *
 * RIGHT-TO-LEFT IS NOT OPTIONAL HERE EITHER. Some of the languages an agency
 * writes in here run right to left — Arabic, Farsi and Urdu today, and the set
 * has already grown once — so every editor carries the target language's own
 * `dir` and `lang`, the source text carries the campaign language's, and the
 * layout uses logical properties only — a declared `dir` over `ml-`/`text-left`
 * is broken with extra steps.
 */

type FetchState = { busy: string | null; error: string | null; notice: string | null };

const STATE_LABELS: Record<CampaignLocaleCoverage["state"], { label: string; tone: StatusTone }> = {
  source_language: { label: "Campaign's own language", tone: "info" },
  operator_complete: { label: "Complete — your wording", tone: "success" },
  machine_assisted: { label: "Complete — partly machine", tone: "warning" },
  partial: { label: "Partly translated", tone: "warning" },
  untranslated: { label: "Not translated", tone: "neutral" },
};

/**
 * The consequence sentence, in one place, used by the button's own explanation
 * and by the confirmation. Two wordings would mean the operator could be warned
 * about one thing and agree to another.
 */
const ACCEPT_CONSEQUENCE =
  "Accepting makes these words your agency's own. The machine-translation caveat that " +
  "participants are reading right now disappears, and the text is published as if someone here " +
  "wrote it. Only accept wording you have read.";

const PUBLISH_MACHINE_CONSEQUENCE =
  "This publishes the model's wording to the public portal straight away, labelled as a machine " +
  "translation. Residents will see it in their language with a caveat saying a machine produced it, " +
  "until someone here accepts or replaces it.";

export function CampaignTranslationsPanel({
  campaignId,
  fields,
  entries,
  coverage,
  sourceLocale,
  sourceLocaleStated,
  readFailures,
  translationsReadable,
  inventoryComplete,
  sourceLocaleReadable,
  machineTranslationAvailable,
  machineBatchMax,
  acceptBatchMax,
  canWrite,
}: {
  campaignId: string;
  /** Every string a participant reads, in the campaign's own language. */
  fields: CampaignTranslatableField[];
  /** What has already been translated. Empty when `translationsReadable` is false. */
  entries: CampaignTranslationEntry[];
  /** NULL when the translations could not be read — never rendered as zeroes. */
  coverage: CampaignLocaleCoverage[] | null;
  sourceLocale: PortalLocale;
  /** False when nobody recorded the campaign's language and it is presumed. */
  sourceLocaleStated: boolean;
  readFailures: Array<{ label: string; message: string; schemaPending: boolean }>;
  /** False when the translations read failed — the difference between unknown and none. */
  translationsReadable: boolean;
  /**
   * False when part of the inventory could not be read, so `fields` is known to
   * be short of what a participant actually reads. Editing comes off: the write
   * route refuses in this state for the same reason, and a button whose API
   * always answers 500 is worse than no button.
   */
  inventoryComplete: boolean;
  /**
   * False when the campaign's recorded language could not be READ — as opposed
   * to having been left unrecorded. Two different sentences, and only one of
   * them is a finding about the agency.
   */
  sourceLocaleReadable: boolean;
  /** False with no Anthropic key: hand authoring still works, and says why. */
  machineTranslationAvailable: boolean;
  /**
   * How many strings one machine-translation request may carry.
   *
   * Passed in rather than imported, because the constant lives beside the route's
   * own validation in a module that reaches node:crypto. A second copy of the
   * number here is how a button comes to promise a batch the API refuses.
   */
  machineBatchMax: number;
  /**
   * How many translations one accept request may promote. Passed for the same
   * reason as `machineBatchMax`: a second copy of the number here is how a
   * button comes to promise a batch the API refuses.
   */
  acceptBatchMax: number;
  /** engagement.write in the workspace role matrix. Viewers read only. */
  canWrite: boolean;
}) {
  const router = useRouter();
  const { confirm, confirmDialog } = useConfirmDialog();

  const targetLocales = useMemo(
    () => PORTAL_LOCALES.filter((locale) => locale !== sourceLocale),
    [sourceLocale]
  );

  const [locale, setLocale] = useState<PortalLocale>(() => {
    const withWork = targetLocales.find((candidate) => entries.some((entry) => entry.locale === candidate));
    return withWork ?? targetLocales[0] ?? sourceLocale;
  });
  const [drafts, setDrafts] = useState<Record<string, string>>({});
  const [state, setState] = useState<FetchState>({ busy: null, error: null, notice: null });

  const direction = PORTAL_LOCALE_DIRECTION[locale];
  const sourceDirection = PORTAL_LOCALE_DIRECTION[sourceLocale];
  const nativeName = TRANSLATION_LANGUAGE_NATIVE_LABELS[locale];
  const englishName = TRANSLATION_LANGUAGE_LABELS[locale];
  /**
   * Some languages the portal RENDERS are deliberately not languages a model may
   * write — see `MACHINE_TRANSLATION_UNAVAILABLE`. This is a fact about the
   * chosen language, so it is re-derived whenever the language changes, and it
   * is kept SEPARATE from `machineTranslationAvailable` (which is about whether
   * a key exists): the two need different sentences, and offering a suggest
   * button that always refuses would be a control no operator can succeed with.
   */
  const languageMachineRefusal = machineTranslationUnavailableReason(locale);
  const machineTranslationOffered = machineTranslationAvailable && !languageMachineRefusal;

  /**
   * The disclosure a participant reading this language will actually see over a
   * machine translation — built by the portal's own resolver rather than
   * restated here, so the preview cannot drift from the published sentence.
   *
   * The VIEW, not the bare sentence. Every locale except Spanish has no message
   * catalog yet, so for those this sentence comes back as the English source
   * even though the language being edited is not English — and rendering it
   * under the TARGET language's `lang` and `dir` is the same mistake the source
   * text beside it already avoids. For a right-to-left language it is the worse
   * half of that mistake twice over: an English sentence told a screen reader it
   * is Arabic, laid out from the wrong edge. `portalTextDisclosureView` already
   * knows which language it actually produced, and `portalTextDisclosure` exists
   * only "for a surface that has nowhere to put `lang`". This surface has one.
   */
  const machineCaveat = useMemo(() => {
    const bundle = buildPortalMessageBundle(resolvePortalLocale({ requested: locale }));
    return portalTextDisclosureView(
      {
        text: "",
        provenance: "machine",
        textLocale: locale,
        textLocaleStated: true,
        requestedLocale: locale,
        model: null,
      },
      createPortalTranslator(bundle)
    );
  }, [locale]);

  const chrome = useMemo(() => portalMessageCoverage(locale), [locale]);

  const entryByKey = useMemo(() => {
    const map = new Map<string, CampaignTranslationEntry>();
    for (const entry of entries) {
      if (entry.locale === locale) map.set(entry.fieldKey, entry);
    }
    return map;
  }, [entries, locale]);

  const machineKeys = fields.filter((field) => entryByKey.get(field.key)?.source === "machine").map((f) => f.key);
  const untranslatedKeys = fields.filter((field) => !entryByKey.has(field.key)).map((f) => f.key);

  const groups = useMemo(() => {
    const ordered: Array<{ key: string; label: string; fields: CampaignTranslatableField[] }> = [];
    for (const field of fields) {
      const last = ordered[ordered.length - 1];
      if (last && last.key === field.groupKey) last.fields.push(field);
      else ordered.push({ key: field.groupKey, label: field.groupLabel, fields: [field] });
    }
    return ordered;
  }, [fields]);

  function draftValue(field: CampaignTranslatableField): string {
    const key = `${locale}::${field.key}`;
    if (key in drafts) return drafts[key];
    return entryByKey.get(field.key)?.text ?? "";
  }

  function setDraft(field: CampaignTranslatableField, value: string) {
    setDrafts((current) => ({ ...current, [`${locale}::${field.key}`]: value }));
  }

  function clearDrafts(keys: string[]) {
    setDrafts((current) => {
      const next = { ...current };
      for (const key of keys) delete next[`${locale}::${key}`];
      return next;
    });
  }

  async function post(busyKey: string, payload: Record<string, unknown>): Promise<Record<string, unknown> | null> {
    setState({ busy: busyKey, error: null, notice: null });
    try {
      const response = await fetch(`/api/engagement/campaigns/${campaignId}/translations`, {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify(payload),
      });
      const body = (await response.json()) as Record<string, unknown>;
      if (!response.ok) {
        // The route's refusal is shown verbatim: it already names the real cause
        // — an archived field, a missing table, a rate limit — and replacing it
        // with a generic sentence would throw that away.
        throw new Error(
          (typeof body.error === "string" ? body.error : null) ??
            (typeof body.details === "string" ? body.details : null) ??
            "The translation could not be saved."
        );
      }
      return body;
    } catch (error) {
      setState({
        busy: null,
        error: error instanceof Error ? error.message : "The translation could not be saved.",
        notice: null,
      });
      return null;
    }
  }

  function finish(notice: string | null, refresh: boolean) {
    setState({ busy: null, error: null, notice });
    if (refresh) router.refresh();
  }

  async function save(keys: string[]) {
    const payload = keys
      .map((key) => fields.find((field) => field.key === key))
      .filter((field): field is CampaignTranslatableField => field !== undefined)
      .map((field) => ({ fieldKey: field.key, text: draftValue(field).trim() }))
      .filter((entry) => entry.text.length > 0);
    if (payload.length === 0) {
      setState({
        busy: null,
        error: "There is nothing to save — write the translation first, or withdraw the existing one.",
        notice: null,
      });
      return;
    }

    const body = await post(`save:${keys.join(",")}`, { action: "save", locale, entries: payload });
    if (!body) return;
    clearDrafts(keys);
    finish(typeof body.published === "string" ? body.published : null, true);
  }

  async function suggest(keys: string[]) {
    const body = await post(`suggest:${keys.join(",")}`, {
      action: "suggest",
      locale,
      fieldKeys: keys.slice(0, machineBatchMax),
    });
    if (!body) return;

    if (body.available === false) {
      // Not an empty box: the reason, named.
      finish(typeof body.reason === "string" ? body.reason : null, false);
      return;
    }

    const suggestions = Array.isArray(body.suggestions)
      ? (body.suggestions as Array<{ fieldKey?: unknown; text?: unknown }>)
      : [];
    setDrafts((current) => {
      const next = { ...current };
      for (const suggestion of suggestions) {
        if (typeof suggestion.fieldKey === "string" && typeof suggestion.text === "string") {
          next[`${locale}::${suggestion.fieldKey}`] = suggestion.text;
        }
      }
      return next;
    });

    const drafted = `${suggestions.length} draft ${suggestions.length === 1 ? "translation" : "translations"} placed in the boxes below. Nothing is saved yet — read them, correct them, then save them as your wording.`;
    finish(typeof body.partial === "string" && body.partial ? `${drafted} ${body.partial}` : drafted, false);
  }

  async function publishMachine(keys: string[]) {
    // The consequence constant is passed through untouched: the panel and the
    // dialog must warn about the same thing in the same words.
    const confirmed = await confirm({
      headline: "Publish the model's wording to the public portal?",
      consequence: PUBLISH_MACHINE_CONSEQUENCE,
      confirmLabel: "Publish as a machine translation",
      cancelLabel: "Not yet",
      tone: "caution",
    });
    if (!confirmed) return;
    const body = await post(`machine:${keys.join(",")}`, {
      action: "publish_machine",
      locale,
      fieldKeys: keys.slice(0, machineBatchMax),
    });
    if (!body) return;

    if (body.available === false) {
      finish(typeof body.reason === "string" ? body.reason : null, false);
      return;
    }

    const notice = [body.publishedNotice, body.partial].filter((part): part is string => typeof part === "string" && part.length > 0);
    clearDrafts(keys);
    finish(notice.join(" ") || null, true);
  }

  async function accept(keys: string[]) {
    const confirmed = await confirm({
      headline: "Accept this wording as your agency's own?",
      consequence: ACCEPT_CONSEQUENCE,
      confirmLabel: "Accept this wording",
      cancelLabel: "Not yet",
      tone: "caution",
    });
    if (!confirmed) return;
    // Sliced to what the route accepts. The response reports how many were
    // actually promoted, so a batch that ran into the cap tells the operator a
    // true number rather than a hopeful one.
    const batch = keys.slice(0, acceptBatchMax);
    const body = await post(`accept:${keys.join(",")}`, { action: "accept", locale, fieldKeys: batch });
    if (!body) return;
    clearDrafts(keys);
    finish(typeof body.published === "string" ? body.published : null, true);
  }

  async function withdraw(field: CampaignTranslatableField) {
    const confirmed = await confirm({
      headline: `Withdraw the ${englishName} translation of “${field.label}”?`,
      consequence: `Participants reading ${englishName} will see it as the project team wrote it, with the disclosure that it is not translated.`,
      confirmLabel: "Withdraw this translation",
    });
    if (!confirmed) {
      return;
    }

    setState({ busy: `delete:${field.key}`, error: null, notice: null });
    try {
      const query = new URLSearchParams({ locale, fieldKey: field.key });
      const response = await fetch(
        `/api/engagement/campaigns/${campaignId}/translations?${query.toString()}`,
        { method: "DELETE" }
      );
      const body = (await response.json()) as { error?: string; details?: string; published?: string };
      if (!response.ok) throw new Error(body.error || body.details || "The translation could not be withdrawn.");
      clearDrafts([field.key]);
      finish(body.published ?? null, true);
    } catch (error) {
      setState({
        busy: null,
        error: error instanceof Error ? error.message : "The translation could not be withdrawn.",
        notice: null,
      });
    }
  }

  const busy = state.busy !== null;
  /**
   * WRITING REQUIRES HAVING READ, in two different senses.
   *
   * When the TRANSLATIONS could not be read, every editor below is empty — and
   * saving an empty editor would upsert over a translation a colleague wrote
   * that this page simply could not see.
   *
   * When the INVENTORY is short, the write route refuses outright: it rebuilds
   * the inventory itself and 500s if any part of it failed, because a shrunken
   * inventory is what would let a write land against a field the request could
   * not verify belongs to this campaign. Leaving the buttons on would offer an
   * action whose API answer is already decided.
   *
   * Either way the controls come off and the reason is stated, rather than
   * offering an action whose effect nobody can predict.
   */
  const editable = canWrite && translationsReadable && inventoryComplete;

  return (
    <article className="module-section-surface">
      <div className="module-section-header">
        <div className="module-section-heading">
          <p className="module-section-label">Language access</p>
          <h2 className="module-section-title">Publish this campaign in your community&rsquo;s languages</h2>
          <p className="module-section-description">
            OpenPlan can already translate what residents tell you. This is where you translate what you
            ask them — the campaign title, the topics, the survey questions, the updates you publish back.
            Anything you write here is published as your agency&rsquo;s own wording. A machine translation is
            published with a caveat saying so, until someone here accepts it.
          </p>
        </div>
        <span className="flex h-11 w-11 items-center justify-center rounded-[0.5rem] bg-sky-500/12 text-sky-700 dark:text-sky-300">
          <Languages className="h-5 w-5" />
        </span>
      </div>

      {readFailures.length > 0 ? (
        <div className="mt-4 space-y-2">
          {readFailures.map((failure) => (
            <p
              key={failure.label}
              className="rounded-[0.5rem] border border-amber-500/40 bg-amber-500/10 px-3 py-2 text-sm text-foreground"
            >
              {/*
                The label is a whole noun phrase, so it drops into either
                sentence unchanged. Prefixing one of them with "This campaign's"
                produced "This campaign's this campaign's translations could not
                be read" — which is what an operator on an unmigrated deployment
                was actually shown.
              */}
              {failure.schemaPending
                ? `This deployment's database does not have the translation storage yet, so ${failure.label} could not be read. Applying the pending migration turns this panel on; nothing below is a finding about this campaign.`
                : `OpenPlan could not read ${failure.label}, so what is shown below is incomplete — not a finding that there is nothing there.`}{" "}
              <span className="text-muted-foreground">({failure.message})</span>
            </p>
          ))}
        </div>
      ) : null}

      {/*
        THREE SENTENCES, NOT TWO, and the third is the whole point. "Nobody has
        recorded which language this campaign is written in" is a finding about
        the AGENCY. When the read simply FAILED, nobody established that — and
        saying it anyway is the same error the portal resolver refuses when it
        keeps `untranslated` and `unreadable` apart rather than rendering a
        database failure as English-by-choice. It is a live state, not a
        hypothesis: a deployment without 20260729000004 errors on this exact
        column.
      */}
      <p className="mt-4 text-sm text-muted-foreground">
        {!sourceLocaleReadable
          ? `Which language this campaign is written in could not be read, so OpenPlan is falling back to ${TRANSLATION_LANGUAGE_LABELS[sourceLocale]} to lay this screen out. That is a fallback, not a record — nobody has established what language this campaign is in, and the counts below are measured against a language that may be the wrong one.`
          : sourceLocaleStated
            ? `This campaign is written in ${TRANSLATION_LANGUAGE_LABELS[sourceLocale]}, so that language needs no translation.`
            : `Nobody has recorded which language this campaign is written in, so OpenPlan presumes ${TRANSLATION_LANGUAGE_LABELS[sourceLocale]} and tells participants only that the text is “as the project team wrote it”. Everything below is measured against that presumption.`}
      </p>

      {/* ── What may be claimed, per language ───────────────────────────── */}
      {coverage === null ? (
        <p className="mt-4 rounded-[0.5rem] border border-amber-500/40 bg-amber-500/10 px-3 py-2 text-sm text-foreground">
          Which languages this campaign is complete in is <strong>unknown</strong> right now, because{" "}
          {readFailures.length > 0
            ? readFailures.map((failure) => failure.label).join(", ")
            : "part of what this claim rests on"}{" "}
          could not be read.{" "}
          {!inventoryComplete && translationsReadable
            ? // The dangerous direction, named. A short inventory does not read as
              // an error on screen — it reads as a campaign with less text in it,
              // and every percentage computed from it rounds UP.
              "Coverage is withheld rather than measured against a list of strings that is known to be short: that would report a language as complete while the strings that failed to load are missing from it."
            : "That is not the same as none, and no coverage is shown rather than showing every language as untranslated."}
        </p>
      ) : (
        <>
          <ul role="list" className="mt-4 grid gap-2 md:grid-cols-2 xl:grid-cols-3">
            {coverage.map((row) => {
              const badge = STATE_LABELS[row.state];
              const rowChrome = portalMessageCoverage(row.locale);
              return (
                <li key={row.locale} className="rounded-[0.5rem] border border-border/70 p-3">
                  <div className="flex flex-wrap items-start justify-between gap-2">
                    <p className="text-sm font-medium text-foreground">
                      <span lang={row.locale} dir={PORTAL_LOCALE_DIRECTION[row.locale]}>
                        {row.nativeName}
                      </span>
                      <span className="ms-2 text-xs text-muted-foreground">{row.englishName}</span>
                    </p>
                    <StatusBadge tone={badge.tone}>{badge.label}</StatusBadge>
                  </div>
                  <p className="mt-1 text-xs text-muted-foreground">
                    {row.isSourceLocale
                      ? "The agency's own words, in the language they were written in."
                      : `Your text: ${row.operatorCount + row.machineCount} of ${row.total} strings translated${
                          row.machineCount > 0 ? ` (${row.machineCount} machine)` : ""
                        }.`}
                  </p>
                  {row.isSourceLocale ? null : (
                    <p className="mt-1 text-xs text-muted-foreground">
                      {rowChrome.complete
                        ? "OpenPlan's own page text: fully translated."
                        : // Named through the constant, not spelled "en": which
                          // language OpenPlan's own copy falls back to is a
                          // property of the catalog, and a literal here would go
                          // on saying "English" after that stopped being true.
                          `OpenPlan's own page text: ${rowChrome.translated} of ${rowChrome.total} phrases — the rest of the page shows in ${TRANSLATION_LANGUAGE_LABELS[PORTAL_DEFAULT_LOCALE]}, labelled.`}
                    </p>
                  )}
                  {row.staleCount > 0 ? (
                    <p className="mt-1 text-xs text-amber-700 dark:text-amber-300">
                      {row.staleCount} {row.staleCount === 1 ? "translation was" : "translations were"} made
                      from wording that has since changed.
                    </p>
                  ) : null}
                </li>
              );
            })}
          </ul>
          <p className="mt-3 text-xs text-muted-foreground">
            &ldquo;Complete&rdquo; means every one of the {fields.length} strings a participant reads on the
            public portal has a translation in that language. It does not mean a qualified translator reviewed
            it, and where the count says some are machine translations, participants are told so on the page.
          </p>
        </>
      )}

      {/* ── The editor ──────────────────────────────────────────────────── */}
      {targetLocales.length === 0 ? null : (
        <div className="mt-6">
          <p id="translation-language-choice" className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">
            Translate into
          </p>
          <div role="group" aria-labelledby="translation-language-choice" className="mt-2 flex flex-wrap gap-2">
            {targetLocales.map((candidate) => (
              <Button
                key={candidate}
                type="button"
                size="sm"
                variant={candidate === locale ? "default" : "outline"}
                aria-pressed={candidate === locale}
                onClick={() => setLocale(candidate)}
              >
                <span lang={candidate} dir={PORTAL_LOCALE_DIRECTION[candidate]}>
                  {TRANSLATION_LANGUAGE_NATIVE_LABELS[candidate]}
                </span>
                <span className="text-xs opacity-75">{TRANSLATION_LANGUAGE_LABELS[candidate]}</span>
              </Button>
            ))}
          </div>
          {chrome.complete ? null : (
            // The half an operator cannot fix from this screen, said plainly
            // where the work is happening. Translating every string below still
            // leaves a page with English buttons on it, and an agency that is
            // told that can decide what to claim; one that is not, cannot.
            <p className="mt-2 text-xs text-muted-foreground">
              OpenPlan&rsquo;s own page text is {chrome.translated} of {chrome.total} phrases translated into{" "}
              {englishName}. Even with everything below translated, a participant reading {englishName} sees the
              rest of the page in {TRANSLATION_LANGUAGE_LABELS[PORTAL_DEFAULT_LOCALE]} — the portal tells them so
              rather than leaving it unlabelled.
            </p>
          )}
        </div>
      )}

      {/* One live region for every outcome, so a screen-reader user hears the
          result of a save without hunting for where it landed. */}
      <div role="status" aria-live="polite" className="mt-4 space-y-2">
        {state.notice ? (
          <p className="rounded-[0.5rem] border border-border/60 bg-muted/20 px-3 py-2 text-sm text-muted-foreground">
            {state.notice}
          </p>
        ) : null}
        {state.error ? (
          <p className="rounded-[0.5rem] border border-destructive/40 bg-destructive/10 px-3 py-2 text-sm text-foreground">
            {state.error}
          </p>
        ) : null}
      </div>

      {!canWrite ? (
        <p className="mt-4 text-sm text-muted-foreground">
          Your workspace role can read this campaign&rsquo;s translations but not change them.
        </p>
      ) : !translationsReadable ? (
        <p className="mt-4 rounded-[0.5rem] border border-amber-500/40 bg-amber-500/10 px-3 py-2 text-sm text-foreground">
          Editing is off because this campaign&rsquo;s existing translations could not be read. Saving from
          empty boxes could overwrite wording a colleague already published and this page cannot see.
        </p>
      ) : !inventoryComplete ? (
        <p className="mt-4 rounded-[0.5rem] border border-amber-500/40 bg-amber-500/10 px-3 py-2 text-sm text-foreground">
          Editing is off because part of what this campaign shows participants could not be read, so the list
          below is known to be short. Saving would be refused anyway — the write checks every string against
          this campaign&rsquo;s own text before it stores a translation, and it cannot do that from a partial
          list.
        </p>
      ) : languageMachineRefusal ? (
        <p className="mt-4 rounded-[0.5rem] border border-border/60 bg-muted/20 px-3 py-2 text-sm text-muted-foreground">
          {languageMachineRefusal}
        </p>
      ) : !machineTranslationAvailable ? (
        <p className="mt-4 rounded-[0.5rem] border border-border/60 bg-muted/20 px-3 py-2 text-sm text-muted-foreground">
          Machine translation is unavailable: no Anthropic API key is configured for this workspace or this
          deployment. You can still write every translation by hand — and hand-written translations are the
          only kind the portal publishes without a caveat.
        </p>
      ) : null}

      {editable && fields.length > 0 ? (
        <div className="mt-4 flex flex-wrap gap-2">
          {machineTranslationOffered && untranslatedKeys.length > 0 ? (
            <>
              <Button
                type="button"
                size="sm"
                variant="outline"
                disabled={busy}
                onClick={() => void suggest(untranslatedKeys)}
              >
                {state.busy?.startsWith("suggest:") ? <Loader2 className="h-4 w-4 animate-spin" /> : null}
                Draft the {Math.min(untranslatedKeys.length, machineBatchMax)} untranslated with machine
                translation
              </Button>
              <Button
                type="button"
                size="sm"
                variant="secondary"
                disabled={busy}
                onClick={() => void publishMachine(untranslatedKeys)}
              >
                Publish those as labelled machine translations
              </Button>
            </>
          ) : null}
          {machineKeys.length > 0 ? (
            <Button type="button" size="sm" variant="secondary" disabled={busy} onClick={() => void accept(machineKeys)}>
              {/* The count the request will actually carry, not the count on
                  screen — a button that says "all 240" and promotes 200 has
                  misreported which sentences the agency just took ownership of. */}
              Accept {Math.min(machineKeys.length, acceptBatchMax)} machine{" "}
              {Math.min(machineKeys.length, acceptBatchMax) === 1 ? "translation" : "translations"} as our wording
            </Button>
          ) : null}
        </div>
      ) : null}

      {fields.length === 0 ? (
        <p className="mt-5 text-sm text-muted-foreground">
          This campaign has no participant-facing text yet. Give it a title, some topics, or a survey and they
          will appear here to translate.
        </p>
      ) : (
        <div className="mt-5 space-y-5">
          {groups.map((group) => (
            <section key={group.key} aria-label={group.label}>
              <h3 className="text-sm font-semibold text-foreground">{group.label}</h3>
              <ul role="list" className="mt-2 space-y-3">
                {group.fields.map((field) => {
                  const entry = entryByKey.get(field.key);
                  const value = draftValue(field);
                  const dirty = value.trim() !== (entry?.text ?? "");

                  return (
                    <li key={field.key} className="rounded-[0.5rem] border border-border/70 p-3">
                      <div className="flex flex-wrap items-start justify-between gap-2">
                        <p className="text-sm font-medium text-foreground">{field.label}</p>
                        {!translationsReadable ? (
                          <StatusBadge tone="warning">Unknown — could not be read</StatusBadge>
                        ) : entry?.source === "operator" ? (
                          <StatusBadge tone="success">Your agency&rsquo;s wording</StatusBadge>
                        ) : entry?.source === "machine" ? (
                          <StatusBadge tone="warning">Machine translation — participants are told</StatusBadge>
                        ) : (
                          <StatusBadge tone="neutral">Not translated</StatusBadge>
                        )}
                      </div>

                      <p className="mt-2 text-xs uppercase tracking-[0.16em] text-muted-foreground">
                        As written ({TRANSLATION_LANGUAGE_LABELS[sourceLocale]})
                      </p>
                      <p
                        lang={sourceLocale}
                        dir={sourceDirection}
                        className="mt-1 whitespace-pre-line text-sm text-muted-foreground"
                      >
                        {field.sourceText}
                      </p>

                      {entry?.stale ? (
                        <p className="mt-2 text-xs text-amber-700 dark:text-amber-300">
                          The original changed after this was translated, so the{" "}
                          {englishName} above may no longer say the same thing. Re-check it.
                        </p>
                      ) : null}

                      <label
                        className="mt-3 block text-xs uppercase tracking-[0.16em] text-muted-foreground"
                        htmlFor={`translation-${field.key}`}
                      >
                        In <span lang={locale} dir={direction}>{nativeName}</span> ({englishName})
                      </label>
                      <Textarea
                        id={`translation-${field.key}`}
                        // The whole point of the direction plumbing: an Arabic or
                        // Farsi editor that reads left-to-right is unusable, and a
                        // screen reader told the wrong language is unintelligible.
                        lang={locale}
                        dir={direction}
                        className="mt-1 text-start"
                        rows={field.multiline ? 3 : 1}
                        value={value}
                        readOnly={!editable}
                        onChange={(event) => setDraft(field, event.target.value)}
                        placeholder={editable ? `${field.label} in ${englishName}` : undefined}
                      />

                      {entry?.source === "machine" ? (
                        <div className="mt-2 rounded-[0.5rem] border border-amber-500/40 bg-amber-500/10 px-3 py-2">
                          <p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">
                            What a participant reads with it today
                          </p>
                          {machineCaveat ? (
                            // Its OWN language and direction, which are the
                            // target language's only when this locale has a
                            // catalog. See `machineCaveat` above.
                            <p
                              lang={machineCaveat.lang}
                              dir={machineCaveat.dir}
                              className="mt-1 text-sm text-foreground"
                            >
                              {machineCaveat.sentence}
                            </p>
                          ) : null}
                          <p className="mt-2 text-xs text-muted-foreground">
                            {entry.model
                              ? `Produced by ${entry.model}. ${ACCEPT_CONSEQUENCE}`
                              : ACCEPT_CONSEQUENCE}
                          </p>
                        </div>
                      ) : null}

                      {editable ? (
                        <div className="mt-3 flex flex-wrap gap-2">
                          <Button
                            type="button"
                            size="sm"
                            disabled={busy || !dirty || value.trim().length === 0}
                            onClick={() => void save([field.key])}
                          >
                            {state.busy === `save:${field.key}` ? (
                              <Loader2 className="h-4 w-4 animate-spin" />
                            ) : null}
                            Save as our wording
                          </Button>
                          {entry?.source === "machine" ? (
                            <Button
                              type="button"
                              size="sm"
                              variant="secondary"
                              disabled={busy}
                              onClick={() => void accept([field.key])}
                            >
                              Accept as our wording
                            </Button>
                          ) : null}
                          {machineTranslationOffered ? (
                            <>
                              <Button
                                type="button"
                                size="sm"
                                variant="outline"
                                disabled={busy}
                                onClick={() => void suggest([field.key])}
                              >
                                Draft with machine translation
                              </Button>
                              <Button
                                type="button"
                                size="sm"
                                variant="outline"
                                disabled={busy}
                                onClick={() => void publishMachine([field.key])}
                              >
                                Publish as machine translation
                              </Button>
                            </>
                          ) : null}
                          {entry ? (
                            <Button
                              type="button"
                              size="sm"
                              variant="ghost"
                              disabled={busy}
                              onClick={() => void withdraw(field)}
                            >
                              Withdraw
                            </Button>
                          ) : null}
                        </div>
                      ) : null}
                    </li>
                  );
                })}
              </ul>
            </section>
          ))}
        </div>
      )}
      {confirmDialog}
    </article>
  );
}
