'use client';
import { useEffect,useState } from 'react';
import { Button } from '@/components/ui/button';
type Session={id:string;status:string;created_at:string;updated_at:string;configuration_version_id:string|null};
type Answer={id:string;session_id:string;question_prompt_snapshot:string|null;answer_text:string|null;answer_json:unknown};
function ResponseReview({session,answers,onReviewed,campaignId}:{session:Session;answers:Answer[];onReviewed:()=>void;campaignId:string}) {
 const [history,setHistory]=useState<Array<{id:string;actor_id:string|null;recorded_at:string;reason:string;before_json:unknown;after_json:unknown}>|null>(null);
 const [reason,setReason]=useState(''),[redactions,setRedactions]=useState<Record<string,string>>({}),[error,setError]=useState<string|null>(null),[busy,setBusy]=useState(false);
 async function review(status:string){setBusy(true);try{const response=await fetch(`/api/engagement/campaigns/${campaignId}/survey/review`,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({sessionId:session.id,expectedUpdatedAt:session.updated_at,status,reason,redactions})});const data=await response.json();if(!response.ok)throw new Error(data.error);onReviewed();}catch(cause){setError(cause instanceof Error?cause.message:'Review failed');}finally{setBusy(false);}}
 return <article className="rounded border p-4 space-y-3"><h3 className="break-all font-semibold">Survey response {session.id}</h3><p>{session.status} · {session.created_at}</p><p className="text-xs break-all">Configuration {session.configuration_version_id||'Historical definition unavailable'}</p>
 {answers.map(answer=><div key={answer.id} className="space-y-2"><h4>{answer.question_prompt_snapshot||'Historical prompt unavailable'}</h4><p className="whitespace-pre-wrap break-words">{answer.answer_text||JSON.stringify(answer.answer_json)}</p><label className="text-sm"><input type="checkbox" checked={answer.id in redactions} onChange={event=>setRedactions(current=>{const next={...current};if(event.target.checked)next[answer.id]='[Withheld following staff review]';else delete next[answer.id];return next;})}/> Replace this answer with a reviewed public copy</label>{answer.id in redactions?<textarea aria-label={`Reviewed answer ${answer.id}`} className="block w-full rounded border p-2" value={redactions[answer.id]} onChange={event=>setRedactions({...redactions,[answer.id]:event.target.value})}/>:null}</div>)}
 <Button type="button" variant="outline" onClick={async()=>{try{const response=await fetch(`/api/engagement/campaigns/${campaignId}/survey/review?sessionId=${session.id}`);const payload=await response.json();if(!response.ok)throw new Error(payload.error);setHistory(payload.history);}catch(cause){setError(cause instanceof Error?cause.message:'History unavailable');}}}>Read survey review history</Button>
 {history?<details open><summary>Restricted survey history ({history.length})</summary>{history.length===0?<p>No reviews retained yet.</p>:history.map(entry=><article className="my-3 rounded border p-3 break-words" key={entry.id}><p>{entry.recorded_at} · {entry.reason}</p><p>Reviewer {entry.actor_id||'Unavailable'}</p><p className="whitespace-pre-wrap">Before: {JSON.stringify(entry.before_json,null,2)}</p><p className="whitespace-pre-wrap">After: {JSON.stringify(entry.after_json,null,2)}</p></article>)}</details>:null}
 <p className="text-xs">A redacted answer retains its original in restricted history. It is exported as reviewed text and must not be counted as an original numeric or choice answer.</p>
 <label className="block">Review reason<textarea className="block w-full rounded border p-2" value={reason} onChange={event=>setReason(event.target.value)}/></label>
 {error?<p role="alert">{error}</p>:null}<div className="flex gap-3"><Button type="button" disabled={busy||!reason.trim()} onClick={()=>review('approved')}>Approve reviewed response</Button><Button type="button" variant="outline" disabled={busy||!reason.trim()} onClick={()=>review('rejected')}>Withhold response</Button></div></article>;
}
export function SurveyReviewQueue({campaignId}:{campaignId:string}) {
 const [page,setPage]=useState(0),[revision,setRevision]=useState(0),[data,setData]=useState<{sessions:Session[];answers:Answer[];total:number}|null>(null),[error,setError]=useState<string|null>(null);
 useEffect(()=>{let active=true;void fetch(`/api/engagement/campaigns/${campaignId}/survey/review?page=${page}`).then(async response=>{const result=await response.json();if(!active)return;if(!response.ok)setError(result.error||'Survey responses unavailable');else{setData(result);setError(null);}}).catch(()=>{if(active)setError('Survey responses unavailable');});return()=>{active=false;};},[campaignId,page,revision]);
 return <section className="module-section-surface space-y-4"><h2 className="module-section-title">Survey response review</h2>{error?<p role="alert">{error}</p>:null}{data?<><p>{data.total} received survey responses. Page {page+1} of {Math.max(1,Math.ceil(data.total/20))}.</p><div className="flex gap-3"><Button type="button" variant="outline" disabled={page===0} onClick={()=>setPage(page-1)}>Previous survey page</Button><Button type="button" variant="outline" disabled={(page+1)*20>=data.total} onClick={()=>setPage(page+1)}>Next survey page</Button></div>{data.sessions.map(session=><ResponseReview key={`${session.id}:${session.updated_at}`} session={session} answers={data.answers.filter(answer=>answer.session_id===session.id)} campaignId={campaignId} onReviewed={()=>setRevision(revision+1)}/>)}</>:<p>Loading survey responses…</p>}</section>;
}
