import { settlementPosition } from "./closeout";
import { accountingHandoffRows, type CloseoutPackage } from "./closeout-export";
import JSZip from "jszip";
import { formatWorkProgramWorkbook } from "@/lib/programs/work-program/workbook-layout";
import { utils } from "xlsx";
import { writeWorkProgramWorkbook } from "@/lib/programs/work-program/export";
import { renderReportPdf } from "@/lib/reports/pdf";
import { reconcileSnapshot, contractMetrics, type Rollup } from "./reconciliation";
import type { ContractSnapshot } from "./schema";
const escape = (v: unknown) => String(v ?? "Unassessed").replace(/[&<>"']/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
type Cell = string | number | null;
export function contractSnapshotTables(report: ContractSnapshot): { name: string; rows: Cell[][] }[] {
 const state = report.snapshot, r = reconcileSnapshot(report);
 const tables: { name: string; rows: Cell[][] }[] = [{ name: "Identity", rows: [
  ["Internal contract management snapshot", report.title], ["Issued", report.created_at], ["Contract", state.engagement.title], ["Project ID", state.engagement.project_id], ["Contract ID", state.engagement.id], ["As of", state.asOf], ["Source cutoff", state.sourceCutoff], ["Original approved baseline", state.originalBaselineId], ["Current approved baseline", state.baselineId], ["Baseline hash", r.baseline?.content_hash ?? null], ["Snapshot ID", report.id], ["Snapshot hash", report.snapshot_hash], ["Currency", r.baseline?.content.currency ?? null], ["Coverage evidence", state.coverageEvidence], ["Coverage attestation", state.coverageComplete ? "Complete source coverage attested by issuer" : "Incomplete or unassessed"], ["Meaning", (state.schemaVersion??0)>=3?"Internal management. Reviewed forecasts retain their assumptions and do not change approved dates, establish deliverable acceptance, accounting revenue or external authority.":"Internal management. No accounting replacement, funder reimbursement, legal authority, accepted progress or forecast finish date is established."],
 ] }];
 const costMetrics=(state.schemaVersion??0)>=7?contractMetrics.filter(k=>k!=="payments"&&k!=="credits"):contractMetrics;
 function rows(values: Rollup[]): Cell[][] { return [["Work", ...costMetrics], ...values.map(v => [v.label, ...costMetrics.map(k => v.totals[k])])]; }
 if((state.schemaVersion??0)>=7&&state.closeout){
  tables.push({name:"Current invoice position",rows:[["Invoice and direction","Measure","Amount and currency"],...settlementPosition(state,state.asOf).flatMap(i=>(["gross","payments","credits","refunds","retention","disputed","open","currentlyDue"] as const).map(metric=>[`${i.number} / ${i.direction}`,metric==="currentlyDue"?"Currently due":metric,`${i[metric]??"Unassessed"} ${i.currency}`]))]});
  const current=state.closeout.versions.at(-1),closed=state.closeout.versions.filter(v=>v.state==="closed").at(-1);
  tables.push({name:"Closeout position",rows:[["Measure","Retained position"],["Current assignment state",current?.state??"No closeout retained"],["Last closed revision",closed?.version??null],["Last closeout incurred cost",closed?.content.position?.incurred??null],["Last closeout underspend",closed?.content.position?.underspend??null],["Last closeout work acceptance",closed?String(closed.content.request.workAccepted):null],["Last closeout financial settlement",closed?String(closed.content.request.financialSettled):null],["Continuing open obligations",closed?.content.request.obligations?.filter(o=>o.status==="open").length??null],["Meaning","Reopening does not revoke prior acceptance or settle later work. Review the current revision and continuing obligations."]]});
 }

 tables.push({ name: "Contract totals", rows: rows([{ id: "total", label: "Contract", totals: r.total }]) }, { name: "Tasks", rows: rows(r.byTask) }, { name: "Staff", rows: rows(r.byStaff) }, { name: "Deliverables", rows: rows(r.byDeliverable) });
 const latestForecast=state.delivery?.forecasts.at(-1),reviewedForecast=latestForecast?.input_hash===state.delivery?.inputHash?latestForecast?.content.result:undefined;
 tables.push({ name: "Budget and billing", rows: [["Measure", "Amount"], ["Approved fee", r.baseline?.content.fee ?? null], ["Approved internal cost", r.baseline?.content.cost ?? null], [(state.schemaVersion??0)>=6?r.billingLabel:"Gross billed before retention", r.grossBilled], [(state.schemaVersion??0)>=5?"Retention stated on issued invoices":"Invoice retention", r.retention], [(state.schemaVersion??0)>=5?"Unbilled gross fee":"Gross fee remaining after credits", r.grossFeeRemaining], [(state.schemaVersion??0)>=5?"Reviewed forecast remaining cost":"Remaining cost estimate",(state.schemaVersion??0)>=5?reviewedForecast?.remainingCost??null:r.remainingCost], [(state.schemaVersion??0)>=5?"Reviewed forecast actual plus remaining":"Actual plus remaining",(state.schemaVersion??0)>=5?reviewedForecast?.actualPlusRemaining??null:r.actualPlusRemaining], ["Unknown historical hours", r.unknownHours]] });
 if((state.schemaVersion??0)>=6)tables.push({name:"Agreement billing perspective",rows:[["Baseline ID","Version","State","Direction","Terms"],...state.baselines.map(b=>[b.id,b.version,b.state,b.content.billingDirection??"outgoing (legacy convention)",b.content.feeTerms])]});
 tables.push({ name: "Baseline history", rows: [["Version", "State", "Identity", "Scope", "Fee", "Cost", "Hours", "Approval evidence", "Source documents", "Hash"], ...state.baselines.map(b => [b.version, b.state, b.id, b.content.scope, b.content.fee, b.content.cost, b.content.hours, b.approval_evidence, b.content.sourceDocuments.join(", "), b.content_hash])] });
 tables.push({ name: "Remaining work", rows: [["Task", "Agreed deadline", "Estimate date", "Remaining hours", "Remaining cost", "Estimate basis", "Independent progress", "Progress note"], ...r.estimates.map(e => [e.task.title, e.task.deadline, e.estimate?.command.asOf ?? null, e.estimate?.command.hours ?? null, e.estimate?.command.cost ?? null, e.estimate?.command.basis ?? null, e.estimate?.command.progress ?? null, e.estimate?.command.progressNote ?? null])] });
 tables.push({ name: "Source history", rows: [["Source", "Version", "Recorded", "Date", "Category", "Status", "Amount", "Hours", "Reference", "Correction", "Physical source", "OWP version"], ...state.actuals.map(v => [v.command.sourceKey, v.version, v.created_at, v.command.entryDate, v.command.category, v.command.status, v.amount, v.hours, v.command.sourceReference, v.command.correctionNote, v.time_entry_id ?? v.spend_entry_id, v.command.owpVersionId])] });
 tables.push({ name: "Allocations", rows: [["Source", "Version", "Task", "Deliverable", "Share (basis points)", "Amount", "Hours"], ...state.actuals.flatMap(v => v.allocations.map(a => [v.command.sourceKey, v.version, a.taskId, a.deliverableId, a.share, a.amount, a.hours]))] });
 tables.push({ name: "Unresolved", rows: [["Record", "State", "Known amount", "Known hours"], ...r.unresolved.map(v => [v.command.sourceKey, v.shared_source_stale?"Shared OWP source requires reconciliation":r.overlappingOpenings.includes(v)?"Opening overlap requires reconciliation":v.command.status, v.amount, v.hours]), ...state.unmappedSpend.map(v => [v.id, "Project spending not mapped to this contract", v.amount, null]), ...state.unmappedTime.map(v => [v.id, "Contract time not reviewed", null, v.hours])] });
 tables.push({ name: "Approved task budgets", rows: [["Task", "Fee", "Internal cost", "Hours", "Agreed deadline", "Scope"], ...(r.baseline?.content.tasks??[]).map(t=>[t.title,t.fee,t.cost,t.hours,t.deadline,t.scope])] });
 tables.push({ name: "Approved staff budgets", rows: [["Task", "Staff", "Hours", "Internal cost"], ...(r.baseline?.content.tasks??[]).flatMap(t=>t.staff.map(s=>[t.title,state.staff.find(p=>p.id===s.staffId)?.name??s.staffId,s.hours,s.cost]))] });
 tables.push({ name: "Billing source allocations", rows: [["Invoice", "Source entry", "Valuation version", "Billing rate", "Task", "Deliverable", "Gross fee", "Hours"], ...(state.billingSources??[]).flatMap(s=>s.lines.map(l=>[s.invoice_id,s.entry_id,s.actual_version_id,s.billing_rate_id,l.taskId,l.deliverableId,l.amount,l.hours]))] });
 tables.push({ name: "Valuation evidence", rows: [["Source", "Version", "Basis", "Cost rate", "Opening coverage", "Opening basis", "Overlap reconciliation", "Shared source state"], ...state.actuals.map(v=>[v.command.sourceKey,v.version,v.command.valuationBasis,v.command.rateId,`${v.command.openingStart??""} to ${v.command.openingEnd??""}`,v.command.openingBasis,v.command.reconciliationNote,v.shared_source_stale?"OWP correction requires reconciliation":"Retained valuation"])] });
 tables.push({ name: "Rates", rows: [["Staff", "Basis", "Effective start", "Effective end", "Rate", "Source", "Identity"], ...state.rates.map(v => [state.staff.find(s => s.id === v.staff_id)?.name ?? v.staff_id, v.basis, v.starts_on, v.ends_on, v.hourly_rate, v.source_reference, v.id])] });
 tables.push({name:"Agreement evidence",rows:[["Baseline","Document","Title","SHA-256","Retained file","Bytes"],...state.baselines.flatMap(b=>(b.source_receipts??[]).map(d=>[b.id,d.id,d.title,d.checksum,d.storageRef,d.bytes]))]});
 tables.push({name:"Staff budget coverage",rows:[["Task","Cost not allocated to staff","Hours not allocated to staff","Unknown staff costs","Unknown staff hours","Meaning"],...r.staffBudgetRemainders.map(b=>[b.task.title,b.cost,b.hours,b.unknownCost,b.unknownHours,"Difference from known staff allocations. May include direct expenses; consult the retained task scope."])]});
 if((state.schemaVersion??0)>=2){
  const retainedMasterTerms=[...(state.masterTerms??[]),...(state.parentMasterTerms?[state.parentMasterTerms]:[])];
  tables.push({name:"Master source custody",rows:[["Version","Document","SHA-256","Retained file","Bytes"],...retainedMasterTerms.map(t=>[t.version,t.source_receipt?.id??t.source_document_id,t.source_receipt?.checksum??null,t.source_receipt?.storageRef??null,t.source_receipt?.bytes??null])]});
  tables.push({name:"Master authorization",rows:[["Version","State","Currency","Shared ceiling","Authorized start","Authorized end","Terms","Approval evidence"],...retainedMasterTerms.map(t=>[t.version,t.state,t.currency,t.ceiling,t.starts_on,t.ends_on,t.terms,t.approval_evidence])]});
  tables.push({name:"Authorized work basis",rows:[["Baseline","Start","End","Beneficiary","Funding reference","Cost basis","Eligibility assessment","Eligibility evidence"],...state.baselines.map(b=>[b.version,b.content.authorization?.startsOn??null,b.content.authorization?.endsOn??null,b.content.authorization?.beneficiary??null,b.content.authorization?.funding??null,b.content.authorization?.costBasis??null,b.content.authorization?.eligibility??"unassessed",b.content.authorization?.eligibilityEvidence??null])]});
  tables.push({name:"Legacy period evidence",rows:[["Baseline","Version","Start","End","Beneficiary","Funding","Cost basis","Eligibility","Eligibility evidence","Source document","Review evidence"],...(state.orderPeriods??[]).map(p=>[p.baseline_id,p.version,p.authorization.startsOn,p.authorization.endsOn,p.authorization.beneficiary,p.authorization.funding,p.authorization.costBasis,p.authorization.eligibility,p.authorization.eligibilityEvidence,p.source_document_id,p.evidence])]});
  tables.push({name:"Received invoices",rows:[["Identity","Number","Version","State","Date","Currency","Amount","Original file","Review evidence"],...(state.receivedInvoices??[]).map(i=>[i.invoice_id,i.content.number,i.version,i.state,i.content.date,i.content.currency,i.content.total,i.content.fileId,i.review_note])]});
  if((state.schemaVersion??0)>=7)tables.push({name:"Received original files",rows:[["Invoice version","File ID","Filename","SHA-256","Content type","Bytes"],...(state.receivedInvoices??[]).map(i=>[i.id,i.source_receipt?.id??i.content.fileId,i.source_receipt?.filename??null,i.source_receipt?.checksum??null,i.source_receipt?.contentType??null,i.source_receipt?.bytes??null])]});
  tables.push({name:"Received cost treatment",rows:[["Invoice","Version","Treatment","Description","Amount","Documented basis"],...(state.receivedInvoices??[]).flatMap(i=>i.content.lines.map(l=>[i.invoice_id,i.version,l.treatment,l.description,l.amount,l.basis]))]});
  tables.push({name:"Received source matching",rows:[["Invoice","Version","Source entry","Valuation version","Matched amount"],...(state.receivedInvoices??[]).flatMap(i=>(i.matches??[]).map(m=>[i.invoice_id,i.version,m.entryId,m.versionId,m.amount]))]});
  tables.push({name:"Accounting comparison",rows:[["Import","Original file","Original SHA-256","Row","External posting","Source key","External amount","External hours","Currency"],...(state.accountingImports??[]).flatMap(i=>i.rows.map((v,index)=>[i.id,i.filename,i.source_hash,index,v.externalId,v.sourceKey,v.amount,v.hours,v.currency]))]});
  tables.push({name:"Accounting review history",rows:[["Import","Row","Version","Source valuation","State","Evidence","Recorded"],...(state.accountingReviews??[]).map(r=>[r.import_id,r.row_index,r.version,r.actual_version_id,r.state,r.evidence,r.created_at])]});
 }
 if((state.schemaVersion??0)>=3&&state.delivery){
  const d=state.delivery;
  tables.push({name:"Reviewed forecasts",rows:[["Version","Issued","As of","Horizon","Supported finish","Remaining cost","Actual plus remaining","Expected gross billing","Input SHA-256","Current at snapshot","Review evidence","Coverage evidence"],...d.forecasts.map(f=>[f.version,f.created_at,f.content.result.asOf,f.content.result.horizonEnd,f.content.result.finish,f.content.result.remainingCost,f.content.result.actualPlusRemaining,f.content.result.remainingGrossBilling,f.input_hash,f.input_hash===d.inputHash?"Unchanged inputs":"Stale inputs",f.content.reviewEvidence,f.content.coverageEvidence])]});
  tables.push({name:"Forecast dates",rows:[["Forecast version","Schedule item","Task","Original approved finish","Current approved finish","Forecast start","Forecast finish","Actual start","Actual finish"],...d.forecasts.flatMap(f=>f.content.result.nodes.map(n=>[f.version,n.title,n.taskId,n.originalApprovedFinish,n.currentApprovedFinish,n.start,n.finish,n.actualStart,n.actualFinish]))]});
  tables.push({name:"Forecast warnings",rows:[["Forecast version","Cause","Schedule item","Staff","Date","Explanation"],...d.forecasts.flatMap(f=>f.content.result.warnings.map(w=>[f.version,w.code,w.nodeId,w.staffId,w.date,w.message]))]});
  tables.push({name:"Staff work review history",rows:[["Task","Staff","Version","State","As of","Remaining hours","Availability per day","Reported status","Blockers","Actual start","Actual finish","Remaining cost","Expected gross billing","Valuation evidence","Reviewed input ID","Review evidence"],...d.workUpdates.map(u=>[u.task_id,u.staff_id,u.version,u.state,u.content.asOf,u.content.hours,u.content.availableHoursPerDay,u.content.status,u.content.blockers,u.content.actualStart,u.content.actualFinish,u.remaining_cost,u.remaining_gross_billing,u.valuation_evidence,u.reviewed_update_id??null,u.evidence])]});
  tables.push({name:"Schedule assumptions",rows:[["Version","Assumptions","Update due","Billing treatment","Billing evidence"],...d.scheduleVersions.map(s=>[s.version,s.content.assumptions,s.content.updateDueOn,s.content.billingTreatment,s.content.billingEvidence])]});
  tables.push({name:"Schedule review periods",rows:[["Version","Item","Kind","Earliest start","Reservation end","Dependencies","Duration days","Day counting","Reviewer availability","Review evidence","Calendar","Weekdays","Dated exceptions"],...d.scheduleVersions.flatMap(s=>s.content.nodes.map(n=>[s.version,n.title,n.kind,n.notBefore,n.reserveThrough,n.predecessors.join(", "),n.durationDays,n.durationKind,n.reviewStatus,n.reviewEvidence,n.calendar.name,n.calendar.weekdays.join(", "),n.calendar.exceptions.map(e=>`${e.date}: ${e.working?"working":"unavailable"}; ${e.reason}`).join("\n")]))]});
  tables.push({name:"Shared capacity",rows:[["Staff","Version","Start","End","Hours per working day","Calendar","Weekdays","Exceptions","Evidence"],...d.capacityVersions.map(c=>[c.staff_id,c.version,c.content.startsOn,c.content.endsOn,c.content.hoursPerDay,c.content.calendar.name,c.content.calendar.weekdays.join(", "),c.content.calendar.exceptions.map(e=>`${e.date}: ${e.working?"working":"unavailable"}; ${e.reason}`).join("\n"),c.content.evidence])]});
 }
 if(state.responses){
  tables.push({name:"PM response comparisons",rows:[["Response ID","Forecast ID","Recorded","Project record","Exact record version","Response evidence","Before finish","Proposed finish","Before remaining cost","Proposed remaining cost","Input SHA-256"],...state.responses.responses.map(r=>[r.id,r.forecast_id,r.created_at,r.content.record.title,r.content.record.updated_at,r.content.request.evidence,r.content.before.finish,r.content.after.finish,r.content.before.remainingCost,r.content.after.remainingCost,r.input_hash])]});
  tables.push({name:"Response assumptions",rows:[["Response ID","Task","Staff","Remaining hours","Available hours per day","Remaining cost","Expected gross billing","Valuation basis","Assumption evidence"],...state.responses.responses.flatMap(r=>r.content.request.workAssumptions.map(a=>[r.id,a.update.taskId,a.update.staffId,a.update.hours,a.update.availableHoursPerDay,a.remainingCost,a.remainingGrossBilling,a.valuationEvidence,a.update.evidence]))]});
  tables.push({name:"Applied working responses",rows:[["Response ID","Schedule ID","Recorded","Decision evidence"],...state.responses.applications.map(a=>[a.response_id,a.schedule_id,a.created_at,a.evidence])]});
 }
 if(state.closeout){
  tables.push({name:"Invoice settlement",rows:[["Invoice","Direction","Currency","Gross","Payments","Credits","Refunds","Adjustments","Retention","Disputed","Open balance","Currently due","Unresolved evidence"],...settlementPosition(state,state.asOf).map(i=>[i.number,i.direction,i.currency,i.gross,i.payments,i.credits,i.refunds,i.adjustments,i.retention,i.disputed,i.open,i.currentlyDue,i.warnings.join("; ")])]});
  tables.push({name:"Financial event history",rows:[["Event ID","Version ID","Version","Source ID","Invoice","Direction","Date","Kind","Amount","Currency","State","Legacy actual","Original source SHA-256","Source reference","Correction evidence"],...state.closeout.settlements.map(e=>[e.content.eventId,e.id,e.version,e.content.sourceKey,e.content.invoiceId,e.content.direction,e.content.date,e.content.kind,e.content.amount,e.content.currency,e.content.state,e.content.legacyActualId,e.source_receipt.checksum,e.content.sourceReference,e.content.correctionEvidence])]});
  tables.push({name:"Deliverable acceptance",rows:[["Event ID","Deliverable","Version","State","Date","Responsible authority","Review evidence","Original artifact","SHA-256",...((state.schemaVersion??0)>=7?["Storage reference","Retained bytes"]:["Retained bytes"])],...state.closeout.deliverableEvents.map(e=>[e.id,e.deliverable_id,e.version,e.state,e.date,e.authority,e.evidence,e.source_receipt.id,e.source_receipt.checksum,e.source_receipt.storageRef,...((state.schemaVersion??0)>=7?[e.source_receipt.bytes]:[])])]});
  tables.push({name:"Closeout revisions",rows:[["Revision ID","Version","State","Predecessor","Recorded","Work acceptance claimed","Financial settlement claimed","Incurred cost","Underspend","Decision evidence","Package SHA-256"],...state.closeout.versions.map(v=>[v.id,v.version,v.state,v.previous_id,v.created_at,String(v.content.request.workAccepted??false),String(v.content.request.financialSettled??false),v.content.position?.incurred??null,v.content.position?.underspend??null,v.content.evidence??v.content.request.evidence,v.content_hash])]});
  tables.push({name:"Continuing obligations",rows:[["Closeout revision","Obligation ID","Obligation","Responsible person","Due","State","Documented basis"],...state.closeout.versions.flatMap(v=>(v.content.request.obligations??[]).map(o=>[v.version,o.id,o.title,o.owner,o.dueOn,o.status,o.basis]))]});
  const issued=state.closeout.versions.filter(v=>v.state==="closed").at(-1)?.content.package as CloseoutPackage|undefined;
  if(issued?.formatVersion===1||issued?.formatVersion===2||issued?.formatVersion===3)tables.push({name:"Accounting handoff",rows:accountingHandoffRows(issued)});
 }
 return tables;
}
export function contractSnapshotHtml(report: ContractSnapshot) {
 return `<!doctype html><html lang="en"><meta charset="utf-8"><title>${escape(report.title)}</title><style>@page{size:A4 landscape;margin:14mm}body{font:11px Arial;color:#17323e}h1{font-size:25px}h2{break-after:avoid}table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{padding:7px;border:1px solid #cad4d8;text-align:left;overflow-wrap:anywhere;vertical-align:top;white-space:pre-wrap}th{background:#24515f;color:white}thead{display:table-header-group}tr,.record{break-inside:avoid}.record{padding:8px;border-bottom:1px solid #cad4d8}section{margin-top:20px}</style><body><h1>${escape(report.title)}</h1>${contractSnapshotTables(report).map(t => `<section><h2>${escape(t.name)}</h2>${t.rows[0].length>6 ? t.rows.slice(1).map(row => `<div class="record">${row.map((v,i) => `<p><strong>${escape(t.rows[0][i])}:</strong> ${escape(v)}</p>`).join("")}</div>`).join("") : `<table><thead><tr>${t.rows[0].map(v => `<th>${escape(v)}</th>`).join("")}</tr></thead><tbody>${t.rows.slice(1).map(row => `<tr>${row.map(v => `<td>${escape(v)}</td>`).join("")}</tr>`).join("")}</tbody></table>`}</section>`).join("")}</body></html>`;
}
export function contractSnapshotWorkbook(report: ContractSnapshot) {
 const book = utils.book_new();
 const typedColumns=(report.snapshot.schemaVersion??0)>=7;
 const amountHeaders=new Set<string>([...contractMetrics,"Amount","Hours","Fee","Cost","Gross","Payments","Credits","Refunds","Adjustments","Retention","Disputed","Open balance","Currently due","Matched amount","External amount","External hours","Hourly rate","Rate","Remaining hours","Known amount","Known hours","Internal cost","Gross fee","Cost not allocated to staff","Hours not allocated to staff","Shared ceiling","Actual plus remaining","Expected gross billing","Availability per day","Hours per working day","Before remaining cost","Proposed remaining cost","Available hours per day","Incurred cost","Underspend","Remaining cost","Remaining gross billing","amount","source_allocation_amount","source_allocation_hours"]);

 const tables=contractSnapshotTables(report),details:Cell[][]=[["Record ID","Field","Part","Parts","Retained text"]],detailLinks=new Map<string,number>();
 if(typedColumns){
  const handoff=tables.find(table=>table.name==="Accounting handoff");
  for(const [rowIndex,row] of (handoff?.rows??[]).entries())if(rowIndex>0)for(const [column,value] of row.entries())if(typeof value==="string"&&value.length>250){
   const parts=value.match(/[\s\S]{1,250}/g)!;detailLinks.set(`${rowIndex}:${column}`,details.length+1);
   parts.forEach((part,index)=>details.push([row[1],handoff!.rows[0][column],index+1,parts.length,part]));
  }
  if(details.length>1){tables.push({name:"Accounting text details",rows:details});tables[0].rows.push(["Long accounting text","Handoff cells retain full values. Links open all text parts in Accounting text details; parts repeat the stable record ID and field."]);}
 }
 for (const table of tables) {
  const widths = table.name==="Accounting text details" ? [42,24,8,8,100] : table.rows[0].map((_,i) => i===0 ? 36 : table.name==="Identity" ? 95 : 30);
  const isAmount=(index:number,row:Cell[])=>!typedColumns||amountHeaders.has(String(table.rows[0][index]))||(table.name==="Closeout position"&&index===1&&["Last closeout incurred cost","Last closeout underspend"].includes(String(row[0])));
  const rows = table.rows.flatMap(row => {
   const parts = row.map((v,index) => typeof v === "number" ? [v] : typeof v === "string" && isAmount(index,row) && /^-?\d+\.\d{2}$/.test(v) && Math.abs(Number(v))<1e12 ? [Number(v)] : (report.snapshot.schemaVersion??0)>=7&&table.name==="Accounting handoff"?[String(v??"Unassessed")]:String(v ?? "Unassessed").match(/[\s\S]{1,250}/g) ?? [""]);
   return Array.from({ length: Math.max(...parts.map(p=>p.length)) }, (_,i) => parts.map(p=>p[i]??""));
  });
  const sheet = utils.aoa_to_sheet(rows); sheet["!cols"] = widths.map(wch=>({wch}));
  sheet["!rows"] = rows.map(row=>({hpt:Math.min(360,Math.max(30,...row.map((v,i)=>16*(String(v).split("\n").length+Math.ceil(String(v).length/(widths[i]-3))))))}));
  for(const key of Object.keys(sheet).filter(k=>!k.startsWith("!"))) if(sheet[key].t==="n"){
   const cell=utils.decode_cell(key);sheet[key].z=isAmount(cell.c,rows[cell.r])?"#,##0.00;[Red](#,##0.00)":"0";
  }
  if(typedColumns&&table.name==="Accounting handoff")for(const [key,row] of detailLinks){const [r,c]=key.split(":").map(Number);sheet[utils.encode_cell({r,c})].l={Target:`#'Accounting text details'!A${row}`,Tooltip:"Read every retained text part for this record and field"};}
  utils.book_append_sheet(book,sheet,table.name);
 }
 return book;
}
export async function renderContractSnapshot(report: ContractSnapshot, format: "pdf"|"xlsx") {
 if (format === "xlsx") { const book=contractSnapshotWorkbook(report),zip=await JSZip.loadAsync(await writeWorkProgramWorkbook(book)); await formatWorkProgramWorkbook(zip,book,{readOnly:true}); return {bytes:Buffer.from(await zip.generateAsync({type:"uint8array",compression:"DEFLATE"})),engine:"sheetjs"}; }
 const pdf = await renderReportPdf(contractSnapshotHtml(report), {title:report.title,generatedAt:report.created_at,footerLabel:"Internal contract management"});
 return {bytes:Buffer.from(pdf.bytes),engine:pdf.engine};
}
