/**
 * THE TYPED LOOKUP a participant surface uses to get its own copy.
 *
 * Deliberately SEPARATE from `messages.ts`, and this split is load-bearing:
 * `messages.ts` holds every locale's catalog, so importing it into a client
 * component would ship all of them to a resident's phone to render one. This
 * module imports from it with `import type` only — erased before bundling — and
 * reads its strings at runtime out of the bundle the server already resolved.
 * A participant downloads their own language and nothing else.
 *
 * WHY A CATALOG AND NOT REQUEST-TIME MACHINE TRANSLATION. The chrome — the tab
 * labels, the field names, the button that submits a comment — is OpenPlan's
 * own copy. It changes rarely, it is short, and it is the part an agency is
 * least able to check. A label regenerated by a model on every request is not
 * reviewable (nobody can approve a string that will be different next time),
 * not cacheable, and not free. Operator-authored CONTENT is the opposite case
 * and is handled the opposite way — see `operator-text.ts`.
 */

import type { PortalLocale, PortalTextDirection } from "./locales";
import type { PortalMessageKey, PortalMessageSource } from "./messages";

/**
 * Everything a client surface needs to render one locale — and nothing that
 * cannot cross the server/client boundary.
 *
 * A function cannot be a prop of a client component, so `t` is NOT passed: the
 * server passes this plain object and the component calls
 * `createPortalTranslator` on it. That also keeps the two sides honest, because
 * both build their translator from the same resolved data.
 */
export type PortalMessageBundle = {
  locale: PortalLocale;
  direction: PortalTextDirection;
  bcp47: string;
  /** The language's name in its own script — legible to the person reading it. */
  nativeName: string;
  /** Every key, already resolved: this locale's string, or the English source. */
  messages: Record<PortalMessageKey, string>;
  /**
   * The keys that fell back to English because this locale does not carry them.
   *
   * NOT an internal detail. English text sitting unlabelled inside an otherwise
   * Spanish page tells a resident the agency wrote it that way, and under Title
   * VI that is a claim about what the agency published. A page holding this list
   * can say what is not translated; a page that never got it cannot.
   */
  fallbackKeys: PortalMessageKey[];
};

/**
 * The `{name}` placeholders inside one English source string, as a type.
 *
 * This is what makes an interpolation a BUILD error rather than a literal
 * "{count}" rendered to a member of the public. `t("portal.itemCount")` with no
 * values, or with the wrong value name, does not compile.
 */
type Placeholders<S extends string> = S extends `${string}{${infer Name}}${infer Rest}`
  ? Name | Placeholders<Rest>
  : never;

type ValuesFor<K extends PortalMessageKey> = Placeholders<PortalMessageSource[K]>;

/**
 * No second argument for a string with no placeholders; a required, exactly
 * typed one for a string that has them.
 */
export type PortalMessageValues<K extends PortalMessageKey> = [ValuesFor<K>] extends [never]
  ? []
  : [values: Record<ValuesFor<K>, string | number>];

export type PortalTranslator = {
  locale: PortalLocale;
  direction: PortalTextDirection;
  bcp47: string;
  nativeName: string;
  /** The participant-facing copy for one key, with `{name}` values substituted. */
  t<K extends PortalMessageKey>(key: K, ...values: PortalMessageValues<K>): string;
  /**
   * True when this key is NOT translated into the participant's language and is
   * being shown in English. A surface that renders a fallback string is
   * expected to mark it, or to rely on the page-level disclosure that
   * `hasFallbacks` drives.
   */
  isFallback(key: PortalMessageKey): boolean;
  /** True when anything on this page is falling back to English. */
  hasFallbacks: boolean;
  /** How many of the catalog's keys this locale actually carries. */
  translatedKeyCount: number;
  totalKeyCount: number;
};

function interpolate(template: string, values: Record<string, string | number> | undefined): string {
  if (!values) return template;
  // Replaces only names that were supplied. An unknown `{token}` is left
  // verbatim rather than blanked, because a visible defect is findable and a
  // silently emptied sentence is not.
  return template.replace(/\{([a-zA-Z0-9_]+)\}/g, (match, name: string) =>
    Object.prototype.hasOwnProperty.call(values, name) ? String(values[name]) : match
  );
}

/**
 * Build the lookup for one already-resolved bundle. Safe on both sides of the
 * server/client boundary, and free of any catalog import at runtime.
 */
export function createPortalTranslator(bundle: PortalMessageBundle): PortalTranslator {
  const fallback = new Set<PortalMessageKey>(bundle.fallbackKeys);
  const total = Object.keys(bundle.messages).length;

  return {
    locale: bundle.locale,
    direction: bundle.direction,
    bcp47: bundle.bcp47,
    nativeName: bundle.nativeName,
    t: <K extends PortalMessageKey>(key: K, ...values: PortalMessageValues<K>): string =>
      interpolate(bundle.messages[key], values[0] as Record<string, string | number> | undefined),
    isFallback: (key) => fallback.has(key),
    hasFallbacks: fallback.size > 0,
    translatedKeyCount: total - fallback.size,
    totalKeyCount: total,
  };
}
