/** Build a reproducible public-source engineering fixture from independently transcribed PDF tables.
 * Run only against an explicitly named local exercise program; never an agency record.
 * OWP_REFERENCE_DIR contains financial-reference.json, staffing-reference.json and source-inventory.json.
 */
import {readFileSync,writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {randomUUID} from 'node:crypto';
import {createServiceRoleClient} from '../../src/lib/supabase/server';
import {loadWorkProgramSources} from '../../src/lib/programs/work-program/server';
import {workProgramDraftSchema,type WorkProgramDraft,type WorkProgramStructuredPreparation} from '../../src/lib/programs/work-program/schema';
import {emptyStructuredPreparation} from '../../src/lib/programs/work-program/reconciliation';
import {proposeSourceElement,validateWorkProgramSources,workProgramCoverage} from '../../src/lib/programs/work-program/source-review';
import {reconcileStructuredWorkProgram} from '../../src/lib/programs/work-program/reconciliation';
import type {WorkProgramSource} from '../../src/lib/programs/work-program/types';
type Printed={source_text:string;state:'amount'|'blank'|'dash';amount_cents:number|null};
type Table={pdf_page:number;columns:string[];rows:{work_element:string;title:string;values:Record<string,Printed>}[];printed_totals:Record<string,Printed>;separate_fixed_asset_line?:{label:string;amount_cents:number;treatment:string}};
type Financial={documents:Record<'prior'|'current',{sha256:string;fiscal_year:string;tables:Record<string,Table>}>};
type Staffing={documents:Record<'prior'|'current',{pdf_page:number;staffing_statement_pdf_page:number;stated_full_time_positions:number;position_titles_in_statement:string[];salary_ranges:Record<string,Record<string,{step:number;source_text:string;amount_cents:number}[]>>;work_element_person_months:{work_element:string;source_value:string;pdf_page:number}[]}>};
type Inventory={documents:Record<'prior'|'current',{material_sections:{title:string;pdf_pages:number[];source_page_text:{pdf_page:number;text:string}[]}[];work_elements:{work_element:string;pdf_pages:number[];source_page_text:{pdf_page:number;text:string}[]}[]}>};
async function main(){
 const dir=process.env.OWP_REFERENCE_DIR,programId=process.env.OWP_REFERENCE_PROGRAM,output=process.env.OWP_REFERENCE_OUTPUT;
 if(!dir||!programId||!output) throw new Error('Explicit reference input directory, local program and output path are required');
 const origin=new URL(process.env.NEXT_PUBLIC_SUPABASE_URL!);
 if(!['localhost','127.0.0.1'].includes(origin.hostname)||origin.port!=='56321')throw new Error('Reference exercise requires its isolated local stack on 56321');
 const financial=JSON.parse(readFileSync(join(dir,'financial-reference.json'),'utf8')) as Financial;
 const staffing=JSON.parse(readFileSync(join(dir,'staffing-reference.json'),'utf8')) as Staffing;
 const inventory=JSON.parse(readFileSync(join(dir,'source-inventory.json'),'utf8')) as Inventory;
 const service=createServiceRoleClient();
 const program=await service.from('programs').select('id,workspace_id,title').eq('id',programId).single();
 if(program.error||!program.data.title.includes('engineering exercise'))throw new Error('The named program is not the engineering exercise');
 const sources=await loadWorkProgramSources(service,programId);
 const choose=(kind:'prior'|'current')=>{const source=sources.find(s=>s.document_checksum===financial.documents[kind].sha256);if(!source)throw new Error(`Missing retained ${kind} original`);const version=source.versions?.at(-1);return version?{...source,selectedVersionId:version.id,extraction_json:version.extraction_json}:source;};
 const prior=choose('prior'),current=choose('current'),p=emptyStructuredPreparation();
 const ref=(s:WorkProgramSource,pageFrom:number,pageTo=pageFrom,tableLabel='Original program passage')=>({sourceId:s.id,extractionVersionId:s.selectedVersionId??null,elementKey:null,pageFrom,pageTo,tableLabel});
 const row=(sourceRefs:WorkProgramStructuredPreparation["funds"][number]["sourceRefs"] =[])=>({id:randomUUID(),sourceRefs});
 const d:WorkProgramDraft={schemaVersion:1,documentKind:'owp',agency:'El Dorado County Transportation Commission — engineering reference proposal',responsibleAuthority:'EDCTC Commission (referenced authority only)',authorityBasis:'Public FY2025/26 Amendment 2 and FY2026/27 Final are reference evidence. This reconstruction grants no authority and records no new adoption.',periodStart:'2026-07-01',periodEnd:'2027-06-30',introduction:'Engineering preparation exercise: reconstruct a next-cycle proposal using the published FY2026/27 final as a comparison benchmark and the FY2025/26 amended predecessor. It is editable preparation, not an agency-approved OWP or a submission. Later amendments are distinct sources and have not been inferred into this revision.',staffing:'The current source states five full-time positions. Published work-element person-month quantities and salary classification ranges are retained separately. The source does not assign hours or a cost rate to each named employee. No salary step, productive-hours basis or FTE conversion is inferred.',financialNotes:'Current exact-cent summary-table figures form the proposed benchmark allocations and expenditures. Prior figures are prior published authority, not available balances. Blank and dash reference cells remain distinct nulls; only printed amounts become proposed rows. The summaries total $1,649,870.12 for the 13 current direct work elements. WE50 describes the indirect pool allocated among these elements, so it is not added again. Missing predecessor elements 200EIR and 263 remain unresolved and keep whole-program completion open. The prior salary-column printed total differs from its rows by one cent; this conflict is retained. Work-element budget text uses whole dollars while the summary uses cents; both original precisions are retained.',currency:'USD',priorBalance:null,priorBalanceBasis:'The retained budgets do not establish actual expenditures, encumbrances or unspent available balances. Obtain dated fund balances and restrictions before treating carryover as available authority.',elements:[],preparation:p};
 p.extractionSelections=[prior,current].map(s=>({sourceId:s.id,versionId:s.selectedVersionId??null}));
 for(const sourceElement of current.extraction_json.elements){
  const element=proposeSourceElement(current,sourceElement),old=prior.extraction_json.elements.find(e=>e.code===element.code);
  element.disposition=old?'changed':'unresolved';
  element.decisionNote=old?'Mapped by explicit matching code and subject in both retained programs. The proposed narrative uses the current final benchmark; prior text is retained for comparison. This does not declare previous activities complete.':'No predecessor match established; new-work decision remains unresolved.';
  element.budgetTreatment=element.code==='50'?'informational':'included';element.budgetTreatmentNote=element.code==='50'?'Indirect pool is allocated once through the 13 direct elements; its separate narrative budget is not an additional cost.':'Use exact-cent current summary-table amounts; retain whole-dollar narrative tables at original precision.';
  const months=staffing.documents.current.work_element_person_months.find(x=>x.work_element===element.code);element.personMonths=months?Number(months.source_value):null;
  element.sourceRefs=old?[{sourceId:prior.id,extractionVersionId:prior.selectedVersionId??null,elementKey:old.key,pageFrom:old.pageFrom,pageTo:old.pageTo,tableLabel:'Predecessor work element'}]:[];
  for(const activity of [...element.tasks,...element.products])activity.sourceRefs=element.source?[element.source]:[];
  d.elements.push(element);p.mappings.push({...row([...(element.source?[element.source]:[]),...element.sourceRefs]),disposition:element.disposition,targetIds:[element.id],note:element.decisionNote});
 }
 for(const old of prior.extraction_json.elements.filter(e=>!current.extraction_json.elements.some(n=>n.code===e.code))){const element=proposeSourceElement(prior,old);element.decisionNote='Not found in the retained current final. Missing evidence of completion, closeout, transfer or continuing authority; absence does not establish completion.';element.budgetTreatmentNote='No supported next-cycle amount. Prior authority is retained only in reference figures.';d.elements.push(element);p.mappings.push({...row(element.source?[element.source]:[]),disposition:'unresolved',targetIds:[element.id],note:element.decisionNote});}
 const elementId=(code:string)=>{const e=d.elements.find(x=>x.code===code);if(!e)throw new Error(`Unmapped source budget ${code}`);return e.id;};
 const reference=(source:WorkProgramSource,table:string,rowName:string,column:string,unit:string,cell:Printed,page:number,note='Reference transcription; excluded from proposed totals')=>p.referenceFigures!.push({...row([ref(source,page,page,table)]),table,row:rowName,column,unit,value:cell.amount_cents===null?null:cell.amount_cents/100,sourceText:cell.source_text,state:cell.state,note});
 for(const kind of ['prior','current'] as const){const s=kind==='prior'?prior:current,doc=financial.documents[kind];
  for(const [tableName,table] of Object.entries(doc.tables)){
   const name=`${doc.fiscal_year} ${tableName}`;
   for(const entry of table.rows)for(const column of table.columns)reference(s,name,`${entry.work_element} ${entry.title}`,column,'USD',entry.values[column],table.pdf_page);
   for(const [column,cell] of Object.entries(table.printed_totals))reference(s,name,'Printed TOTAL',column,'USD',cell,table.pdf_page);
   if(table.separate_fixed_asset_line){const x=table.separate_fixed_asset_line;reference(s,`${doc.fiscal_year} separate fixed assets`,x.label,'separate amount','USD',{source_text:(x.amount_cents/100).toFixed(2),amount_cents:x.amount_cents,state:'amount'},table.pdf_page,x.treatment);p.conflicts.push({...row([ref(s,table.pdf_page)]),description:`${doc.fiscal_year}: ${x.label} is printed separately below the operating total.`,status:'unresolved',resolution:x.treatment+' Evidence of its funding and relationship to the operating total is needed before adding it.'});}
   if(tableName.startsWith('revenue'))for(const column of table.columns.filter(x=>x!=='total')){
    const cell=table.printed_totals[column],fund={...row([ref(s,table.pdf_page,table.pdf_page,name)]),name:column.replaceAll('_',' '),vintage:doc.fiscal_year,periodStart:kind==='prior'?'2025-07-01':d.periodStart,periodEnd:kind==='prior'?'2026-06-30':d.periodEnd,kind:kind==='prior'?'prior_authority':column.includes('carryover')?'carryover':'proposed',basis:kind==='prior'?'reference':'proposed',amount:cell.amount_cents===null?null:cell.amount_cents/100,note:kind==='prior'?'Published prior authority only; not an available balance.':column.includes('anticipated')?'Anticipated carryover as proposed in the final source; actual balance remains unresolved.':'Proposed engineering benchmark from the final source; no new spending authority.'} as WorkProgramStructuredPreparation['funds'][number];p.funds.push(fund);
    if(kind==='current')for(const entry of table.rows){const amount=entry.values[column].amount_cents;if(amount!==null)p.allocations.push({...row([ref(s,table.pdf_page,table.pdf_page,`${name}: ${entry.work_element}, ${column}`)]),elementId:elementId(entry.work_element),taskId:null,fundId:fund.id,amount:amount/100,matchForFundId:null,note:'Exact printed summary amount. No grant-match relationship inferred.'});}
   }
  }
  const staff=staffing.documents[kind];
  for(const [role,rates] of Object.entries(staff.salary_ranges))for(const [unit,steps] of Object.entries(rates))for(const step of steps)reference(s,`${doc.fiscal_year} salary schedule: ${unit}`,role,`Step ${step.step}`,`USD/${unit}`,{source_text:step.source_text,amount_cents:step.amount_cents,state:'amount'},staff.pdf_page,'Classification range reference, not a selected employee labor-cost rate or billing rate.');
  reference(s,`${doc.fiscal_year} staffing statement`,'Full-time positions','Count','positions',{source_text:String(staff.stated_full_time_positions),amount_cents:staff.stated_full_time_positions*100,state:'amount'},staff.staffing_statement_pdf_page,staff.position_titles_in_statement.join('; '));
  for(const item of staff.work_element_person_months){reference(s,`${doc.fiscal_year} work-element staffing`,item.work_element,'Printed person-months','person-months',{source_text:item.source_value,amount_cents:Number(item.source_value)*100,state:'amount'},item.pdf_page,'Printed source quantity. No hours or FTE conversion inferred.');if(kind==='current')p.staffing.push({...row([ref(s,item.pdf_page,item.pdf_page,`WE ${item.work_element} staffing schedule`)]),elementId:elementId(item.work_element),taskId:null,staffId:null,role:`Unassigned EDCTC staff, WE ${item.work_element}`,periodStart:d.periodStart,periodEnd:d.periodEnd,quantity:Number(item.source_value),unit:'person_months',capacityHours:null,hoursPerUnit:null,capacityBasis:'',costTreatment:'capacity_only',rate:null,rateBasis:'unresolved',rateStart:d.periodStart,rateEnd:d.periodEnd,rateNote:'Actual employee allocation, hours conversion and cost rate are not specified by the retained schedule.',includesIndirect:false});}
  for(const section of inventory.documents[kind].material_sections){const pages=section.pdf_pages, isTable=/budget|salary|staffing/.test(section.title), proposedText=kind==='current' && /introduction|location and organization|state planning|appendix F/.test(section.title) ? section.source_page_text.map(page=>page.text).join('\n') : ''; p.sourceSections.push({...row(pages.map(page=>ref(s,page,page,section.title))),title:`${doc.fiscal_year}: ${section.title}`,proposedText,retainPageImages:kind==='current' && /study area map|staffing, duties|federal planning|state planning|planning flowchart/.test(section.title),retainedText:/revenue budget|expenditure budget|work element detail/.test(section.title)?section.source_page_text.map(page=>page.text).join("\n"):"",status:isTable||proposedText?'incorporated':'reference_only',note:isTable?'Retained original passage and applicable numeric tables are transcribed at printed precision; unsupported actuals and personal cost assignments remain unresolved.':`Retained as ${kind==='prior'?'predecessor':'current benchmark'} context. This exercise does not adopt, sign or renew the source statements, certifications, maps, goals or third-party commitments.`});}
  const covered=new Set([...inventory.documents[kind].material_sections.flatMap(x=>x.pdf_pages),...s.extraction_json.elements.flatMap(x=>Array.from({length:x.pageTo-x.pageFrom+1},(_,i)=>x.pageFrom+i))]);
  for(let page=1;page<=s.page_count;page++)if(!covered.has(page))p.sourceSections.push({...row([ref(s,page)]),title:`${doc.fiscal_year}: remaining PDF page ${page}`,status:'reference_only',note:'Section divider page, checked directly with pdftotext against the retained original; its heading separates program sections and carries no additional allocation.'});
 }
 const expenses=financial.documents.current.tables.expenditures,poolId=randomUUID();p.indirectPools.push({id:poolId,sourceRefs:[ref(current,expenses.pdf_page)],name:'FY2026/27 indirect allocation pool',amount:expenses.printed_totals.indirect.amount_cents!/100,note:'Exact summary pool allocated across direct work elements; WE50 whole-dollar narrative is a rounded description, not another allocation.'});
 for(const entry of expenses.rows)for(const column of expenses.columns.filter(x=>x!=='total')){const cell=entry.values[column];if(cell.amount_cents!==null)p.costs.push({...row([ref(current,expenses.pdf_page,expenses.pdf_page,`Expenditures: ${entry.work_element}, ${column}`)]),elementId:elementId(entry.work_element),taskId:null,label:column.replaceAll('_',' '),category:column==='indirect'?'indirect':column==='salaries_benefits'?'labor_summary':column==='professional_services'?'consultant':'direct',amount:cell.amount_cents/100,contractId:null,indirectPoolId:column==='indirect'?poolId:null,note:'Exact printed current budget amount; no actual expenditure or executed contract inferred.'});}
 p.amendments.push({...row([ref(prior,1),ref(current,1)]),amendmentSourceId:prior.id,modifiesSourceId:current.id,status:'separate_cycle',note:'The FY2025/26 Amendment 2 is the cumulative predecessor; it does not modify the FY2026/27 final. Amendment 1 and the original prior final are named on the cover but not separately retained here; their exact changes and intervening precedence remain unresolved.'});
 p.conflicts.push({...row([ref(prior,54)]),description:'Prior salary/benefit rows total $661,434.49; printed column total is $661,434.50.',status:'unresolved',resolution:'Preserve the one-cent discrepancy. Obtain corrected source or agency explanation; no balancing adjustment has been fabricated.'});
 p.conflicts.push({...row([ref(prior,1)]),description:'Separate original FY2025/26 final and Amendment 1 are not retained.',status:'unresolved',resolution:'The retained Amendment 2 documents the cumulative predecessor. Separate amendments are needed to reconstruct each intervening change; document dates alone do not decide precedence.'});
 const parsed=workProgramDraftSchema.safeParse(d);if(!parsed.success)throw new Error(JSON.stringify(parsed.error.issues));const error=validateWorkProgramSources(parsed.data,sources);if(error)throw new Error(error);
 const result={draft:parsed.data,reconciliation:reconcileStructuredWorkProgram(parsed.data),coverage:workProgramCoverage(parsed.data,sources)};
 writeFileSync(output,JSON.stringify(result,null,2));console.log(JSON.stringify({output,elements:d.elements.length,referenceFigures:p.referenceFigures?.length,funds:p.funds.length,allocations:p.allocations.length,costs:p.costs.length,staffing:p.staffing.length,knownRevenue:result.reconciliation.knownRevenue,knownCost:result.reconciliation.knownCost,issues:result.reconciliation.issues.length}));
}
main().catch(error=>{console.error(error instanceof Error?error.message:'Reference construction failed');process.exitCode=1;});
