import * as XLSX from "xlsx";
import type { WorkProgramRevision, WorkProgramSource } from "./types";
import { reconcileStructuredWorkProgram } from "./reconciliation";
import { selectWorkProgramSources, workProgramCoverage } from "./source-review";

const esc = (value: unknown) => String(value ?? "Unresolved").replace(/\uf0b7/g, "•").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[c]!);
const paragraph = (value: unknown) => `<p>${esc(value).replaceAll("\n", "<br>")}</p>`;
const table = (headings: string[], rows: unknown[][]) => `<table><thead><tr>${headings.map((value) => `<th>${esc(value)}</th>`).join("")}</tr></thead><tbody>${rows.map((row) => `<tr>${row.map((value) => `<td>${esc(value).replaceAll("\n", "<br>")}</td>`).join("")}</tr>`).join("")}</tbody></table>`;
const notice = "Engineering preparation proposal using retained sources. No agency approval, adoption, spending authorization or submission is established. Blank or unsupported figures remain unresolved.";

export function buildStructuredWorkProgramHtml(revision: WorkProgramRevision, originals: WorkProgramSource[], pageImages: import("./types").WorkProgramPageImage[] = []) {
  const d = revision.content_json, p = d.preparation!, r = reconcileStructuredWorkProgram(d);
  const sources = selectWorkProgramSources(d, originals);
  const sourceNames = new Map(sources.map((source) => [source.id, source.title]));
  const refs = (rows: { sourceId: string; pageFrom: number; pageTo: number; tableLabel: string; extractionVersionId?: string | null; purpose?: string }[]) => rows.map((ref) => `${sourceNames.get(ref.sourceId) ?? ref.sourceId}, PDF ${ref.pageFrom}-${ref.pageTo}, ${ref.tableLabel}${ref.purpose ? `; ${ref.purpose}` : ""}; extraction ${ref.extractionVersionId ?? "original attachment"}`).join("\n");
  const fundName = (id: string) => { const row = p.funds.find((row) => row.id === id); return row ? `${row.name} / ${row.vintage}` : "Unresolved funding source"; };
  const workName = (id: string) => d.elements.find((row) => row.id === id)?.code ?? "Unresolved work element";
  const money = (value: number | null) => value === null ? "Unresolved" : value.toFixed(2);
  const referenceTables = [...new Set((p.referenceFigures ?? []).map((row) => row.table))].map((name) => {
    const cells = (p.referenceFigures ?? []).filter((row) => row.table === name);
    const columns = [...new Set(cells.map((row) => row.column))];
    const rows = [...new Set(cells.map((row) => row.row))];
    return `<h3>${esc(name)}</h3>${paragraph([...new Set(cells.map((row) => row.unit))].join(", "))}${table(["Source row", ...columns], rows.map((name) => [name, ...columns.map((column) => { const cell = cells.find((row) => row.row === name && row.column === column); return !cell ? "Not present" : cell.state === "amount" ? cell.sourceText : cell.state === "blank" ? "Blank in source" : cell.state === "dash" ? "Dash in source" : "Unavailable"; })]))}${paragraph(refs(cells[0]?.sourceRefs ?? []))}`;
  }).join("");
  const sections = [
    `<h1>${esc(d.agency)}</h1><h2>${esc(d.documentKind.toUpperCase())} preparation proposal</h2>${paragraph(`${d.periodStart} to ${d.periodEnd} · revision ${revision.revision} · ${d.currency}`)}<p class="notice">${notice}</p>`,
    `<h2>Program narrative</h2>${paragraph(d.introduction)}<h3>Responsible authority</h3>${paragraph(d.responsibleAuthority)}${paragraph(d.authorityBasis)}<h3>Staffing and organization</h3>${paragraph(d.staffing)}<h3>Financial assumptions</h3>${paragraph(d.financialNotes)}`,
    ...p.sourceSections.filter((row) => row.proposedText?.trim()).map((row) => `<section><h2>${esc(row.title)}</h2>${paragraph(row.proposedText)}${paragraph(refs(row.sourceRefs))}</section>`),
    `<h2>Reconciliation</h2>${table([`Measure (${d.currency})`, "Amount"], [["Known work-element funding subtotal", money(r.knownRevenue)], ["Known work-element expenditure subtotal", money(r.knownCost)], ["Proposed funding allocated to work", money(r.revenue)], ["Proposed expenditure including calculated labor", money(r.cost)], ["Funding less expenditure", money(r.difference)], ["Prior balance, reference only", money(d.priorBalance)]])}${paragraph(d.priorBalanceBasis)}`,
    `<h2>Funding sources and vintages</h2>${table(["Source / vintage", "Meaning / basis", `Amount (${d.currency})`, "Effective period", "Source / assumptions"], p.funds.map((row) => [`${row.name}\n${row.vintage}`, `${row.kind}\n${row.basis}`, money(row.amount), `${row.periodStart}\n${row.periodEnd}`, `${refs(row.sourceRefs)}\n${row.note}`]))}`,
    `<h2>Funding reconciliation</h2>${table(["Source / vintage", "Available", "Allocated", "Remaining", "Required match", "Proposed match", "Match difference"], r.byFund.map((row) => [`${row.name}\n${row.vintage}`, money(row.available), money(row.allocated), money(row.remainder), money(row.requiredMatch), money(row.providedMatch), money(row.matchDifference)]))}`,
    `<h2>Indirect-cost pools</h2>${paragraph("Pool totals describe the costs distributed through work-element expenditure rows. They are not added to program costs a second time.")}${table(["Pool", `Amount (${d.currency})`, "Source / allocation basis"], p.indirectPools.map((row) => [row.name, money(row.amount), `${refs(row.sourceRefs)}\n${row.note}`]))}`,
    ...d.elements.map((element) => {
      const total = r.byElement.find((row) => row.id === element.id);
      return `<section class="element"><h2>${esc(element.code)} ${esc(element.title)}</h2>${paragraph(`${element.disposition}: ${element.decisionNote || "Decision unresolved"}`)}${paragraph(`Budget treatment: ${element.budgetTreatment}. ${element.budgetTreatmentNote}`)}${paragraph(refs([...(element.source ? [element.source] : []), ...(element.sourceRefs ?? [])]))}<h3>Objective</h3>${paragraph(element.objective)}<h3>Discussion</h3>${paragraph(element.discussion)}<h3>Responsibility and schedule</h3>${paragraph(`${element.responsible}\n${element.schedule}\nSource/proposed person-months: ${element.personMonths ?? "unresolved"}`)}${(["tasks", "products"] as const).map((kind) => `<h3>${kind === "tasks" ? "Tasks" : "Products"}</h3>${element[kind].map((row, index) => `<h4>${index + 1}</h4>${paragraph(row.description)}${paragraph(`${row.responsible}\n${row.schedule}`)}${paragraph(refs(row.sourceRefs ?? []))}`).join("")}`).join("")}<h3>Proposed allocations</h3>${table(["Funding source / vintage", `Amount (${d.currency})`, "Match / source"], p.allocations.filter((row) => row.elementId === element.id).map((row) => [fundName(row.fundId), money(row.amount), `${row.matchForFundId ? `Match for ${fundName(row.matchForFundId)}\n` : ""}${refs(row.sourceRefs)}\n${row.note}`]))}<h3>Proposed expenditures</h3>${table(["Category", `Amount (${d.currency})`, "Contract / pool / source"], p.costs.filter((row) => row.elementId === element.id).map((row) => [`${row.label}\n${row.category}`, money(row.amount), `${row.contractId ?? ""}\n${row.indirectPoolId ?? ""}\n${refs(row.sourceRefs)}\n${row.note}`]))}${paragraph(total ? `Funding ${money(total.revenue)}; expenditure ${money(total.cost)}; difference ${money(total.difference)} ${d.currency}.` : "This element is outside proposed program totals.")}</section>`;
    }),
    `<h2>Staff allocations</h2>${table(["Person / role / work", "Period / quantity", "Hours / cost", "Cost and capacity assumptions"], p.staffing.map((row) => { const value = r.staff.find((item) => item.id === row.id)!; return [`${row.staffId ?? row.role}\nWE ${workName(row.elementId)}`, `${row.periodStart} to ${row.periodEnd}\n${row.quantity ?? "Unresolved"} ${row.unit}`, `${value.hours ?? "Unresolved"} hours\n${row.costTreatment === "capacity_only" ? "Capacity only; see expenditure table" : `${money(value.cost)} ${d.currency}`}`, `Available period hours ${row.capacityHours ?? "unresolved"}; hours per ${row.unit}: ${row.hoursPerUnit ?? "unresolved"}. Basis: ${row.capacityBasis}\nRate ${row.rate ?? "unresolved"} ${d.currency}/hour, ${row.rateBasis}, ${row.rateStart} to ${row.rateEnd}; ${row.rateNote}\n${refs(row.sourceRefs)}`]; }))}`,
    `<h2>Predecessor and proposed work comparison</h2>${table(["Source work", "Decision / proposed work", "Explanation"], p.mappings.map((row) => [refs(row.sourceRefs), `${row.disposition}\n${row.targetIds.map(workName).join(", ")}`, row.note]))}`,
    `<h2>Amendment decisions</h2>${table(["Amendment / modified source", "Decision", "Explanation / passages"], p.amendments.map((row) => [`${sourceNames.get(row.amendmentSourceId)}\n${sourceNames.get(row.modifiesSourceId)}`, row.status, `${row.note}\n${refs(row.sourceRefs)}`]))}`,
    `<h2>Material source sections</h2>${table(["Section", "Treatment", "Explanation / passages"], p.sourceSections.map((row) => [row.title, row.status, `${row.note}\n${refs(row.sourceRefs)}`]))}`,
    `<h2>Source conflicts</h2>${table(["Conflict", "Status / resolution", "Passages"], p.conflicts.map((row) => [row.description, `${row.status}\n${row.resolution}`, refs(row.sourceRefs)]))}`,
    `<h2>Unresolved items and discrepancies</h2>${table(["Finding", "Contributing row identifiers"], r.issues.map((issue) => [issue.message, issue.rowIds.join("\n")]))}${workProgramCoverage(d, originals).map((row) => paragraph(`${row.title}: unmatched work elements ${row.unmappedElements.map((element) => element.code).join(", ") || "none"}; uncovered PDF pages ${row.uncoveredPages.join(", ") || "none"}; amendment relationship ${row.amendmentUnresolved ? "unresolved" : "no unresolved relationship detected"}.`)).join("")}`,
    `<h2>Source financial and staffing tables</h2>${paragraph("Reference cells preserve printed values and blank/dash states. These are excluded from proposed totals.")}${referenceTables}`,
    `<h2>Original work-element budget passages</h2>${paragraph("These retained source passages preserve original whole-dollar figures and descriptions. They are reference evidence and are not added to the proposed allocations a second time.")}${sources.map((source) => `<h3>${esc(source.title)}</h3>${source.extraction_json.elements.map((element) => `<h4>WE ${esc(element.code)} · PDF ${element.pageFrom}–${element.pageTo}</h4><pre class="source-budget">${esc(element.budgetText)}</pre>`).join("")}`).join("")}`,
    ...p.sourceSections.filter((row) => row.retainedText?.trim()).map((row) => `<h3>Original passage: ${esc(row.title)}</h3><pre class="source-budget">${esc(row.retainedText)}</pre>${paragraph(refs(row.sourceRefs))}`),
    ...pageImages.map((item) => `<section class="source-image"><h2>Original reference page</h2>${paragraph(`${sourceNames.get(item.sourceId)} · PDF page ${item.page}. Reference evidence; no new adoption or certification.`)}<img src="${item.dataUrl}" alt="Original PDF page ${item.page} from ${esc(sourceNames.get(item.sourceId))}; retained to preserve chart and table relationships"/>${paragraph(`Rendered page SHA-256 ${item.checksum}`)}</section>`),
    `<h2>Source register</h2>${sources.map((source) => `<h3>${esc(source.title)}</h3>${paragraph(`${source.source_role}; ${source.page_count} PDF pages; source ${source.id}\nOriginal SHA-256 ${source.document_checksum}\nExtraction ${source.selectedVersionId ?? "original attachment"}\n${source.source_url ?? "Official URL not recorded"}`)}`).join("")}`,
    `<h2>Revision identity</h2>${paragraph(`Revision ${revision.revision}, ${revision.id}\nContent SHA-256 ${revision.content_sha256}\nSaved ${revision.created_at}\nThe HTML, PDF and XLSX use this same immutable revision and reconciliation. External workbook edits do not change the saved proposal.`)}`,
  ];
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${esc(d.agency)} preparation</title><style>body{font:11pt/1.45 Arial,sans-serif;color:#17323e;max-width:1050px;margin:auto;padding:24px}h1{font-size:25pt}h2{font-size:17pt;border-bottom:2px solid #2b6574;padding-bottom:5px;margin-top:28px}h3{font-size:12pt}h1,h2,h3,h4{break-after:avoid}p,th,td{overflow-wrap:anywhere}.source-budget{white-space:pre-wrap;overflow-wrap:anywhere;font:9pt/1.4 "DejaVu Sans",sans-serif}table{border-collapse:collapse;width:100%;table-layout:fixed;font-size:9pt;margin:12px 0}th,td{padding:6px;border:1px solid #b7c6cd;text-align:left;vertical-align:top}th{background:#e8f1f3}thead{display:table-header-group}.source-image{break-before:page}.source-image img{display:block;max-width:100%;max-height:8in;object-fit:contain}.notice{border:2px solid #2b6574;padding:12px}@media print{body{padding:0;font-size:10pt}.element{break-before:page}tr{break-inside:avoid}}@media(max-width:500px){body{padding:12px}table{font-size:8pt}th,td{padding:3px}}</style></head><body>${sections.join("")}</body></html>`;
}

type Cell = string | number | boolean | null;
export function buildStructuredWorkProgramWorkbook(revision: WorkProgramRevision, originals: WorkProgramSource[]) {
  const d = revision.content_json, p = d.preparation!, r = reconcileStructuredWorkProgram(d), sources = selectWorkProgramSources(d, originals);
  const book = XLSX.utils.book_new();
  function sheet(name: string, headings: string[], rows: Cell[][], widths?: number[]) {
    const value = XLSX.utils.aoa_to_sheet([headings, ...rows]);
    value["!cols"] = headings.map((_, index) => ({ wch: widths?.[index] ?? 24 }));
    value["!autofilter"] = { ref: value["!ref"]! };
    XLSX.utils.book_append_sheet(book, value, name);
    return value;
  }
  const formula = (sheet: XLSX.WorkSheet, cell: string, f: string, value: Cell) => { sheet[cell] = { t: typeof value === "number" ? "n" : "s", v: value === null ? "Unresolved" : String(value), f }; if (typeof value === "number") sheet[cell].v = value; };
  sheet("Read me", ["Topic", "Meaning"], [["Proposal", notice], ["Revision", revision.revision], ["Content SHA-256", revision.content_sha256], ["Currency", d.currency], ["Editable cells", "Blue cells on pale blue are editable inputs. Dark cells contain formulas, reference evidence or identifiers. Sheets protect those cells without a password; preserve them when reviewing. Row-level unit and period columns define every numeric input."], ["Recalculation", "Existing numeric rows recalculate totals, funding gaps and row checks. Unresolved items records the source/review findings at export. Re-export after changing source decisions or adding/removing/reordering rows."], ["External edits", "Edits in this workbook do not change the saved proposal or its hash. Unrestricted spreadsheet re-import is outside this workflow."], ["Unknown values", "Blank numeric inputs are unknown. A formula displays Unresolved when a required input is missing. Reference authority/balances are not proposed funding."], ["Units", "Amounts are currency units, not thousands. Staffing quantity units and capacity basis are explicit; no FTE conversion is inferred."]], [30, 110]);
  sheet("Program narrative", ["Section", "Content"], [["Agency", d.agency], ["Period starts", d.periodStart], ["Period ends", d.periodEnd], ["Responsible authority", d.responsibleAuthority], ["Authority basis", d.authorityBasis], ["Introduction", d.introduction], ["Staffing", d.staffing], ["Financial notes", d.financialNotes], ["Prior balance, reference only", d.priorBalance], ["Prior balance basis", d.priorBalanceBasis]], [32, 100]);
  const elements = sheet("Work elements", ["Element ID", "Code", "Title", "Disposition", "Budget treatment", "Decision explanation", "Objective", "Discussion", "Schedule", "Active in totals", "Project ID", "Source person-months", "Responsible"], d.elements.map((row) => [row.id, row.code, row.title, row.disposition, row.budgetTreatment, row.decisionNote, row.objective, row.discussion, row.schedule, row.disposition !== "completed" && row.budgetTreatment !== "informational" ? 1 : 0, row.projectId, row.personMonths, row.responsible]), [38, 14, 45, 20, 20, 70, 80, 80, 45, 18, 38, 20]);
  sheet("Tasks and products", ["Row ID", "Element ID", "Kind", "Description", "Responsible", "Schedule"], d.elements.flatMap((element) => (["tasks", "products"] as const).flatMap((kind) => element[kind].map((row) => [row.id, element.id, kind, row.description, row.responsible, row.schedule]))), [38, 38, 15, 100, 40, 40]);
  const funds = sheet("Funding sources", ["Fund ID", "Name", "Vintage", "Kind", "Basis", `Amount (${d.currency})`, "Effective from", "Effective through", "Source assumptions", "Match basis", "Match value (amount or percent)", "Match applicability note", "Source passage count"], p.funds.map((row) => [row.id, row.name, row.vintage, row.kind, row.basis, row.amount, row.periodStart, row.periodEnd, row.note, row.matchBasis ?? "unresolved", row.matchValue ?? null, row.matchNote ?? "", row.sourceRefs.length]), [38, 38, 28, 24, 22, 22, 18, 18, 80]);
  const allocations = sheet("Allocations", ["Row ID", "Element ID", "Task ID", "Fund ID", `Amount (${d.currency})`, "Match for fund ID", "Note", "Active", "Eligible proposal fund", "Included amount", "Duplicate count"], p.allocations.map((row) => [row.id, row.elementId, row.taskId, row.fundId, row.amount, row.matchForFundId, row.note, null, null, null, null]), [38, 38, 38, 38, 22, 38, 70, 14, 25, 22, 20]);
  const costs = sheet("Expenditures", ["Row ID", "Element ID", "Task ID", "Treatment", "Category", `Amount (${d.currency})`, "Contract ID", "Indirect pool ID", "Note", "Active", "Included amount"], p.costs.map((row) => [row.id, row.elementId, row.taskId, row.category, row.label, row.amount, row.contractId, row.indirectPoolId, row.note, null, null]), [38, 38, 38, 22, 35, 22, 38, 38, 80, 14, 22]);
  const staffing = sheet("Staffing", ["Row ID", "Element ID", "Task ID", "Staff ID", "Unfilled role", "Period starts", "Period ends", "Quantity", "Unit", "Capacity hours", "Capacity basis", "Cost treatment", `Rate (${d.currency}/hour)`, "Rate basis", "Rate starts", "Rate ends", "Includes indirect", "Rate source note", "Calculated hours", "Calculated cost", "Active", "Source passage count", "Capacity check", "Hours per FTE or person-month", "Capacity identity"], p.staffing.map((row) => [row.id, row.elementId, row.taskId, row.staffId, row.role, row.periodStart, row.periodEnd, row.quantity, row.unit, row.capacityHours, row.capacityBasis, row.costTreatment, row.rate, row.rateBasis, row.rateStart, row.rateEnd, row.includesIndirect ? "yes" : "no", row.rateNote, null, null, null, row.sourceRefs.length, null, row.hoursPerUnit ?? null, null]), [38, 38, 38, 38, 45, 18, 18, 18, 20, 20, 80, 24, 24, 22, 18, 18, 22, 80, 22, 22, 14, 22, 28]);
  const pools = sheet("Indirect pools", ["Pool ID", "Name", `Pool amount (${d.currency})`, "Allocated", "Difference", "Source note"], p.indirectPools.map((row) => [row.id, row.name, row.amount, null, null, row.note]), [38, 40, 22, 22, 22, 80]);
  const elementTotals = sheet("Element totals", ["Element ID", "Code", "Revenue", "Expenditure", "Difference", "Active"], d.elements.map((row) => { const total = r.byElement.find((item) => item.id === row.id); return [row.id, row.code, total?.revenue ?? null, total?.cost ?? null, total?.difference ?? null, total ? 1 : 0]; }), [38, 16, 22, 22, 22, 14]);
  const fundTotals = sheet("Fund totals", ["Fund ID", "Name", "Vintage", "Available", "Allocated", "Remaining", "Required match", "Proposed match", "Match difference"], r.byFund.map((row) => [row.id, row.name, row.vintage, row.available, row.allocated, row.remainder, row.requiredMatch, row.providedMatch, row.matchDifference]), [38, 40, 25, 22, 22, 22]);
  const summary = sheet("Reconciliation", ["Measure", `Amount (${d.currency})`], [["Proposed revenue", r.revenue], ["Proposed expenditure", r.cost], ["Revenue less expenditure", r.difference], ["Duplicate allocation rows", r.issues.filter((row) => row.code === "duplicate_allocation").length], ["Unresolved element totals", r.byElement.filter((row) => row.revenue === null || row.cost === null).length], ["Known work-element funding subtotal", r.knownRevenue], ["Known work-element expenditure subtotal", r.knownCost]], [45, 30]);
  sheet("Mappings", ["Row ID", "Decision", "Proposed element IDs", "Explanation"], p.mappings.map((row) => [row.id, row.disposition, row.targetIds.join("\n"), row.note]), [38, 24, 60, 100]);
  sheet("Source sections", ["Row ID", "Section", "Treatment", "Explanation", "Proposed narrative"], p.sourceSections.map((row) => [row.id, row.title, row.status, row.note, row.proposedText ?? ""]), [38, 50, 24, 100, 100]);
  sheet("Amendments", ["Row ID", "Amendment source ID", "Modified source ID", "Decision", "Explanation"], p.amendments.map((row) => [row.id, row.amendmentSourceId, row.modifiesSourceId, row.status, row.note]), [38, 38, 38, 24, 100]);
  sheet("Conflicts", ["Row ID", "Conflict", "Status", "Resolution / missing evidence"], p.conflicts.map((row) => [row.id, row.description, row.status, row.resolution]), [38, 80, 22, 100]);
  sheet("Original budget passages", ["Source", "Work element", "First PDF page", "Last PDF page", "Original printed budget text, reference only"], sources.flatMap((source) => source.extraction_json.elements.map((element) => [source.title, element.code, element.pageFrom, element.pageTo, element.budgetText])), [45,18,18,18,110]);
  sheet("Original program passages", ["Source section", "Retained original text, reference only"], p.sourceSections.filter((row) => row.retainedText).map((row) => [row.title,row.retainedText!]), [50,110]);
  sheet("Source figures", ["Row ID", "Original table", "Original row", "Original column", "Source units", "Printed cell", "Numeric reference value", "Printed state", "Reference note"], (p.referenceFigures ?? []).map((row) => [row.id,row.table,row.row,row.column,row.unit,row.sourceText,row.value,row.state,row.note]), [38,45,45,35,22,25,25,22,90]);
  sheet("Sources", ["Source ID", "Document ID", "Title", "Role", "Original SHA-256", "Selected extraction", "PDF pages", "Official URL"], sources.map((row) => [row.id, row.document_id, row.title, row.source_role, row.document_checksum, row.selectedVersionId ?? "original attachment", row.page_count, row.source_url]), [38, 38, 60, 22, 68, 38, 18, 90]);
  const cited = [...d.elements.map((element) => ({ id: element.id, sourceRefs: [...(element.source ? [element.source] : []), ...(element.sourceRefs ?? [])] })), ...d.elements.flatMap((element) => [...element.tasks, ...element.products].map((row) => ({ id: row.id, sourceRefs: row.sourceRefs ?? [] }))), ...(p.referenceFigures ?? []), ...p.funds, ...p.allocations, ...p.costs, ...p.staffing, ...p.indirectPools, ...p.mappings, ...p.sourceSections, ...p.amendments, ...p.conflicts];
  sheet("Source passages", ["Contributing row ID", "Source ID", "Extraction version", "Source element key", "First PDF page", "Last PDF page", "Table / passage", "Supported figure / assumption"], cited.flatMap((row) => row.sourceRefs.map((ref) => [row.id, ref.sourceId, ref.extractionVersionId ?? "original attachment", ref.elementKey, ref.pageFrom, ref.pageTo, ref.tableLabel, ref.purpose ?? ""])), [38, 38, 38, 30, 20, 20, 80, 80]);
  sheet("Unresolved items", ["Finding at export", "Contributing row IDs"], [...r.issues.map((row): Cell[] => [row.message, row.rowIds.join("\n")]), ...workProgramCoverage(d, originals).filter((row) => row.unmappedElements.length || row.uncoveredPages.length || row.amendmentUnresolved).map((row): Cell[] => [`${row.title}: unmatched work ${row.unmappedElements.map((element) => element.code).join(", ")}; uncovered PDF pages ${row.uncoveredPages.join(", ")}; amendment unresolved ${row.amendmentUnresolved}`, row.sourceId])], [100, 80]);
  const end = (rows: unknown[]) => Math.max(2, rows.length + 1), ee = end(d.elements), fe = end(p.funds), ae = end(p.allocations), ce = end(p.costs), se = end(p.staffing);
  const active = (row: number) => `IFERROR(INDEX('Work elements'!J$2:J$${ee},MATCH(B${row},'Work elements'!A$2:A$${ee},0)),0)`;
  d.elements.forEach((element, index) => { const row = index + 2; formula(elements, `J${row}`, `IF(AND(D${row}<>"completed",E${row}<>"informational"),1,0)`, element.disposition !== "completed" && element.budgetTreatment !== "informational" ? 1 : 0); });
  p.allocations.forEach((item, index) => {
    const row = index + 2, fund = p.funds.find((fund) => fund.id === item.fundId), enabled = r.byElement.some((entry) => entry.id === item.elementId);
    const eligible = fund?.basis === "proposed" && !["prior_authority", "prior_balance"].includes(fund.kind);
    formula(allocations, `H${row}`, active(row), enabled ? 1 : 0);
    formula(allocations, `I${row}`, `IFERROR(IF(AND(INDEX('Funding sources'!E$2:E$${fe},MATCH(D${row},'Funding sources'!A$2:A$${fe},0))="proposed",INDEX('Funding sources'!D$2:D$${fe},MATCH(D${row},'Funding sources'!A$2:A$${fe},0))<>"prior_authority",INDEX('Funding sources'!D$2:D$${fe},MATCH(D${row},'Funding sources'!A$2:A$${fe},0))<>"prior_balance"),1,0),0)`, eligible ? 1 : 0);
    formula(allocations, `J${row}`, `IF(H${row}=0,0,IF(AND(I${row}=1,ISNUMBER(E${row})),ROUND(E${row},2),"Unresolved"))`, !enabled ? 0 : eligible ? item.amount : null);
    formula(allocations, `K${row}`, `COUNTIFS(B$2:B$${ae},B${row},C$2:C$${ae},IF(C${row}="","",C${row}),D$2:D$${ae},D${row})`, p.allocations.filter((other) => other.elementId === item.elementId && other.taskId === item.taskId && other.fundId === item.fundId).length);
  });
  p.costs.forEach((item, index) => { const row = index + 2, enabled = r.byElement.some((entry) => entry.id === item.elementId); formula(costs, `J${row}`, active(row), enabled ? 1 : 0); formula(costs, `K${row}`, `IF(J${row}=0,0,IF(ISNUMBER(F${row}),ROUND(F${row},2),"Unresolved"))`, enabled ? item.amount : 0); });
  p.staffing.forEach((item, index) => {
    const row = index + 2, values = r.staff[index];
    formula(staffing, `S${row}`, `IF(NOT(ISNUMBER(H${row})),"Unresolved",IF(I${row}="hours",H${row},IF(AND(ISNUMBER(X${row}),X${row}>0,K${row}<>""),H${row}*X${row},"Unresolved")))`, values.hours);
    formula(staffing, `T${row}`, `IF(L${row}="capacity_only","",IF(AND(ISNUMBER(S${row}),ISNUMBER(M${row}),N${row}="labor_cost",O${row}<=F${row},P${row}>=G${row},R${row}<>"",V${row}>0),ROUND(S${row}*M${row},2),"Unresolved"))`, item.costTreatment === "capacity_only" ? "" : values.cost);
    formula(staffing, `U${row}`, active(row), r.byElement.some((entry) => entry.id === item.elementId) ? 1 : 0);
    formula(staffing, `Y${row}`, `IF(D${row}<>"",D${row},E${row})`, item.staffId ?? item.role);
    const unknownCapacity = r.issues.some((issue) => ["staff_capacity", "capacity_conflict", "staff_overlap_unresolved", "capacity_unresolved", "staff_identity", "staff_period"].includes(issue.code) && issue.rowIds.includes(item.id));
    formula(staffing, `W${row}`, `IF(OR(NOT(ISNUMBER(J${row})),K${row}="",NOT(ISNUMBER(S${row})),Y${row}="",F${row}<'Program narrative'!B3,G${row}>'Program narrative'!B4,G${row}<F${row},COUNTIFS(Y$2:Y$${se},Y${row},F$2:F$${se},F${row},G$2:G$${se},G${row},S$2:S$${se},"Unresolved")>0,COUNTIFS(Y$2:Y$${se},Y${row},F$2:F$${se},F${row},G$2:G$${se},G${row},J$2:J$${se},"<>"&J${row})>0,COUNTIFS(Y$2:Y$${se},Y${row},F$2:F$${se},F${row},G$2:G$${se},G${row},K$2:K$${se},"<>"&K${row})>0,COUNTIFS(Y$2:Y$${se},Y${row},F$2:F$${se},"<="&G${row},G$2:G$${se},">="&F${row})>COUNTIFS(Y$2:Y$${se},Y${row},F$2:F$${se},F${row},G$2:G$${se},G${row})),"Unresolved",IF(SUMIFS(S$2:S$${se},Y$2:Y$${se},Y${row},F$2:F$${se},F${row},G$2:G$${se},G${row})>J${row},"Overallocated","Within stated capacity"))`, unknownCapacity ? "Unresolved" : r.issues.some((issue) => issue.code === "staff_overallocated" && issue.rowIds.includes(item.id)) ? "Overallocated" : "Within stated capacity");
  });
  d.elements.forEach((item, index) => {
    const row = index + 2, values = r.byElement.find((entry) => entry.id === item.id);
    formula(elementTotals, `F${row}`, `'Work elements'!J${row}`, values ? 1 : 0);
    formula(elementTotals, `C${row}`, `IF(F${row}=0,"Excluded",IF(OR(COUNTIF('Allocations'!B$2:B$${ae},A${row})=0,COUNTIFS('Allocations'!B$2:B$${ae},A${row},'Allocations'!J$2:J$${ae},"Unresolved")>0),"Unresolved",ROUND(SUMIF('Allocations'!B$2:B$${ae},A${row},'Allocations'!J$2:J$${ae}),2)))`, values ? values.revenue : "Excluded");
    formula(elementTotals, `D${row}`, `IF(F${row}=0,"Excluded",IF(OR(COUNTIF('Expenditures'!B$2:B$${ce},A${row})+COUNTIFS('Staffing'!B$2:B$${se},A${row},'Staffing'!L$2:L$${se},"calculate")=0,COUNTIFS('Expenditures'!B$2:B$${ce},A${row},'Expenditures'!K$2:K$${ce},"Unresolved")+COUNTIFS('Staffing'!B$2:B$${se},A${row},'Staffing'!T$2:T$${se},"Unresolved")>0),"Unresolved",ROUND(SUMIF('Expenditures'!B$2:B$${ce},A${row},'Expenditures'!K$2:K$${ce})+SUMIF('Staffing'!B$2:B$${se},A${row},'Staffing'!T$2:T$${se}),2)))`, values ? values.cost : "Excluded");
    formula(elementTotals, `E${row}`, `IF(AND(ISNUMBER(C${row}),ISNUMBER(D${row})),ROUND(C${row}-D${row},2),"Unresolved")`, values?.difference ?? null);
  });
  p.funds.forEach((item, index) => { const row = index + 2, values = r.byFund[index]; formula(fundTotals, `D${row}`, `IF(AND('Funding sources'!E${row}="proposed",'Funding sources'!D${row}<>"prior_authority",'Funding sources'!D${row}<>"prior_balance",ISNUMBER('Funding sources'!F${row})),'Funding sources'!F${row},"Unresolved")`, values.available); formula(fundTotals, `E${row}`, `IF(COUNTIFS('Allocations'!D$2:D$${ae},A${row},'Allocations'!H$2:H$${ae},1,'Allocations'!E$2:E$${ae},"")>0,"Unresolved",ROUND(SUMIFS('Allocations'!E$2:E$${ae},'Allocations'!D$2:D$${ae},A${row},'Allocations'!H$2:H$${ae},1),2))`, values.allocated); formula(fundTotals, `F${row}`, `IF(AND(ISNUMBER(D${row}),ISNUMBER(E${row})),ROUND(D${row}-E${row},2),"Unresolved")`, values.remainder); });
  p.funds.forEach((item, index) => {
    const row = index + 2, values = r.byFund[index];
    formula(fundTotals, `G${row}`, `IF(OR('Funding sources'!L${row}="",'Funding sources'!M${row}=0,'Funding sources'!J${row}="unresolved"),"Unresolved",IF('Funding sources'!J${row}="not_required",0,IF(NOT(ISNUMBER('Funding sources'!K${row})),"Unresolved",IF('Funding sources'!J${row}="amount",ROUND('Funding sources'!K${row},2),IF(NOT(ISNUMBER(E${row})),"Unresolved",IF('Funding sources'!J${row}="percent_funded_amount",ROUND(E${row}*'Funding sources'!K${row}/100,2),IF(AND('Funding sources'!J${row}="percent_total_cost",'Funding sources'!K${row}<100),ROUND(E${row}*'Funding sources'!K${row}/(100-'Funding sources'!K${row}),2),"Unresolved")))))))`, values.requiredMatch);
    formula(fundTotals, `H${row}`, `IF(COUNTIFS('Allocations'!F$2:F$${ae},A${row},'Allocations'!H$2:H$${ae},1,'Allocations'!J$2:J$${ae},"Unresolved")+COUNTIFS('Allocations'!F$2:F$${ae},A${row},'Allocations'!D$2:D$${ae},A${row},'Allocations'!H$2:H$${ae},1)>0,"Unresolved",ROUND(SUMIFS('Allocations'!J$2:J$${ae},'Allocations'!F$2:F$${ae},A${row},'Allocations'!H$2:H$${ae},1),2))`, values.providedMatch);
    formula(fundTotals, `I${row}`, `IF(AND(ISNUMBER(G${row}),ISNUMBER(H${row})),ROUND(H${row}-G${row},2),"Unresolved")`, values.matchDifference);
  });
  p.indirectPools.forEach((item, index) => { const row = index + 2, selected = p.costs.filter((cost) => cost.indirectPoolId === item.id && cost.category === "indirect" && r.byElement.some((element) => element.id === cost.elementId)); const total = selected.some((cost) => cost.amount === null) ? null : selected.reduce((sum, cost) => sum + Math.round(cost.amount! * 100), 0) / 100; formula(pools, `D${row}`, `IF(COUNTIFS('Expenditures'!H$2:H$${ce},A${row},'Expenditures'!D$2:D$${ce},"indirect",'Expenditures'!J$2:J$${ce},1,'Expenditures'!F$2:F$${ce},"")>0,"Unresolved",ROUND(SUMIFS('Expenditures'!F$2:F$${ce},'Expenditures'!H$2:H$${ce},A${row},'Expenditures'!D$2:D$${ce},"indirect",'Expenditures'!J$2:J$${ce},1),2))`, total); formula(pools, `E${row}`, `IF(AND(ISNUMBER(C${row}),ISNUMBER(D${row})),ROUND(C${row}-D${row},2),"Unresolved")`, item.amount === null || total === null ? null : (Math.round(item.amount * 100) - Math.round(total * 100)) / 100); });
  for (const [cell, column, value] of [["B2", "C", r.revenue], ["B3", "D", r.cost]] as const) formula(summary, cell, `IF(OR(SUM('Element totals'!F2:F${ee})=0,COUNTIF('Element totals'!${column}2:${column}${ee},"Unresolved")>0),"Unresolved",ROUND(SUM('Element totals'!${column}2:${column}${ee}),2))`, value);
  formula(summary, "B7", `IF(COUNT('Element totals'!C2:C${ee})=0,"Unresolved",ROUND(SUM('Element totals'!C2:C${ee}),2))`, r.knownRevenue);
  formula(summary, "B8", `IF(COUNT('Element totals'!D2:D${ee})=0,"Unresolved",ROUND(SUM('Element totals'!D2:D${ee}),2))`, r.knownCost);
  formula(summary, "B4", 'IF(AND(ISNUMBER(B2),ISNUMBER(B3)),ROUND(B2-B3,2),"Unresolved")', r.difference);
  formula(summary, "B5", `COUNTIF('Allocations'!K2:K${ae},">1")`, p.allocations.filter((item) => p.allocations.filter((other) => item.elementId === other.elementId && item.taskId === other.taskId && item.fundId === other.fundId).length > 1).length);
  formula(summary, "B6", `COUNTIF('Element totals'!C2:C${ee},"Unresolved")+COUNTIF('Element totals'!D2:D${ee},"Unresolved")`, r.byElement.reduce((sum, item) => sum + Number(item.revenue === null) + Number(item.cost === null), 0));
  for (const name of book.SheetNames) for (const [address, cell] of Object.entries(book.Sheets[name])) if (!address.startsWith("!") && cell.t === "n") cell.z = "#,##0.00";
  // Real date cells make relational criteria work in Excel and LibreOffice.
  const dateCell = (sheetName: string, address: string) => {
    const cell = book.Sheets[sheetName][address];
    if (cell?.t === "s" && /^\d{4}-\d{2}-\d{2}$/.test(String(cell.v))) {
      cell.v = Date.parse(`${cell.v}T00:00:00Z`) / 86400000 + 25569;
      cell.t = "n"; cell.z = "yyyy-mm-dd";
    }
  };
  for (const address of ["B3", "B4"]) dateCell("Program narrative", address);
  p.funds.forEach((_, i) => { for (const col of ["G", "H"]) dateCell("Funding sources", `${col}${i + 2}`); });
  p.staffing.forEach((_, i) => { for (const col of ["F", "G", "O", "P"]) dateCell("Staffing", `${col}${i + 2}`); });
  // Explicit input tables already carry units. Cached formula values match the application calculation.
  void funds;
  return book;
}
