import { NextRequest, NextResponse } from "next/server";
import { z } from "zod";
import { BODY_LIMITS, readJsonOrNullWithLimit } from "@/lib/http/body-limit";
import { createApiAuditLogger } from "@/lib/observability/audit";
import { createClient } from "@/lib/supabase/server";
import { authorizeMeasureWrite } from "@/lib/measures/write-authorization";

/**
 * TURN THE PUBLIC OVERSIGHT PAGE ON OR OFF.
 *
 * The `/api/rtp-cycles/[rtpCycleId]/public-share` route in shape: a 40-character
 * token minted on first enable and never regenerated by this route, an
 * `enabled` flag that is what actually opens the page, and a role gate.
 *
 * ============================================================================
 * THE TOKEN IS THE CREDENTIAL, AND THE FLAG IS THE SWITCH
 * ============================================================================
 *
 * Two columns rather than one, deliberately (20260812000011). Disabling clears
 * `public_share_enabled` and LEAVES the token, so an agency that turns the page
 * off for a month and back on does not invalidate the link it printed in a
 * meeting agenda. `public_share_token` alone opens nothing: the public page
 * matches on BOTH columns, so a leaked token against a disabled fund is a 404.
 *
 * THERE IS NO REGENERATE HERE. Rotating the credential is a different act with
 * a different consequence — every previously published link dies — and putting
 * it behind the same button as "turn it on" is how somebody rotates it by
 * accident. If an agency needs rotation it is its own route with its own
 * confirmation, and nothing in this lane pretends to offer it.
 *
 * ============================================================================
 * WHY `programs.write` AND NOT THE DECISION GATE
 * ============================================================================
 *
 * Publishing the oversight record is not moving money, so it is the same
 * authority that maintains the measure's record — `authorizeMeasureWrite`'s
 * default. The stricter `invoices.write` gate governs approving and paying
 * claims and nothing else, and widening it to cover publishing would mean a
 * member who maintains the fund could not show it to the committee that
 * oversees it. The agent may not reach this at all: see
 * `refused-measure-fund-actions-stay-refused.test.ts`, refusal 4.
 *
 * WHAT IS AUDITED. Both directions, with the workspace and the actor. Turning a
 * public surface on is exactly the event an operator needs to be able to find
 * afterwards, and turning it off is the one somebody will need to prove.
 */

const paramsSchema = z.object({ measureId: z.string().uuid() });
const bodySchema = z.object({ enabled: z.boolean() });

/**
 * 40 hex-ish characters from two UUIDs, the `/plan` share-token recipe.
 *
 * Copied rather than shared because the two surfaces must be able to change
 * their credential independently, and 40 characters of `crypto.randomUUID`
 * entropy is not the kind of thing a helper makes safer.
 */
function generateShareToken(): string {
  return (crypto.randomUUID() + crypto.randomUUID()).replace(/-/g, "").slice(0, 40);
}

export async function POST(request: NextRequest, context: { params: Promise<{ measureId: string }> }) {
  const audit = createApiAuditLogger("measures.public_share", request);
  const startedAt = Date.now();

  try {
    const routeParams = paramsSchema.safeParse(await context.params);
    if (!routeParams.success) {
      return NextResponse.json({ error: "Invalid measure id" }, { status: 400 });
    }

    const payloadBody = await readJsonOrNullWithLimit(request, BODY_LIMITS.smallJson);
    if (!payloadBody.ok) return payloadBody.response;
    const payload = bodySchema.safeParse(payloadBody.data);
    if (!payload.success) {
      return NextResponse.json({ error: "Invalid public-share payload" }, { status: 400 });
    }

    const supabase = await createClient();
    // The repo's untyped-client convention, and the recorded fix for the TS2589
    // this exact shape produces: a real Supabase client passed into a
    // structural `SupabaseLike` sends the checker down a recursive builder
    // type. Every route in this lane casts at the call site for the same
    // reason, where it is visible.
    const authorization = await authorizeMeasureWrite(
      supabase as unknown as Parameters<typeof authorizeMeasureWrite>[0],
      audit,
      routeParams.data.measureId,
      { intent: "The public oversight page setting" }
    );
    if (!authorization.ok) return authorization.response;

    const fund = authorization.fund;
    // `MeasureFundRow` (write-authorization.ts, Lane 2's) declares
    // `public_share_enabled` but not the token — the token is read and written
    // by this lane alone, so the narrowing happens here rather than widening a
    // shared type that no other caller needs. `MEASURE_FUND_COLUMNS` selects
    // the column, so the value is present at runtime.
    const updates: Record<string, unknown> = { public_share_enabled: payload.data.enabled };
    let token = (fund as { public_share_token?: string | null }).public_share_token ?? null;
    if (payload.data.enabled && !token) {
      token = generateShareToken();
      updates.public_share_token = token;
    }

    const { data: updated, error: updateError } = await supabase
      .from("measure_funds")
      .update(updates)
      .eq("id", fund.id)
      // The workspace scope is re-stated on the write even though the fund was
      // already proven to sit in it. The read that proved it and this write are
      // two statements, and an `.eq()` that only guards the first is the shape
      // this repo has shipped before.
      .eq("workspace_id", authorization.workspaceId)
      // AND THE WRITE OBSERVES ITSELF. PostgREST answers an update that matched
      // NOTHING with a 200 and no error — an RLS policy that refused it looks
      // identical to a success. On this route that would tell an agency its
      // oversight page is live when nothing was published, or that it came down
      // when it is still readable by anyone holding the link. Both are worse
      // than an error.
      .select("id, public_share_enabled");

    if (updateError) {
      audit.error("update_failed", { error: updateError.message, code: updateError.code ?? null });
      return NextResponse.json({ error: "Failed to update public sharing" }, { status: 500 });
    }

    if (!updated || updated.length === 0) {
      audit.warn("update_matched_no_rows", { measureId: fund.id, enabled: payload.data.enabled });
      return NextResponse.json(
        {
          error: "Nothing was changed",
          details:
            "The database accepted the request but changed no row, so the public oversight page is still " +
            "in whatever state it was in. Reload the page to see which.",
        },
        { status: 409 }
      );
    }

    audit.info("updated", {
      measureId: fund.id,
      workspaceId: authorization.workspaceId,
      userId: authorization.userId,
      enabled: payload.data.enabled,
      mintedToken: Boolean(updates.public_share_token),
      durationMs: Date.now() - startedAt,
    });

    return NextResponse.json({
      enabled: payload.data.enabled,
      token,
      shareUrl: payload.data.enabled && token ? `/measure/${token}` : null,
    });
  } catch (error) {
    audit.error("unhandled_error", { error: error instanceof Error ? error.message : String(error) });
    return NextResponse.json({ error: "Unexpected error while updating public sharing" }, { status: 500 });
  }
}
