"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { accountingFields, type ContractState } from "@/lib/invoicing/contracts/schema";
import { currentActuals } from "@/lib/invoicing/contracts/reconciliation";
import { Field, inputClass, type CommandSender } from "./fields";
export function AccountingReconciliation({state,send,busy}:{state:ContractState;send:CommandSender;busy:boolean}) {
 const [error,setError]=useState("");const actuals=currentActuals(state.actuals),reviews=state.accountingReviews??[];
 return <section className="space-y-5"><h2 className="text-xl font-semibold">Accounting and payroll reconciliation</h2><p>The agency accounting system remains authoritative for posted transactions. This intake compares its export with existing OpenPlan sources. It creates no cost entries. Original rows, discrepancies and reviewer decisions remain retained.</p>{error&&<p role="alert">{error}</p>}
 <form className="space-y-3 rounded border p-4" onSubmit={async e=>{e.preventDefault();setError("");const d=new FormData(e.currentTarget),file=d.get("file");if(!(file instanceof File)||file.size>1000000){setError("Choose a UTF-8 CSV up to 1 MB and 200 records.");return;}await send({kind:"accounting_import",requestId:crypto.randomUUID(),filename:file.name,csv:await file.text(),mapping:{externalId:String(d.get("externalId")??""),sourceKey:String(d.get("sourceKey")??""),amount:String(d.get("amount")??""),hours:String(d.get("hours")??""),currency:String(d.get("currency")??"")}});}}>
 <Field label="Original accounting or payroll CSV"><input name="file" type="file" accept=".csv,text/csv" className={inputClass} required/></Field><p>Map the exported column names. Leave the hours column blank for cost-only entries.</p>{accountingFields.map(f=><Field key={f} label={`CSV column for ${f}`}><input className={inputClass} name={f} defaultValue={f} required={f!=="hours"}/></Field>)}<Button disabled={busy}>Retain accounting comparison</Button></form>
 {(state.accountingImports??[]).map(imp=><article className="space-y-3 rounded border p-4" key={imp.id}><h3 className="font-semibold">{imp.filename}</h3><a className="underline" href={`/api/invoicing/engagements/${state.engagement.id}/management/accounting-file?importId=${imp.id}`}>Download original accounting export</a>{imp.rows.map((row,ix)=>{const source=actuals.find(a=>a.command.sourceKey===row.sourceKey),review=reviews.filter(r=>r.import_id===imp.id&&r.row_index===ix).at(-1),stale=review&&review.actual_version_id!==(source?.id??null);return <form className="space-y-2 rounded border p-3" key={ix} onSubmit={async e=>{e.preventDefault();const d=new FormData(e.currentTarget);await send({kind:"accounting_review",requestId:crypto.randomUUID(),expectedVersion:review?.version??0,importId:imp.id,rowIndex:ix,actualVersionId:source?.id??null,state:String(d.get("state")) as "reconciled"|"unresolved",evidence:String(d.get("evidence")??"")});}}><p className="font-medium">{row.externalId} · {row.sourceKey}</p><p>External posted amount {row.amount} {row.currency}; hours {row.hours??"not supplied"}. OpenPlan amount {source?.amount??"unmapped or unvalued"}; hours {source?.hours??"not supplied"}.</p><p>{stale?"Source changed after review. Review again.":review?.state??"Not reviewed"} {review?.evidence}</p><Field label={`Decision for ${row.externalId}`}><select name="state" className={inputClass}><option value="unresolved">Discrepancy remains unresolved</option><option value="reconciled">Exact source values reconciled</option></select></Field><Field label={`Evidence for ${row.externalId}`}><textarea name="evidence" className={inputClass} required/></Field><Button disabled={busy}>Retain accounting review</Button></form>;})}</article>)}
 </section>;
}
