"use client";
import { Button } from "@/components/ui/button";
import type { ContractActual, ContractState, ActualVersion } from "@/lib/invoicing/contracts/schema";
import { Field,inputClass,TextField,NoteField,useRetainedDraft,type CommandSender } from "./fields";
export function emptyActual(staffId:string|null=null):ContractActual {return {kind:"actual",requestId:"",entryId:"",expectedVersion:0,sourceKey:"",sourceReference:"",entryDate:new Date().toISOString().slice(0,10),category:"labor",status:"draft",description:"",staffId,hours:null,amount:null,valuationBasis:"unvalued",rateId:null,billable:true,timeEntryId:null,spendEntryId:null,owpVersionId:null,invoiceId:null,allocations:[],correctionNote:"",openingStart:null,openingEnd:null,openingBasis:"",reconciliationNote:""};}
export function ActualForm({state,send,busy,correcting,onSaved}:{state:ContractState;send:CommandSender;busy:boolean;correcting?:ActualVersion;onSaved:()=>void}) {
 const admin=state.role!=="member", baseline=state.baselines.filter(b=>b.state==="approved").at(-1);
 const initial=correcting?{...correcting.command,expectedVersion:correcting.version,amount:correcting.amount,timeEntryId:correcting.time_entry_id,spendEntryId:correcting.spend_entry_id,correctionNote:""}:emptyActual(state.staff[0]?.id??null);
 const draft=useRetainedDraft<ContractActual>(`contract-actual:${state.engagement.id}:${correcting?.id??"new"}`,initial),value=draft.value;
 function set<K extends keyof ContractActual>(key:K,v:ContractActual[K]){draft.setValue({...value,[key]:v});}
 return <form className="space-y-4" onSubmit={async e=>{e.preventDefault();if(await send({...value,requestId:crypto.randomUUID(),entryId:correcting?.entry_id??crypto.randomUUID(),expectedVersion:correcting?.version??0})){draft.setValue(emptyActual(state.staff[0]?.id??null));onSaved();}}}>
 <p className="text-sm text-muted-foreground">{correcting?"Record a new version with a correction reason. Prior valuations and issued snapshots remain retained.":"Record the source once. Review time, spending, commitments and documented cash separately."}</p>
 {draft.error&&<p role="alert">{draft.error}</p>}
 <div className="grid gap-3 sm:grid-cols-2"><TextField label="Source key from the originating record" value={value.sourceKey} onChange={v=>set("sourceKey",v)} required/><TextField label="Entry date" type="date" value={value.entryDate} onChange={v=>set("entryDate",v)} required/></div>
 <NoteField label="Source reference and retained evidence" value={value.sourceReference} onChange={v=>set("sourceReference",v)} required/><NoteField label="Work or transaction description" value={value.description} onChange={v=>set("description",v)} required/>
 {admin&&<div className="grid gap-3 sm:grid-cols-2"><Field label="Record meaning"><select className={inputClass} value={value.category} onChange={e=>set("category",e.target.value as ContractActual["category"])}>{["labor","expense","opening","commitment","payment","credit"].map(k=><option key={k} value={k}>{k}</option>)}</select></Field><Field label="Review state"><select className={inputClass} value={value.status} onChange={e=>set("status",e.target.value as ContractActual["status"])}><option value="draft">Draft, unreviewed</option><option value="approved">Reviewed and approved actual</option><option value="excluded">Excluded with reason</option></select></Field></div>}
 <Field label="Staff identity"><select className={inputClass} value={value.staffId??""} onChange={e=>set("staffId",e.target.value||null)}><option value="">No staff attribution</option>{state.staff.map(s=><option key={s.id} value={s.id}>{s.name}{s.active?"":" (inactive)"}</option>)}</select></Field>
 <TextField label="Hours, empty if unknown" value={value.hours} onChange={v=>set("hours",v||null)}/>
 {admin&&<div className="grid gap-3 sm:grid-cols-2"><Field label="Cost valuation"><select className={inputClass} value={value.valuationBasis} onChange={e=>set("valuationBasis",e.target.value as ContractActual["valuationBasis"])}><option value="unvalued">Unvalued</option><option value="recorded">Documented amount</option><option value="cost_rate">Effective approved cost rate</option></select></Field>{value.valuationBasis==="cost_rate"?<Field label="Cost rate"><select className={inputClass} value={value.rateId??""} onChange={e=>set("rateId",e.target.value||null)}><option value="">Select rate</option>{state.rates.filter(r=>r.basis==="cost"&&r.staff_id===value.staffId).map(r=><option value={r.id} key={r.id}>{r.hourly_rate}/hour · {r.starts_on} to {r.ends_on}</option>)}</select></Field>:<TextField label="Documented amount" value={value.amount} onChange={v=>set("amount",v||null)}/>}</div>}
 <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={value.billable} onChange={e=>set("billable",e.target.checked)}/>Billable work. Clear for nonbillable rework.</label>
 <fieldset className="space-y-3 rounded border p-4"><legend className="px-2 font-medium">Task allocations</legend><p className="text-sm">Shares use basis points: 10,000 is 100%. Split totals must equal 10,000. The last allocation retains rounding cents.</p>
 {value.allocations.map((a,i)=><div key={i} className="grid gap-3 sm:grid-cols-[1fr_10rem_auto]"><Field label="Approved task"><select className={inputClass} value={a.taskId} required onChange={e=>set("allocations",value.allocations.map((v,n)=>n===i?{...v,taskId:e.target.value,deliverableId:baseline?.content.tasks.find(t=>t.id===e.target.value)?.deliverableId??null}:v))}><option value="">Select task</option>{baseline?.content.tasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></Field><TextField label="Share, basis points" value={String(a.share)} onChange={v=>set("allocations",value.allocations.map((a,n)=>n===i?{...a,share:Number(v)}:a))}/><Button type="button" variant="outline" onClick={()=>set("allocations",value.allocations.filter((_,n)=>n!==i))}>Remove</Button></div>)}
 <Button type="button" variant="outline" onClick={()=>set("allocations",[...value.allocations,{taskId:"",deliverableId:null,share:value.allocations.length?0:10000}])}>Add task allocation</Button></fieldset>
 {value.category==="opening"&&<><div className="grid gap-3 sm:grid-cols-2"><TextField label="Opening coverage start" type="date" value={value.openingStart} onChange={v=>set("openingStart",v||null)}/><TextField label="Opening coverage end" type="date" value={value.openingEnd} onChange={v=>set("openingEnd",v||null)}/></div><NoteField label="Documented opening balance basis" value={value.openingBasis} onChange={v=>set("openingBasis",v)}/></>}
 {admin&&<details className="rounded border p-3"><summary>Map existing time, spending or OWP records</summary><p className="my-2 text-sm">Choose the existing source instead of entering it again. Shared OWP sources require the current matching OWP valuation ID.</p>{(["timeEntryId","spendEntryId","owpVersionId"] as const).map(k=><TextField key={k} label={k==="timeEntryId"?"Existing time ID":k==="spendEntryId"?"Existing spending ID":"Current OWP valuation ID"} value={value[k]} onChange={v=>set(k,v||null)}/>)}</details>}
 {(["payment","credit"] as string[]).includes(value.category)&&<Field label="Issued invoice"><select className={inputClass} value={value.invoiceId??""} onChange={e=>set("invoiceId",e.target.value||null)}><option value="">Select invoice</option>{state.invoices.filter(i=>["sent","paid"].includes(i.status)).map(i=><option key={i.id} value={i.id}>{i.invoice_number}</option>)}</select></Field>}
 <NoteField label="Overlap reconciliation, including opening balances" value={value.reconciliationNote} onChange={v=>set("reconciliationNote",v)}/>
 {correcting&&<NoteField label="Correction reason" value={value.correctionNote} onChange={v=>set("correctionNote",v)} required/>}
 <Button disabled={busy}>{correcting?"Record correction":"Save actual record"}</Button>
 </form>;
}
