import { readDocumentedCash } from "@/lib/invoicing/contracts/cash-summary-server";
import { cents,decimalText } from "@/lib/programs/work-program/reporting";
const buckets=["Not yet due","1–30 days","31–60 days","61–90 days","Over 90 days","Due date missing"];
/** Display exact documented cash and obligations; an invoice status is not a payment event. */
export async function ContractCashPosition({workspaceId,clientId,details=false}:{workspaceId:string;clientId?:string;details?:boolean}){
 const data=await readDocumentedCash(workspaceId),rows=data.rows.filter(r=>!clientId||r.client_id===clientId),positions=data.positions.filter(p=>!clientId||p.clientId===clientId),missing=rows.length-positions.length;
 const today=new Date().toISOString().slice(0,10),totals=new Map<string,{open:bigint;cash:bigint;retention:bigint;disputed:bigint;refundObligation:bigint;aging:bigint[];unassessedDue:number}>();let warnings=0;
 for(const p of positions){
  const total=totals.get(p.currency)??{open:BigInt(0),cash:BigInt(0),retention:BigInt(0),disputed:BigInt(0),refundObligation:BigInt(0),aging:buckets.map(()=>BigInt(0)),unassessedDue:0};
  const open=cents(p.open),due=p.currentlyDue===null?null:cents(p.currentlyDue);total.open+=open;total.cash+=cents(p.payments)-cents(p.refunds);total.retention+=cents(p.retention);total.disputed+=cents(p.disputed);if(open<BigInt(0))total.refundObligation-=open;
  if(due===null)total.unassessedDue++;
  if(due!==null&&due>BigInt(0)){const days=p.dueOn?Math.floor((Date.parse(today)-Date.parse(p.dueOn))/86400000):null;const bucket=days===null||!Number.isFinite(days)?5:days<=0?0:days<=30?1:days<=60?2:days<=90?3:4;total.aging[bucket]+=due;}
  totals.set(p.currency,total);warnings+=p.warnings.length;
 }
 return <section className="space-y-2"><h2 className="text-sm font-semibold">Documented client invoice balances</h2>{data.failed?<p>The complete invoice list could not be read. No total is asserted.</p>:!rows.length?<p>No issued client invoices.</p>:<>{[...totals].map(([currency,total])=><div key={currency} className="space-y-2"><p className="text-2xl font-semibold">{decimalText(total.open)} {currency}{missing?" known balance":" open balance"}</p>{details&&<><p>Documented receipts less refunds: {decimalText(total.cash)} {currency}. Retention: {decimalText(total.retention)}. Disputed: {decimalText(total.disputed)}. Refund obligations: {decimalText(total.refundObligation)}.</p><div className="overflow-x-auto"><table className="w-full text-sm"><caption className="text-left">{currency} {total.unassessedDue?"Known currently due amounts":"currently due amounts"} by days after due date, as of {today}</caption><thead><tr>{buckets.map(b=><th className="p-2 text-left" key={b}>{b}</th>)}</tr></thead><tbody><tr>{total.aging.map((amount,i)=><td className="p-2" key={buckets[i]}>{decimalText(amount)}</td>)}</tr></tbody></table></div>{total.unassessedDue>0&&<p>{total.unassessedDue} invoices have unassessed amounts currently due. Aging is incomplete until their hold allocation is reconciled.</p>}</>}</div>)}<p>Open balances include retained and disputed amounts. Aging excludes those holds. Refund obligations stay separate from amounts to collect.</p>{missing>0&&<p>{missing} invoices have unassessed settlement, changed during reading or require designated contract access. A complete balance is unavailable.</p>}{warnings>0&&<p>{warnings} unresolved financial comparisons need review in invoice settlement.</p>}</>}</section>;
}
