"use client";
import { useEffect,useState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import type { ActualVersion,ContractCommand,ContractState } from "@/lib/invoicing/contracts/schema";
import { currentActuals,reconcileContract,contractMetrics,type Rollup } from "@/lib/invoicing/contracts/reconciliation";
import { ContractImportForm } from "./import-form";
import { BaselineForm } from "./baseline-form";
import { ActualForm } from "./actual-form";
import { ManagementForm } from "./management-forms";
const tabs=["Position","Baselines","Actuals","Rates","Remaining work","Billing","Snapshots"] as const;
export function ContractManagement({initial}:{initial:ContractState}) {
 const [state,setState]=useState(initial),[tab,setTab]=useState<typeof tabs[number]>("Position"),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),[pending,setPending]=useState<ContractCommand|null>(null),[correcting,setCorrecting]=useState<ActualVersion|undefined>();
 const [downloads,setDownloads]=useState<Record<string,{id:string;status:string}>>({});
 const endpoint=`/api/invoicing/engagements/${state.engagement.id}/management`,key=`contract-pending:${state.engagement.id}`,admin=state.role!=="member";
 useEffect(()=>{try{const text=localStorage.getItem(key);if(text)setPending(JSON.parse(text));}catch{setMessage("Saved request could not be read. Its browser copy has been retained.");}},[key]);
 async function reload(){const response=await fetch(endpoint,{cache:"no-store"});const body=await response.json();if(!response.ok)throw new Error(body.error??"Contract could not be reloaded");setState(body);}
 async function send(command:ContractCommand){
  setBusy(true);setMessage("");setPending(command);
  try{localStorage.setItem(key,JSON.stringify(command));const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(command)});const body=await response.json();if(!response.ok)throw new Error(body.error??"Save was not confirmed");await reload();localStorage.removeItem(key);setPending(null);setMessage(body.invoiceId?"Draft invoice prepared. Open Invoicing to review and send it.":"Saved. The retained contract record is current.");return true;}catch(error){setMessage(error instanceof Error?error.message:"Save was not confirmed. Retry the retained request.");return false;}finally{setBusy(false);}
 }
 async function report(id:string,format:"pdf"|"xlsx",prepare:boolean){setBusy(true);try{const url=`${endpoint}/reports?reportId=${id}&format=${format}`;const response=await fetch(url,{method:prepare?"POST":"GET"});const body=await response.json();if(!response.ok)throw new Error(body.error);if(prepare)setMessage("Report queued in Documents. Refresh its status when the worker finishes.");else if(body.document)setDownloads(d=>({...d,[`${id}:${format}`]:body.document}));else setMessage("Report has not been prepared yet.");}catch(e){setMessage(e instanceof Error?e.message:"Report unavailable");}finally{setBusy(false);}}
 let position:ReturnType<typeof reconcileContract>|undefined,error="";if(admin)try{position=reconcileContract(state);}catch(e){error=e instanceof Error?e.message:"Contract totals could not be reconciled";}
 function table(title:string,rows:Rollup[]){return <div><h3 className="mb-2 font-semibold">{title}</h3><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr><th className="p-2 text-left">Work</th>{contractMetrics.map(k=><th className="p-2 text-right" key={k}>{k}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><th className="p-2 text-left font-normal">{r.label}</th>{contractMetrics.map(k=><td className="p-2 text-right tabular-nums" key={k}>{r.totals[k]}</td>)}</tr>)}</tbody></table></div></div>;}
 return <main className="mx-auto max-w-6xl space-y-6 p-4 sm:p-8">
 <nav className="flex flex-wrap gap-4 text-sm"><Link className="underline" href={`/projects/${state.engagement.project_id}`}>Project</Link><Link className="underline" href={`/invoicing?direction=receivables&workspaceId=${state.engagement.workspace_id}`}>Invoicing register</Link><Link className="underline" href={`/my-work?workspaceId=${state.engagement.workspace_id}`}>My Work</Link></nav>
 <header><p className="text-sm text-muted-foreground">{state.engagement.engagement_kind.replaceAll("_"," ")}</p><h1 className="text-3xl font-semibold">{state.engagement.title}</h1><p className="mt-2 text-muted-foreground">Reconcile the approved agreement, work incurred, billing and remaining estimates.</p></header>
 {message&&<p className="rounded border p-3" role="status">{message}</p>}
 {pending&&<div className="flex flex-wrap items-center gap-3 rounded border p-3"><p className="text-sm">A retained save request is available for recovery.</p><Button disabled={busy} onClick={()=>void send(pending)}>Retry retained request</Button><Button variant="outline" disabled={busy} onClick={()=>{localStorage.removeItem(key);setPending(null);}}>Dismiss retry after review</Button></div>}
 <nav aria-label="Contract management" className="flex flex-wrap gap-2">{tabs.filter(t=>admin||["Position","Actuals"].includes(t)).map(t=><Button key={t} variant={tab===t?"default":"outline"} onClick={()=>setTab(t)}>{t}</Button>)}</nav>
 {tab==="Position"&&<section className="space-y-6">{error&&<p role="alert">{error}. No totals are asserted.</p>}{position&&<>
 <p>Current approved baseline: {position.baseline?`version ${position.baseline.version}, ${position.baseline.content.title}`:"Not yet approved"}. {position.baseline?.content.currency??"Currency unassessed"}. Totals cover approved retained sources.</p>
 <div className="grid gap-3 sm:grid-cols-3">{[["Incurred internal cost",position.total.incurred],["Gross billed before retention",position.grossBilled],["Invoice retention",position.retention],["Documented payments",position.total.payments],["Gross fee remaining",position.grossFeeRemaining],["Actual plus remaining cost",position.actualPlusRemaining]].map(([label,value])=><div key={label} className="rounded border p-4"><p className="text-sm text-muted-foreground">{label}</p><p className="text-xl tabular-nums">{value??"Unassessed"}</p></div>)}</div>
 <p className="text-sm text-muted-foreground">A live preview has no source-coverage attestation. Actual-plus-remaining cost is assessed in an issued snapshot only when every task has an estimate and all known sources are reconciled. Expenditure does not establish progress or a finish date.</p>
 {table("Task position",position.byTask)}{table("Staff position",position.byStaff)}{table("Deliverable position",position.byDeliverable)}
 <h3 className="font-semibold">Unresolved sources</h3>{position.unresolved.map(v=><p key={v.id} role={v.shared_source_stale?"alert":undefined}>{v.command.sourceKey}: {v.shared_source_stale?"The shared OWP valuation has changed. Reconcile this contract record before relying on its retained cost.":"Review valuation and allocation coverage."}</p>)}<p>{position.unresolved.length} unreviewed, unvalued or unallocated records; {state.unmappedTime.length} unmapped time records; {state.unmappedSpend.length} project spending records not mapped here; {position.unknownHours} opening balances with unknown hours.</p>
 {[...state.unmappedTime,...state.unmappedSpend].map(v=><p className="break-all text-sm" key={v.id}>{v.id} · {v.entry_date} · {"hours" in v?`${v.hours} hours`:`${v.amount} spending`}</p>)}
 </>}{!admin&&<><p>Your assigned work and draft time are available here. Private management costs remain with owners and administrators.</p>{state.baselines.filter(b=>b.state==="approved").at(-1)?.content.tasks.map(t=><div key={t.id} className="rounded border p-3"><h2 className="font-semibold">{t.title}</h2><p>{t.scope}</p><p>Agreed deadline: {t.deadline??"Unrecorded"}</p></div>)}</>}</section>}
 {tab==="Baselines"&&admin&&<section className="space-y-6"><BaselineForm key={state.baselines.at(-1)?.version??0} state={state} send={send} busy={busy}/>{state.baselines.at(-1)?.state==="proposed"&&<ManagementForm kind="approve" state={state} send={send} busy={busy}/>}<h2 className="font-semibold">Retained baseline history</h2>{state.baselines.map(b=><details key={b.id} className="rounded border p-4"><summary>Version {b.version}: {b.state} · {b.content.title}</summary><p className="mt-3 whitespace-pre-wrap">{b.content.scope}</p><p>Fee {b.content.fee??"unassessed"}; cost {b.content.cost??"unassessed"}; hours {b.content.hours??"unassessed"}</p><p>{b.approval_evidence||"No approval recorded"}</p><p className="break-all text-xs">{b.id} · {b.content_hash}</p></details>)}</section>}
 {tab==="Actuals"&&<section className="space-y-6">{admin&&<ContractImportForm state={state} onSaved={reload}/>}<ActualForm key={correcting?.id??"new"} state={state} send={send} busy={busy} correcting={correcting} onSaved={()=>setCorrecting(undefined)}/>{correcting&&<Button variant="outline" onClick={()=>setCorrecting(undefined)}>Return to new entry</Button>}<h2 className="font-semibold">Source register</h2>{currentActuals(state.actuals).map(v=><div key={v.id} className="space-y-2 rounded border p-4"><p className="font-medium">{v.command.sourceKey} · version {v.version} · {v.command.status}</p><p>{v.command.description} · {v.hours??"Unknown"} hours{admin?` · ${v.amount??"Unvalued"}`:""}</p><p className="text-sm">{v.command.sourceReference}</p><Button variant="outline" disabled={busy||(!admin&&v.command.status!=="draft")} onClick={()=>setCorrecting(v)}>Correct this record</Button></div>)}</section>}
 {tab==="Rates"&&admin&&<section className="space-y-5"><ManagementForm kind="rate" state={state} send={send} busy={busy}/>{state.rates.map(r=><p key={r.id}>{state.staff.find(s=>s.id===r.staff_id)?.name} · {r.basis} · {r.hourly_rate}/hour · {r.starts_on} to {r.ends_on} · {r.source_reference}</p>)}</section>}
 {tab==="Remaining work"&&admin&&<section className="space-y-5"><ManagementForm kind="estimate" state={state} send={send} busy={busy}/>{position?.estimates.map(e=><div key={e.task.id} className="rounded border p-3"><p>{e.task.title}: agreed deadline {e.task.deadline??"unrecorded"}</p><p>Remaining cost {e.estimate?.command.cost??"unassessed"}; hours {e.estimate?.command.hours??"unassessed"}; independent progress {e.estimate?.command.progress??"unassessed"}</p><p>{e.estimate?.command.basis}</p></div>)}</section>}
 {tab==="Billing"&&admin&&<ManagementForm kind="bill" state={state} send={send} busy={busy}/>}
 {tab==="Snapshots"&&admin&&<section className="space-y-5"><ManagementForm kind="snapshot" state={state} send={send} busy={busy}/>{state.snapshots.map(r=><div key={r.id} className="space-y-3 rounded border p-4"><h2 className="font-semibold">{r.title}</h2><p>{r.created_at}</p>{(["pdf","xlsx"] as const).map(format=><div className="flex flex-wrap gap-3" key={format}><Button variant="outline" disabled={busy} onClick={()=>void report(r.id,format,true)}>Prepare {format.toUpperCase()}</Button><Button variant="outline" disabled={busy} onClick={()=>void report(r.id,format,false)}>Refresh {format.toUpperCase()} status</Button>{downloads[`${r.id}:${format}`]?.status==="stored"&&<a className="underline" href={`/api/knowledge-base/documents/${downloads[`${r.id}:${format}`].id}/download`}>Download {format.toUpperCase()}</a>}</div>)}</div>)}</section>}
 </main>;
}
