"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import type { ContractState } from "@/lib/invoicing/contracts/schema";
import type { Schedule, WorkingCalendar, WorkUpdateVersion } from "@/lib/invoicing/contracts/delivery-schema";
import { forecastDelivery } from "@/lib/invoicing/contracts/delivery";
import { Field,inputClass,TextField,NoteField,useRetainedDraft,type CommandSender } from "./fields";
const today=()=>new Date().toISOString().slice(0,10);
const calendar=():WorkingCalendar=>({name:"Explicit Monday–Friday calendar; edit to match this assignment",weekdays:[1,2,3,4,5],exceptions:[]});
const val=(d:FormData,k:string)=>String(d.get(k)??"");
function CalendarEditor({value,onChange}:{value:WorkingCalendar;onChange:(c:WorkingCalendar)=>void}){
 return <fieldset className="space-y-2 rounded border p-3"><legend>Working calendar</legend><TextField label="Calendar description" value={value.name} onChange={name=>onChange({...value,name})}/><div className="flex flex-wrap gap-3">{["Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"].map((day,i)=><label key={day}><input type="checkbox" checked={value.weekdays.includes(i)} onChange={e=>onChange({...value,weekdays:e.target.checked?[...value.weekdays,i].sort():value.weekdays.filter(v=>v!==i)})}/> {day}</label>)}</div><p className="text-sm">No holidays or outside review requirements are assumed. Add dated exceptions from your working arrangements.</p>{value.exceptions.map((e,i)=><div className="grid gap-2 sm:grid-cols-3" key={i}><TextField type="date" label="Exception date" value={e.date} onChange={date=>onChange({...value,exceptions:value.exceptions.map((v,n)=>n===i?{...v,date}:v)})}/><TextField label="Exception reason" value={e.reason} onChange={reason=>onChange({...value,exceptions:value.exceptions.map((v,n)=>n===i?{...v,reason}:v)})}/><label><input type="checkbox" checked={e.working} onChange={event=>onChange({...value,exceptions:value.exceptions.map((v,n)=>n===i?{...v,working:event.target.checked}:v)})}/> Working day</label><Button type="button" variant="outline" onClick={()=>onChange({...value,exceptions:value.exceptions.filter((_,n)=>n!==i)})}>Remove exception</Button></div>)}<Button type="button" variant="outline" onClick={()=>onChange({...value,exceptions:[...value.exceptions,{date:today(),working:false,reason:""}]})}>Add dated exception</Button></fieldset>;
}
function ScheduleEditor({state,send,busy}:{state:ContractState;send:CommandSender;busy:boolean}){
 const latest=state.delivery?.scheduleVersions.at(-1),tasks=state.baselines.filter(b=>b.state==="approved").at(-1)?.content.tasks??[];
 const draft=useRetainedDraft<Schedule>(`contract-schedule:${state.engagement.id}:${latest?.version??0}`,latest?.content??{nodes:[],updateDueOn:today(),billingTreatment:"unassessed",billingSourceId:null,billingEvidence:"",assumptions:""}),schedule=draft.value;
 function node(i:number,patch:Partial<Schedule["nodes"][number]>){draft.setValue({...schedule,nodes:schedule.nodes.map((n,index)=>index===i?{...n,...patch}:n)});}
 return <form className="space-y-4" onSubmit={async e=>{e.preventDefault();await send({kind:"schedule",requestId:crypto.randomUUID(),expectedVersion:latest?.version??0,content:schedule});}}><h3 className="font-semibold">Work and review sequence</h3><p>These are working expectations. Approved agreement dates and budgets change only through a baseline approval.</p>{draft.error&&<p role="alert">{draft.error}</p>}<NoteField label="Schedule assumptions and proposed sequencing" value={schedule.assumptions} onChange={assumptions=>draft.setValue({...schedule,assumptions})} required/><TextField label="Staff update required as of" type="date" value={schedule.updateDueOn} onChange={updateDueOn=>draft.setValue({...schedule,updateDueOn})}/>
 {schedule.nodes.map((n,i)=><fieldset className="space-y-3 rounded border p-4" key={n.id}><legend>Schedule item {i+1}</legend><TextField label="Schedule item title" value={n.title} onChange={title=>node(i,{title})} required/><Field label="Approved contract task"><select className={inputClass} value={n.taskId} onChange={e=>node(i,{taskId:e.target.value})} required><option value="">Select task</option>{tasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></Field><Field label="Schedule item type"><select className={inputClass} value={n.kind} onChange={e=>node(i,{kind:e.target.value as typeof n.kind,staff:[]})}><option value="work">Staff work</option><option value="client_review">Client review</option><option value="agency_review">Agency review</option><option value="public_review">Public review</option></select></Field><div className="grid gap-3 sm:grid-cols-2"><TextField label="Earliest expected start" type="date" value={n.notBefore} onChange={notBefore=>node(i,{notBefore})}/><TextField label="Reserve capacity through" type="date" value={n.reserveThrough} onChange={reserveThrough=>node(i,{reserveThrough})}/></div>
 <Field label="Finish-to-start predecessors"><select className={inputClass} multiple value={n.predecessors} onChange={e=>node(i,{predecessors:Array.from(e.target.selectedOptions,o=>o.value)})}>{schedule.nodes.filter(other=>other.id!==n.id).map(other=><option key={other.id} value={other.id}>{other.title||"Untitled item"}</option>)}</select></Field><CalendarEditor value={n.calendar} onChange={c=>node(i,{calendar:c})}/>
 {n.kind==="work"?<><p>Reserve daily hours explicitly. Staff submit remaining effort below. Reservations are checked against other active assignments.</p>{n.staff.map((person,j)=><div className="grid gap-3 sm:grid-cols-2" key={j}><Field label="Scheduled staff"><select className={inputClass} value={person.staffId} onChange={e=>node(i,{staff:n.staff.map((p,index)=>index===j?{...p,staffId:e.target.value}:p)})} required><option value="">Select staff</option>{state.staff.filter(p=>p.active).map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></Field><TextField label="Reserved hours per working day" value={person.hoursPerDay} onChange={hoursPerDay=>node(i,{staff:n.staff.map((p,index)=>index===j?{...p,hoursPerDay}:p)})}/><Button type="button" variant="outline" onClick={()=>node(i,{staff:n.staff.filter((_,index)=>index!==j)})}>Remove reservation</Button></div>)}<Button type="button" variant="outline" onClick={()=>node(i,{staff:[...n.staff,{staffId:"",hoursPerDay:""}]})}>Reserve staff time</Button></>:<><Field label="Outside reviewer availability"><select className={inputClass} value={n.reviewStatus} onChange={e=>node(i,{reviewStatus:e.target.value as typeof n.reviewStatus})}><option value="unassessed">Unassessed</option><option value="available">Available from expected start</option><option value="unavailable">Unavailable</option></select></Field><TextField label="Required review duration, days; blank if unknown" value={n.durationDays===null?null:String(n.durationDays)} onChange={v=>node(i,{durationDays:v===""?null:Number(v)})}/><Field label="Review duration counting"><select className={inputClass} value={n.durationKind} onChange={e=>node(i,{durationKind:e.target.value as "working"|"calendar"})}><option value="working">Working days</option><option value="calendar">Calendar days</option></select></Field><NoteField label="Source for review duration and responsible reviewer" value={n.reviewEvidence} onChange={reviewEvidence=>node(i,{reviewEvidence})}/></>}
 <Button type="button" variant="outline" onClick={()=>draft.setValue({...schedule,nodes:schedule.nodes.filter((_,index)=>index!==i)})}>Remove schedule item</Button></fieldset>)}
 <Button type="button" variant="outline" onClick={()=>draft.setValue({...schedule,nodes:[...schedule.nodes,{id:crypto.randomUUID(),taskId:tasks[0]?.id??"",title:"",kind:"work",notBefore:today(),reserveThrough:today(),predecessors:[],calendar:calendar(),durationDays:null,durationKind:"working",reviewEvidence:"",reviewStatus:"unassessed",staff:[]}]})}>Add work or review period</Button>
 <Field label="Agreement treatment for expected billing"><select className={inputClass} value={schedule.billingTreatment} onChange={e=>draft.setValue({...schedule,billingTreatment:e.target.value as Schedule["billingTreatment"]})}><option value="unassessed">Unassessed</option><option value="fixed_fee">Fixed fee; separate from incurred cost</option><option value="time_materials">Documented time and materials</option></select></Field><Field label="Retained billing agreement source"><select className={inputClass} value={schedule.billingSourceId??""} onChange={e=>draft.setValue({...schedule,billingSourceId:e.target.value||null})}><option value="">Unassessed</option>{state.documents.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></Field><NoteField label="Evidence supporting expected gross billing" value={schedule.billingEvidence} onChange={billingEvidence=>draft.setValue({...schedule,billingEvidence})}/><Button disabled={busy}>Retain reviewed working schedule</Button></form>;
}
function CapacityEditor({state,send,busy}:{state:ContractState;send:CommandSender;busy:boolean}){
 const [working,setWorking]=useState(calendar());
 return <form className="space-y-3" onSubmit={async e=>{e.preventDefault();const d=new FormData(e.currentTarget),staffId=val(d,"staffId");await send({kind:"capacity",requestId:crypto.randomUUID(),expectedVersion:Math.max(0,...(state.delivery?.capacityVersions??[]).filter(c=>c.staff_id===staffId).map(c=>c.version)),content:{staffId,startsOn:val(d,"startsOn"),endsOn:val(d,"endsOn"),hoursPerDay:val(d,"hoursPerDay"),calendar:working,evidence:val(d,"evidence")}});}}><h3 className="font-semibold">Shared staff availability</h3><p>This dated availability applies across assignments. Another PM can see reserved hours without confidential project details. Reusing a start date replaces that period prospectively; earlier versions remain retained.</p><Field label="Availability staff"><select name="staffId" className={inputClass} required><option value="">Select staff</option>{state.staff.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field>{([['startsOn','Availability start','date'],['endsOn','Availability end','date'],['hoursPerDay','Available hours per working day','text'],['evidence','Availability evidence','text']] as const).map(([name,label,type])=><Field key={name} label={label}><input className={inputClass} name={name} type={type} required/></Field>)}<CalendarEditor value={working} onChange={setWorking}/><Button disabled={busy}>Retain dated availability</Button>{state.delivery?.capacityVersions.map(c=><p key={c.id}>{state.staff.find(s=>s.id===c.staff_id)?.name??"Assigned staff"}: {c.content.startsOn}–{c.content.endsOn}, {c.content.hoursPerDay} hours/day, version {c.version}. {c.content.evidence}</p>)}</form>;
}
function WorkUpdates({state,send,busy}:{state:ContractState;send:CommandSender;busy:boolean}){
 const updates=state.delivery?.workUpdates??[],latest=new Map<string,WorkUpdateVersion>();for(const u of updates.toSorted((a,b)=>a.version-b.version))latest.set(`${u.task_id}:${u.staff_id}`,u);
 const tasks=state.baselines.filter(b=>b.state==="approved").at(-1)?.content.tasks??[],manager=["owner","admin","pm","finance"].includes(state.role);
 return <section className="space-y-4"><form className="space-y-3" onSubmit={async e=>{e.preventDefault();const d=new FormData(e.currentTarget),taskId=val(d,"taskId"),staffId=val(d,"staffId");await send({kind:"work_update",requestId:crypto.randomUUID(),expectedVersion:latest.get(`${taskId}:${staffId}`)?.version??0,content:{taskId,staffId,asOf:val(d,"asOf"),hours:val(d,"hours")||null,availableHoursPerDay:val(d,"availableHoursPerDay")||null,status:val(d,"status") as "not_started"|"in_progress"|"blocked"|"reported_complete",actualStart:val(d,"actualStart")||null,actualFinish:val(d,"actualFinish")||null,blockers:val(d,"blockers"),evidence:val(d,"evidence")}});}}><h3 className="font-semibold">Submit remaining work</h3><p>Your PM reviews this exact version. Reporting completion does not accept a deliverable or settle the contract.</p><Field label="Update task"><select className={inputClass} name="taskId" required>{tasks.map(t=><option value={t.id} key={t.id}>{t.title}</option>)}</select></Field><Field label="Update staff"><select className={inputClass} name="staffId" required>{state.staff.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field>{([['asOf','Remaining-work as-of date','date'],['hours','Remaining hours, blank if unknown','text'],['availableHoursPerDay','Expected available hours per day','text'],['actualStart','Reported actual start','date'],['actualFinish','Reported actual finish','date']] as const).map(([name,label,type])=><Field key={name} label={label}><input className={inputClass} name={name} type={type} defaultValue={name==="asOf"?today():undefined} required={name==="asOf"}/></Field>)}<Field label="Delivery status"><select className={inputClass} name="status"><option value="not_started">Not started</option><option value="in_progress">In progress</option><option value="blocked">Blocked</option><option value="reported_complete">Staff reports work complete</option></select></Field><Field label="Blockers and unavailable reviewers"><textarea name="blockers" className={inputClass}/></Field><Field label="Remaining-work explanation"><textarea name="evidence" className={inputClass} required/></Field><Button disabled={busy}>Submit for PM review</Button></form>
 {[...latest.values()].map(u=><article className="space-y-3 rounded border p-4" key={u.id} id={`work-update-${u.id}`}><h3 className="font-semibold">{tasks.find(t=>t.id===u.task_id)?.title??"Retained task"} · {state.staff.find(s=>s.id===u.staff_id)?.name??"Staff"}</h3><p>{u.state}, version {u.version}; {u.content.asOf}; {u.content.hours??"Unknown"} hours remaining; availability {u.content.availableHoursPerDay??"unassessed"}/day.</p><p>{u.content.status}: {u.content.blockers} {u.content.evidence}</p><p>{u.evidence}</p>{manager&&u.state==="submitted"&&<form className="space-y-3" onSubmit={async e=>{e.preventDefault();const d=new FormData(e.currentTarget);await send({kind:"work_review",requestId:crypto.randomUUID(),expectedVersion:u.version,updateId:u.id,state:val(d,"state") as "accepted"|"returned",remainingCost:val(d,"remainingCost")||null,remainingGrossBilling:val(d,"remainingGrossBilling")||null,valuationEvidence:val(d,"valuationEvidence"),evidence:val(d,"evidence")});}}><Field label="PM work-review decision"><select className={inputClass} name="state"><option value="accepted">Accept this version</option><option value="returned">Return for correction</option></select></Field>{([['remainingCost','Reviewed remaining internal cost'],['remainingGrossBilling','Expected remaining gross billing, if supported'],['valuationEvidence','Valuation assumptions and source'],['evidence','PM review evidence']] as const).map(([name,label])=><Field key={name} label={label}><input className={inputClass} name={name} required={name==="evidence"}/></Field>)}<Button disabled={busy}>Retain exact work review</Button></form>}</article>)}
 <details><summary>Retained update history</summary>{updates.map(u=><div className="space-y-1 border-t p-3" key={u.id} id={`work-history-${u.id}`}><p>{tasks.find(t=>t.id===u.task_id)?.title??"Retained task"}: {u.state}, version {u.version}, {u.created_at}</p><p>{u.content.evidence} {u.evidence}</p>{u.reviewed_update_id&&<a className="underline" href={`#work-history-${u.reviewed_update_id}`}>Exact submitted version reviewed</a>}</div>)}</details>
 </section>;
}
function Forecasts({state,send,busy}:{state:ContractState;send:CommandSender;busy:boolean}){
 const [preview,setPreview]=useState<ReturnType<typeof forecastDelivery>|null>(null),[error,setError]=useState("");
 return <section className="space-y-4"><form className="space-y-3" onSubmit={async e=>{e.preventDefault();const d=new FormData(e.currentTarget),options={asOf:val(d,"asOf"),horizonEnd:val(d,"horizonEnd"),coverageComplete:d.get("coverageComplete")==="on"};try{const r=forecastDelivery(state,state.delivery!,options);setPreview(r);setError("");if(val(d,"reviewEvidence"))await send({kind:"forecast",requestId:crypto.randomUUID(),...options,coverageEvidence:val(d,"coverageEvidence"),reviewEvidence:val(d,"reviewEvidence")});}catch(e){setError(e instanceof Error?e.message:"Forecast unavailable");}}}><h3 className="font-semibold">Explainable forecast</h3>{([['asOf','Forecast as-of date'],['horizonEnd','Forecast horizon end']] as const).map(([name,label])=><Field key={name} label={label}><input className={inputClass} name={name} type="date" defaultValue={name==="asOf"?today():undefined} required/></Field>)}<label className="block"><input name="coverageComplete" type="checkbox"/> Reviewed incurred-cost source coverage is complete</label><Field label="Source coverage evidence"><textarea name="coverageEvidence" className={inputClass} required/></Field><Field label="Forecast review evidence; leave blank for preview"><textarea name="reviewEvidence" className={inputClass}/></Field><Button disabled={busy}>Calculate or retain reviewed forecast</Button></form>{error&&<p role="alert">{error}</p>}{preview&&<ForecastTable result={preview}/>}{state.delivery?.forecasts.toReversed().map(f=><article className="space-y-3 rounded border p-4" key={f.id}><h3 className="font-semibold">Reviewed forecast {f.version}</h3><p>{f.input_hash===state.delivery?.inputHash?"Inputs unchanged since review":"Stale: inputs changed after review"}. {f.created_at}</p><p>{f.content.reviewEvidence}</p><ForecastTable result={f.content.result}/></article>)}</section>;
}
export function ForecastTable({result}:{result:ReturnType<typeof forecastDelivery>}){
 return <div className="space-y-3"><p>Supported finish: {result.finish??"Unassessed"}; remaining cost {result.remainingCost??"unassessed"}; actual plus remaining {result.actualPlusRemaining??"unassessed"}; expected remaining gross billing {result.remainingGrossBilling??"unassessed"}.</p><div className="overflow-x-auto"><table className="w-full text-sm"><caption className="text-left">Reviewed schedule expectations and separate approved dates</caption><thead><tr>{["Work or review","Original approved finish","Current approved finish","Forecast start","Forecast finish","Actual start","Actual finish"].map(h=><th className="p-2 text-left" key={h}>{h}</th>)}</tr></thead><tbody>{result.nodes.map(n=><tr className="border-t" key={n.id}><th className="p-2 text-left">{n.title}</th>{[n.originalApprovedFinish,n.currentApprovedFinish,n.start,n.finish,n.actualStart,n.actualFinish].map((d,i)=><td className="p-2" key={i}>{d??"Unassessed"}</td>)}</tr>)}</tbody></table></div>{result.warnings.map((w,i)=><p className="rounded border p-3" key={i}>{result.nodes.find(n=>n.id===w.nodeId)?.title}{w.date?` · ${w.date}`:""}: {w.message}</p>)}</div>;
}
export function DeliveryManagement(props:{state:ContractState;send:CommandSender;busy:boolean}){
 const [section,setSection]=useState("Updates"),manager=["owner","admin","pm","finance"].includes(props.state.role);
 if(!props.state.delivery)return <p>Remaining-work review is unavailable until this installation is updated.</p>;
 return <section className="space-y-5" id="delivery"><nav className="flex flex-wrap gap-2" aria-label="Remaining-work management">{(manager?["Updates","Schedule","Capacity","Forecasts"]:["Updates"]).map(s=><Button key={s} variant={section===s?"default":"outline"} onClick={()=>setSection(s)}>{s}</Button>)}</nav>{section==="Updates"&&<WorkUpdates {...props}/>} {section==="Schedule"&&manager&&<ScheduleEditor key={props.state.delivery.scheduleVersions.at(-1)?.version??0} {...props}/>} {section==="Capacity"&&manager&&<CapacityEditor {...props}/>} {section==="Forecasts"&&manager&&<Forecasts {...props}/>}</section>;
}
