"use client";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Field,inputClass,type CommandSender } from "./fields";
import { ForecastTable } from "./delivery-management";
import type { ContractState } from "@/lib/invoicing/contracts/schema";
import type { ResponseCommand } from "@/lib/invoicing/contracts/response-schema";
const value=(d:FormData,k:string)=>String(d.get(k)??"");
export function ManagementResponses({state,send,busy}:{state:ContractState;send:CommandSender;busy:boolean}){
 const forecast=state.delivery?.forecasts.at(-1),schedule=state.delivery?.scheduleVersions.at(-1),tasks=state.baselines.filter(b=>b.state==="approved").at(-1)?.content.tasks??[];
 return <section className="space-y-5"><h3 className="text-lg font-semibold">Weekly PM responses</h3><p><Link className="underline" href={`/projects/${state.engagement.project_id}?tab=record`}>Open the project risk, issue or decision</Link>, then retain its exact version with this comparison. Use Schedule to compare revised sequencing, staff reservations or review periods. Approved fee, scope and dates change through Baselines.</p><form className="space-y-3 rounded border p-4" onSubmit={async e=>{e.preventDefault();if(!forecast||!schedule)return;const d=new FormData(e.currentTarget),record=state.responses?.records.find(r=>r.id===value(d,"record"));if(!record)return;const taskId=value(d,"task"),staffId=value(d,"staff"),workAssumptions:ResponseCommand["workAssumptions"]=taskId&&staffId?[{update:{taskId,staffId,asOf:forecast.content.result.asOf,hours:value(d,"hours")||null,availableHoursPerDay:value(d,"available")||null,status:"in_progress",actualStart:null,actualFinish:null,blockers:value(d,"blockers"),evidence:value(d,"evidence")},remainingCost:value(d,"cost")||null,remainingGrossBilling:value(d,"billing")||null,valuationEvidence:value(d,"valuation")}]:[];await send({kind:"response",requestId:crypto.randomUUID(),forecastId:forecast.id,recordId:record.id,recordType:record.recordType,recordUpdatedAt:record.updated_at,recordHash:record.recordHash,schedule:schedule.content,workAssumptions,evidence:value(d,"evidence")});}}><h4 className="font-semibold">Compare added or revised remaining effort</h4><p>These are proposed PM assumptions. Applying a response updates the working schedule only. Staff must submit and PMs must review changed effort before a subsequent forecast can rely on it.</p><Field label="Response project decision"><select name="record" className={inputClass} required><option value="">Select risk, issue or decision</option>{state.responses?.records.map(r=><option key={r.id} value={r.id}>{r.recordType}: {r.title}</option>)}</select></Field><Field label="Response task"><select name="task" className={inputClass} required><option value="">Select task</option>{tasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></Field><Field label="Response staff"><select name="staff" className={inputClass} required><option value="">Select staff</option>{state.staff.filter(s=>s.active).map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field>{([['hours','Assumed remaining hours'],['available','Assumed available hours per day'],['cost','Assumed remaining internal cost'],['billing','Assumed remaining gross billing'],['blockers','Assumed blockers'],['valuation','Assumption valuation basis'],['evidence','Response explanation']] as const).map(([name,label])=><Field key={name} label={label}><input name={name} className={inputClass} required={name==="valuation"||name==="evidence"}/></Field>)}<Button disabled={busy||!forecast}>Retain proposed effort comparison</Button></form>
 {state.responses?.responses.toReversed().map(r=><article className="space-y-3 rounded border p-4" key={r.id}><h4 className="font-semibold">{r.content.record.title}</h4><p>{r.content.request.evidence}</p><p>{r.created_at}; {r.input_hash===state.delivery?.inputHash?"Comparison inputs unchanged":"Stale comparison; inputs changed"}</p><details><summary>Current reviewed forecast</summary><ForecastTable result={r.content.before}/></details><details open><summary>Proposed response outcome</summary><ForecastTable result={r.content.after}/></details>{state.responses?.applications.some(a=>a.response_id===r.id)?<p>Working response applied. Contractual approval and staff work reviews remain separate.</p>:<form onSubmit={async e=>{e.preventDefault();await send({kind:"apply_response",requestId:crypto.randomUUID(),responseId:r.id,expectedVersion:schedule?.version??0,evidence:value(new FormData(e.currentTarget),"evidence")});}} className="space-y-3"><Field label="Working response decision evidence"><input name="evidence" className={inputClass} required/></Field><Button disabled={busy||r.input_hash!==state.delivery?.inputHash}>Apply proposed working schedule</Button></form>}</article>)}
 </section>;
}
