"use client";
import { Button } from "@/components/ui/button";
import type { ContractCommand,ContractState } from "@/lib/invoicing/contracts/schema";
import { currentActuals } from "@/lib/invoicing/contracts/reconciliation";
import { Field,inputClass,type CommandSender } from "./fields";
const value=(data:FormData,key:string)=>String(data.get(key)??"");
export function ManagementForm({kind,state,send,busy}:{kind:"rate"|"estimate"|"bill"|"snapshot"|"approve";state:ContractState;send:CommandSender;busy:boolean}) {
 const baseline=state.baselines.filter(b=>b.state==="approved").at(-1),latest=state.baselines.at(-1);
 async function submit(form:HTMLFormElement){
  const data=new FormData(form),requestId=crypto.randomUUID();let command:ContractCommand;
  if(kind==="rate")command={kind,requestId,rateId:crypto.randomUUID(),staffId:value(data,"staffId"),basis:value(data,"basis") as "cost"|"billing",startsOn:value(data,"startsOn"),endsOn:value(data,"endsOn"),hourlyRate:value(data,"hourlyRate"),sourceReference:value(data,"sourceReference")};
  else if(kind==="estimate"){const taskId=value(data,"taskId");command={kind,requestId,expectedVersion:state.estimates.filter(e=>e.task_id===taskId).at(-1)?.version??0,taskId,asOf:value(data,"asOf"),hours:value(data,"hours")||null,cost:value(data,"cost")||null,basis:value(data,"basis"),progress:value(data,"progress")===""?null:Number(value(data,"progress")),progressNote:value(data,"progressNote")};}
  else if(kind==="bill")command={kind,requestId,invoiceNumber:value(data,"invoiceNumber"),invoiceDate:value(data,"invoiceDate"),dueDate:value(data,"dueDate")||null,retentionPercent:value(data,"retentionPercent"),entryIds:data.getAll("entryIds").map(String)};
  else if(kind==="approve")command={kind,requestId,baselineId:latest!.id,expectedVersion:latest!.version,approvalEvidence:value(data,"approvalEvidence")};
  else command={kind,requestId,title:value(data,"title"),asOf:value(data,"asOf"),sourceCutoff:new Date().toISOString(),coverageComplete:data.get("coverageComplete")==="on",coverageEvidence:value(data,"coverageEvidence")};
  await send(command);
 }
 const field=(name:string,label:string,type="text",required=true,defaultValue?:string)=><Field label={label}><input name={name} className={inputClass} type={type} required={required} defaultValue={defaultValue}/></Field>;
 const note=(name:string,label:string)=><Field label={label}><textarea name={name} className={inputClass} rows={3} required/></Field>;
 return <form className="space-y-4" onSubmit={e=>{e.preventDefault();void submit(e.currentTarget);}}>
 {kind==="approve"&&<><p>Approve proposal {latest?.version}: {latest?.content.title}. Its scope, source documents and budgets are retained below.</p>{note("approvalEvidence","Evidence of the responsible person's approval")}<Button disabled={busy||latest?.state!=="proposed"}>Record baseline approval</Button></>}
 {kind==="rate"&&<><p className="text-sm">Cost and client billing rates have separate effective periods. Retained rates cannot be overwritten.</p><Field label="Staff"><select required className={inputClass} name="staffId"><option value="">Select staff</option>{state.staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></Field><Field label="Rate meaning"><select className={inputClass} name="basis"><option value="cost">Private internal cost</option><option value="billing">Client billing fee</option></select></Field><div className="grid gap-3 sm:grid-cols-2">{field("startsOn","Effective start","date")}{field("endsOn","Effective end","date")}</div>{field("hourlyRate","Exact hourly rate")}{note("sourceReference","Approved rate source reference")}<Button disabled={busy}>Retain approved rate</Button></>}
 {kind==="estimate"&&<><p className="text-sm">Estimate remaining work independently of expenditure. Agreed deadlines remain visible; this does not infer a finish date.</p><Field label="Task"><select required className={inputClass} name="taskId"><option value="">Select task</option>{baseline?.content.tasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></Field>{field("asOf","Estimate date","date")}<div className="grid gap-3 sm:grid-cols-2">{field("hours","Remaining hours","text",false)}{field("cost","Remaining internal cost","text",false)}</div>{note("basis","Remaining-work estimate basis")}{field("progress","Independent deliverable progress, percent","number",false)}{note("progressNote","Progress and outstanding review evidence")}<Button disabled={busy}>Retain dated estimate</Button></>}
 {kind==="bill"&&<><p className="text-sm">Prepare a draft invoice from reviewed, billable sources. Each task split retains its attribution. Send the draft from Invoicing.</p>{field("invoiceNumber","Invoice number")}{field("invoiceDate","Invoice date","date")}{field("dueDate","Payment due date","date",false)}{field("retentionPercent","Retention percent","text",true,"0.00")}<fieldset className="space-y-2"><legend>Reviewed billable sources</legend>{currentActuals(state.actuals).filter(v=>v.command.status==="approved"&&v.command.billable&&["labor","expense"].includes(v.command.category)).map(v=><label className="flex gap-2 text-sm" key={v.id}><input type="checkbox" name="entryIds" value={v.entry_id}/>{v.command.sourceKey}: {v.command.description}</label>)}</fieldset><Button disabled={busy}>Prepare source-attributed invoice</Button></>}
 {kind==="snapshot"&&<><p className="text-sm">Freeze the current retained records and approval history into an immutable internal management snapshot. Incomplete sources remain visible.</p>{field("title","Snapshot title")}{field("asOf","Management as-of date","date")}<label className="flex gap-2 text-sm"><input type="checkbox" name="coverageComplete"/>I have reconciled source coverage through this date.</label>{note("coverageEvidence","Coverage evidence and unresolved source boundaries")}<Button disabled={busy||!baseline}>Issue internal management snapshot</Button></>}
 </form>;
}
