"use client";
import type { ContractState } from "@/lib/invoicing/contracts/schema";
import { Button } from "@/components/ui/button";
import { Field, inputClass, type CommandSender } from "./fields";

export function MasterTermsPanel({state,send,busy}:{state:ContractState;send:CommandSender;busy:boolean}) {
 const versions=state.masterTerms??[],latest=versions.at(-1),approved=versions.filter(t=>t.state==="approved").at(-1);
 if(state.engagement.parent_engagement_id)return <section className="space-y-2 rounded border p-4"><h2 className="font-semibold">Master authorization</h2>{state.parentMasterTerms?<p>Shared ceiling {state.parentMasterTerms.ceiling} {state.parentMasterTerms.currency}; authorized {state.parentMasterTerms.starts_on} through {state.parentMasterTerms.ends_on}. Approval checks all task orders together.</p>:<p>Master terms are unassessed. Retain and approve the master agreement terms before authorizing this task order.</p>}<a className="underline" href={`/invoicing/engagements/${state.engagement.parent_engagement_id}`}>Manage master agreement</a></section>;
 return <section className="space-y-4"><h2 className="text-xl font-semibold">Master agreement authorization</h2><p>{approved?`Approved shared ceiling ${approved.ceiling} ${approved.currency}, ${approved.starts_on} through ${approved.ends_on}.`:"No shared ceiling is approved. Use this section when this agreement authorizes task orders."}</p>
 <form className="space-y-3" onSubmit={async e=>{e.preventDefault();const d=new FormData(e.currentTarget),v=(k:string)=>String(d.get(k)??"");await send({kind:"master_terms",requestId:crypto.randomUUID(),termsId:crypto.randomUUID(),expectedVersion:latest?.version??0,currency:v("currency"),ceiling:v("ceiling"),startsOn:v("startsOn"),endsOn:v("endsOn"),terms:v("terms"),sourceDocumentId:v("sourceDocumentId")});}}>
 <div className="grid gap-3 sm:grid-cols-2">{([['ceiling','Shared maximum','text'],['currency','Currency code','text'],['startsOn','Master authorized start','date'],['endsOn','Master authorized end','date']] as const).map(([name,label,type])=><Field key={name} label={label}><input className={inputClass} name={name} type={type} required defaultValue={name==="currency"?approved?.currency:undefined}/></Field>)}</div>
 <Field label="Master terms and source interpretation"><textarea name="terms" className={inputClass} rows={3} required/></Field><Field label="Retained master agreement"><select name="sourceDocumentId" className={inputClass} required><option value="">Select document</option>{state.documents.map(d=><option value={d.id} key={d.id}>{d.title}</option>)}</select></Field><Button disabled={busy}>Propose master terms</Button></form>
 {latest?.state==="proposed"&&<form className="space-y-3 rounded border p-4" onSubmit={async e=>{e.preventDefault();await send({kind:"approve_master_terms",requestId:crypto.randomUUID(),termsId:latest.id,expectedVersion:latest.version,approvalEvidence:String(new FormData(e.currentTarget).get("approvalEvidence")??"")});}}><p>Proposal {latest.version}: {latest.ceiling} {latest.currency}, {latest.starts_on} through {latest.ends_on}. {latest.terms}</p><Field label="Master approval evidence"><textarea className={inputClass} name="approvalEvidence" required/></Field><Button disabled={busy}>Confirm master terms approval</Button></form>}
 <form className="space-y-3 rounded border p-4" onSubmit={async e=>{e.preventDefault();const d=new FormData(e.currentTarget);await send({kind:"task_order",requestId:crypto.randomUUID(),engagementId:crypto.randomUUID(),projectId:state.engagement.project_id,title:String(d.get("title")??"")});}}><h3 className="font-semibold">Create a task order for this project</h3><Field label="Task order title"><input name="title" className={inputClass} required/></Field><Button disabled={busy}>Create linked task order</Button></form>
 {(state.taskOrders??[]).map(t=><p key={t.id}><a className="underline" href={`/invoicing/engagements/${t.id}`}>{t.title}</a></p>)}
 {versions.map(t=><details className="rounded border p-3" key={t.id}><summary>Master terms version {t.version}: {t.state}</summary><p>{t.ceiling} {t.currency}; {t.starts_on} through {t.ends_on}</p><p>{t.terms}</p><p>{t.approval_evidence||"No approval recorded"}</p></details>)}
 </section>;
}
