import os
import time
import requests
from dotenv import load_dotenv

load_dotenv('../../openplan/.env.local')

SUPABASE_URL = os.getenv('NEXT_PUBLIC_SUPABASE_URL')
SUPABASE_KEY = os.getenv('SUPABASE_SERVICE_ROLE_KEY')

if not SUPABASE_URL or not SUPABASE_KEY:
    raise ValueError("Missing Supabase credentials in environment.")

HEADERS = {
    "apikey": SUPABASE_KEY,
    "Authorization": f"Bearer {SUPABASE_KEY}",
    "Content-Type": "application/json",
    "Prefer": "return=representation"
}

def poll_for_jobs():
    print("AequilibraE Worker Prototype started. Polling for queued stages...")
    while True:
        try:
            # Poll queued stages
            # GET /rest/v1/model_run_stages?status=eq.queued&order=run_id.asc,sort_order.asc&limit=1
            url = f"{SUPABASE_URL}/rest/v1/model_run_stages?status=eq.queued&order=run_id.asc,sort_order.asc&limit=1"
            res = requests.get(url, headers=HEADERS)
            if res.status_code != 200:
                print(f"Error fetching stages: {res.text}")
                time.sleep(5)
                continue

            stages = res.json()
            if not stages:
                time.sleep(5)
                continue

            stage = stages[0]
            stage_id = stage['id']
            run_id = stage['run_id']
            stage_name = stage['stage_name']

            print(f"[{time.strftime('%X')}] Found queued stage: {stage_name} (Run ID: {run_id})")

            # Claim the stage
            patch_url = f"{SUPABASE_URL}/rest/v1/model_run_stages?id=eq.{stage_id}"
            claim_data = {
                "status": "running",
                "log_tail": "Worker claimed job. Initializing AequilibraE environment..."
            }
            # We skip 'started_at' right now because it's a bit strict with formatting in simple payloads, but we could use a datetime.
            
            res_claim = requests.patch(patch_url, headers=HEADERS, json=claim_data)
            if res_claim.status_code not in (200, 204):
                print(f"Failed to claim stage: {res_claim.text}")
                continue

            # Update the run status if it's not already running
            requests.patch(f"{SUPABASE_URL}/rest/v1/model_runs?id=eq.{run_id}", headers=HEADERS, json={"status": "running"})

            # Execute Mock Work
            print(f"Executing {stage_name}...")
            time.sleep(3) # simulate work
            log_tail = f"AequilibraE environment initialized.\nExecuting {stage_name} operations...\n"
            
            requests.patch(patch_url, headers=HEADERS, json={"log_tail": log_tail + 'In progress...'})
            
            time.sleep(4) # simulate more work
            
            # Create a mock artifact for "Artifact Extraction" stage
            if stage_name == "Artifact Extraction":
                # Mock file upload skipped for prototype simplicity
                artifact_content = b"Mock OMX skim matrix data"
                post_url = f"{SUPABASE_URL}/rest/v1/model_run_artifacts"
                requests.post(post_url, headers=HEADERS, json={
                    'run_id': run_id,
                    'stage_id': stage_id,
                    'artifact_type': 'skim_matrix',
                    'file_url': f"mock-storage-path/{run_id}/skims.omx",
                    'file_size_bytes': len(artifact_content),
                    'content_hash': 'abcdef123456',
                    'metadata_json': {'description': 'Mock Skim Matrix generated by AequilibraE Worker'}
                })
                log_tail += "Generated skim_matrix artifact.\n"

            log_tail += "Completed successfully.\n"

            # Complete the stage
            res_complete = requests.patch(patch_url, headers=HEADERS, json={
                "status": "succeeded",
                "log_tail": log_tail
            })
            
            print(f"[{time.strftime('%X')}] Stage {stage_name} succeeded.")

            # Check if this was the last stage, if so complete the run
            res_rem = requests.get(f"{SUPABASE_URL}/rest/v1/model_run_stages?run_id=eq.{run_id}&status=neq.succeeded", headers=HEADERS)
            if res_rem.status_code == 200 and not res_rem.json():
                print(f"Run {run_id} completely finished. Marking run as succeeded.")
                requests.patch(f"{SUPABASE_URL}/rest/v1/model_runs?id=eq.{run_id}", headers=HEADERS, json={"status": "succeeded"})

        except Exception as e:
            print(f"Error processing job: {e}")
            time.sleep(5)

if __name__ == "__main__":
    poll_for_jobs()
