"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Field, SelectField } from "./fields";
import type { ActualCommand, ActualVersion } from "@/lib/programs/work-program/reporting";
import type { WorkProgramDraft } from "@/lib/programs/work-program/schema";
export type ReportingData = {
 contracts?: { id: string; title: string; project_id: string | null }[];
 deliverables?: { id: string; title: string; project_id: string }[];
 timeSources?: { id: string; staff_id: string; engagement_id: string; entry_date: string; hours: string; notes: string; billable: boolean }[];
 spendSources?: { id: string; project_id: string; entry_date: string; amount: string; description: string }[];
 canManage: boolean; staff: { id: string; name: string; active: boolean; user_id: string | null }[];
 revisions: { id: string; revision: number; content_json: WorkProgramDraft; content_sha256: string; source_ids: string[] }[];
 actuals?: ActualVersion[]; rates?: { id: string; staff_id: string; hourly_cost: string; starts_on: string; ends_on: string }[];
 ownTime?: { entryId: string; version: number; entryDate: string; hours: string; billable: boolean; description: string; sourceKey: string; sourceReference: string; staffId: string; revisionId: string; projectId: string | null; contractId: string | null; allocations: ActualCommand["allocations"] }[];
};
export function newActual(revisionId: string, canManage: boolean): ActualCommand {
 return { requestId: crypto.randomUUID(), entryId: crypto.randomUUID(), expectedVersion: 0, revisionId, kind: "labor", status: "draft", entryDate: new Date().toISOString().slice(0, 10), sourceKey: "", sourceReference: "", description: "", staffId: null, projectId: null, contractId: null, timeEntryId: null, spendEntryId: null, hours: null, amount: null, basis: canManage ? "recorded" : "unvalued", rateId: null, billable: false, allocations: [], openingStart: null, openingEnd: null, correctionNote: "", openingBasis: "", reconciliationNote: "", linkedRecordReference: "" };
}
export function ActualEntry({ programId, data, save, disabled }: { programId: string; data: ReportingData; save: (command: ActualCommand) => Promise<boolean>; disabled: boolean }) {
 const [command, setCommand] = useState<ActualCommand>(() => newActual(data.revisions.at(-1)?.id ?? "", data.canManage));
 const [csv, setCsv] = useState(""), [filename, setFilename] = useState("");
 const [mapping, setMapping] = useState<Record<string, string>>({ sourceKey: "source_key", entryDate: "date", description: "description", hours: "hours", amount: "amount" });
 const [preview, setPreview] = useState<{ row: number; duplicate: boolean; errors: string[]; command: ActualCommand | null }[]>([]), [message, setMessage] = useState("");
 const revision = data.revisions.find(r => r.id === command.revisionId);
 const patch = (values: Partial<ActualCommand>) => { setCommand(c => ({ ...c, ...values })); setPreview([]); };
 const latest = [...new Map([...(data.actuals ?? [])].sort((a, b) => a.version - b.version).map(v => [v.entry_id, v])).values()];
 async function previewCsv() {
  setMessage("");
  try {
   const response = await fetch(`/api/programs/${programId}/work-program/reporting/import`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ csv, filename, mapping: Object.fromEntries(Object.entries(mapping).filter(([, v]) => v)), defaults: { ...command, sourceKey: command.sourceKey || "CSV source key", sourceReference: command.sourceReference || "CSV retained reference", description: command.description || "CSV mapped description" } }) });
   const result = await response.json(); if (!response.ok) throw new Error(result.error); setPreview(result.rows); setMessage(`Previewed ${result.rows.length} rows. Duplicate and invalid rows will not be imported.`);
  } catch (e) { setMessage(e instanceof Error ? e.message : "Preview unavailable"); }
 }
 return <section id="actual-work" className="space-y-5 rounded-xl border p-4 min-w-0">
  <h2 className="text-xl font-semibold">Actual work</h2><p className="text-sm text-muted-foreground">Enter agency time without a client contract. Owners and administrators reconcile costs before approving them. Billing, commitments and payments are separate measures and never add to incurred costs.</p>
  <form className="space-y-4" onSubmit={async e => { e.preventDefault(); if (await save(command)) setCommand(newActual(command.revisionId, data.canManage)); }}>
   <fieldset disabled={disabled} className="space-y-4 min-w-0">
   <div className="grid gap-4 md:grid-cols-2">
    <SelectField label="Attribution revision" value={command.revisionId} onChange={v => patch({ revisionId: v, allocations: [] })}>{data.revisions.map(r => <option key={r.id} value={r.id}>Revision {r.revision}</option>)}</SelectField>
    {data.canManage && <SelectField label="Entry kind" value={command.kind} onChange={v => patch({ kind: v as ActualCommand["kind"] })}>{["labor", "expense", "opening", "commitment", "billed", "payment"].map(k => <option key={k}>{k}</option>)}</SelectField>}
    <Field label="Entry date" type="date" value={command.entryDate} onChange={v => patch({ entryDate: v })}/>
    <Field label="Stable source key" value={command.sourceKey} onChange={v => patch({ sourceKey: v })}/>
    <Field label="Source reference" value={command.sourceReference} onChange={v => patch({ sourceReference: v })}/>
    <Field label="Description" value={command.description} onChange={v => patch({ description: v })}/>
    <SelectField label="Staff identity" value={command.staffId ?? ""} onChange={v => patch({ staffId: v || null })}><option value="">No staff attribution</option>{data.staff.map(s => <option key={s.id} value={s.id}>{s.name}{s.active ? "" : " (inactive; retained history)"}</option>)}</SelectField>
    <Field label="Hours" value={command.hours ?? ""} onChange={v => patch({ hours: v || null })}/>
    {data.canManage && <><SelectField label="Valuation basis" value={command.basis} onChange={v => patch({ basis: v as ActualCommand["basis"] })}><option value="recorded">Payroll or source cost</option><option value="cost_rate">Approved effective cost rate</option><option value="unvalued">Unvalued, needs reconciliation</option></SelectField>
    {command.basis === "cost_rate" ? <SelectField label="Approved cost rate" value={command.rateId ?? ""} onChange={v => patch({ rateId: v || null })}><option value="">Select rate</option>{data.rates?.filter(r => r.staff_id === command.staffId).map(r => <option key={r.id} value={r.id}>{r.hourly_cost}/hour · {r.starts_on} to {r.ends_on}</option>)}</SelectField> : <Field label="Source amount" value={command.amount ?? ""} onChange={v => patch({ amount: v || null })}/>}
    <SelectField label="Actual status" value={command.status} onChange={v => patch({ status: v as ActualCommand["status"] })}><option value="draft">Draft, unresolved</option><option value="approved">Approve source cost and allocations</option><option value="excluded">Exclude with correction reason</option></SelectField>
    <SelectField label="Contract (optional)" value={command.contractId ?? ""} onChange={v => patch({ contractId: v || null, timeEntryId: null })}><option value="">Agency work, no client contract</option>{data.contracts?.filter(c => c.project_id === command.projectId).map(c => <option key={c.id} value={c.id}>{c.title}</option>)}</SelectField>
    {command.kind === "labor" && !command.expectedVersion && <SelectField label="Existing time source (optional)" value={command.timeEntryId ?? ""} onChange={v => { const source = data.timeSources?.find(t => t.id === v); patch(source ? { timeEntryId: source.id, staffId: source.staff_id, contractId: source.engagement_id, hours: String(source.hours), entryDate: source.entry_date, billable: source.billable, description: source.notes || "Existing time", sourceKey: `time:${source.id}`, sourceReference: `Existing time entry ${source.id}` } : { timeEntryId: null }); }}><option value="">Create a new time entry</option>{data.timeSources?.filter(t => t.staff_id === command.staffId && t.engagement_id === command.contractId).map(t => <option key={t.id} value={t.id}>{t.entry_date} · {t.hours} hours · {t.notes}</option>)}</SelectField>}
    {command.kind === "expense" && !command.expectedVersion && <SelectField label="Existing expense source (optional)" value={command.spendEntryId ?? ""} onChange={v => { const source = data.spendSources?.find(t => t.id === v); patch(source ? { spendEntryId: source.id, amount: String(source.amount), entryDate: source.entry_date, description: source.description, basis: "recorded", sourceKey: `expense:${source.id}`, sourceReference: `Existing expense entry ${source.id}` } : { spendEntryId: null }); }}><option value="">Create a new expense</option>{data.spendSources?.filter(t => t.project_id === command.projectId).map(t => <option key={t.id} value={t.id}>{t.entry_date} · {t.amount} · {t.description}</option>)}</SelectField>}</>}
   </div>
   <label className="flex gap-2 text-sm"><input type="checkbox" checked={command.billable} onChange={e => patch({ billable: e.target.checked })}/>Billable work. Billing rates remain separate.</label>
   <div className="space-y-3"><h3 className="font-semibold">Allocation</h3><p className="text-sm">Use one or more shares totaling 100%. An empty list stays unallocated and cannot be approved.</p>
   {command.allocations.map((a, i) => {
    const element = revision?.content_json.elements.find(e => e.id === a.elementId);
    const change = (value: Partial<typeof a>) => patch({ allocations: command.allocations.map((row, ix) => ix === i ? { ...row, ...value } : row) });
    return <div key={i} className="grid gap-3 rounded-lg border p-3 md:grid-cols-2">
     <SelectField label={`Element ${i + 1}`} value={a.elementId} onChange={v => { const e = revision?.content_json.elements.find(e => e.id === v); patch({ projectId: e?.projectId ?? null, allocations: command.allocations.map((row, ix) => ix === i ? { ...row, elementId: v, taskId: null, deliverableId: null } : row) }); }}><option value="">Select element</option>{revision?.content_json.elements.map(e => <option key={e.id} value={e.id}>{e.code} {e.title}</option>)}</SelectField>
     <SelectField label={`Task ${i + 1}`} value={a.taskId ?? ""} onChange={v => change({ taskId: v || null })}><option value="">Element-level work</option>{element?.tasks.map(t => <option key={t.id} value={t.id}>{t.description}</option>)}</SelectField>
     <Field label={`Share ${i + 1} (%)`} value={String(a.share / 100)} onChange={v => change({ share: Math.round(Number(v) * 100) })}/>
     <SelectField label={`Deliverable ${i + 1} (optional)`} value={a.deliverableId ?? ""} onChange={v => change({ deliverableId: v || null })}><option value="">No deliverable attribution</option>{data.deliverables?.filter(d => d.project_id === command.projectId).map(d => <option key={d.id} value={d.id}>{d.title}</option>)}</SelectField>
     <Button className="h-auto min-h-10 max-w-full whitespace-normal" type="button" variant="outline" onClick={() => patch({ allocations: command.allocations.filter((_, ix) => ix !== i) })}>Remove share</Button>
    </div>;
   })}<Button className="h-auto min-h-10 max-w-full whitespace-normal" type="button" variant="outline" onClick={() => patch({ allocations: [...command.allocations, { elementId: "", taskId: null, deliverableId: null, share: command.allocations.length ? 5000 : 10000 }] })}>Add allocation</Button></div>
   {command.kind === "opening" && <><Field label="Opening coverage start" type="date" value={command.openingStart ?? ""} onChange={v => patch({ openingStart: v || null })}/><Field label="Opening coverage end" type="date" value={command.openingEnd ?? ""} onChange={v => patch({ openingEnd: v || null })}/><Field label="Opening balance coverage and basis" multiline value={command.openingBasis} onChange={v => patch({ openingBasis: v })}/></>}
   <Field label="Correction or exclusion reason" multiline value={command.correctionNote} onChange={v => patch({ correctionNote: v })}/>
   {data.canManage && <><Field label="Time/payroll reconciliation decision" multiline value={command.reconciliationNote} onChange={v => patch({ reconciliationNote: v })}/><Field label="Related invoice, reimbursement or payment reference" value={command.linkedRecordReference} onChange={v => patch({ linkedRecordReference: v })}/></>}
   <div className="flex flex-wrap gap-2"><Button className="h-auto min-h-10 max-w-full whitespace-normal" type="submit">{command.expectedVersion ? "Save correction" : "Save actual"}</Button><Button className="h-auto min-h-10 max-w-full whitespace-normal" type="button" variant="outline" onClick={() => setCommand(newActual(command.revisionId, data.canManage))}>New entry</Button></div>
   </fieldset>
  </form>
  {data.canManage && <details className="rounded-lg border p-3"><summary className="cursor-pointer font-semibold">Import CSV with mapping and preview</summary><div className="space-y-3 mt-3"><p className="text-sm">Select the default entry kind, valuation, staff and allocation above. Map stable source keys to detect duplicates across files. Payroll overlapping time must be reconciled before approval.</p><label className="block text-sm">CSV file<input className="block max-w-full" type="file" accept=".csv,text/csv" onChange={async e => { const f = e.target.files?.[0]; if (f) { setCsv(await f.text()); setFilename(f.name); setPreview([]); } }}/></label><div className="grid gap-3 md:grid-cols-3">{["sourceKey", "entryDate", "description", "hours", "amount", "staffId", "elementId", "taskId", "projectId"].map(f => <Field key={f} label={`CSV column for ${f}`} value={mapping[f] ?? ""} onChange={v => { setMapping(m => ({ ...m, [f]: v })); setPreview([]); }}/>)}</div><Button className="h-auto min-h-10 max-w-full whitespace-normal" type="button" variant="outline" disabled={!csv || disabled} onClick={previewCsv}>Preview import</Button><p role="status">{message}</p>{preview.length > 0 && <><div className="max-h-80 overflow-auto">{preview.map(r => <p key={r.row} className="border-b py-2 text-sm">Row {r.row}: {r.duplicate ? "Duplicate, skipped" : r.errors.length ? r.errors.join("; ") : `${r.command?.sourceKey}: ${r.command?.hours ?? ""} hours; ${r.command?.amount ?? "unvalued"}; ${r.command?.status}`}</p>)}</div><Button className="h-auto min-h-10 max-w-full whitespace-normal" disabled={disabled || !preview.some(r => r.command)} onClick={async () => { for (const row of preview.filter(r => r.command)) { if (!await save(row.command!)) { setMessage(`Import stopped at row ${row.row}. Retry the retained save, then preview again; saved rows will be detected as duplicates.`); return; } } setPreview([]); setMessage("Valid nonduplicate rows saved."); }}>Import valid rows</Button></>}</div></details>}
  <div className="space-y-2"><h3 className="font-semibold">Source ledger and corrections</h3>{latest.map(v => <div key={v.id} className="flex flex-wrap items-center justify-between gap-2 border-b py-3 text-sm"><span className="break-all">{v.source_key} · {v.entry_date} · {v.kind} · {v.amount ?? "unvalued"} · {v.status} · version {v.version}</span><Button className="h-auto min-h-10 max-w-full whitespace-normal hover:bg-background hover:text-foreground" variant="outline" onClick={() => setCommand({ ...v.detail, requestId: crypto.randomUUID(), expectedVersion: v.version, correctionNote: "", timeEntryId: null, spendEntryId: null })}>Correct {v.source_key}</Button></div>)}{data.ownTime?.map(v => <div key={`${v.entryId}-${v.version}`} className="flex flex-wrap gap-2"><span>{v.description} · {v.entryDate} · {v.hours} hours</span><Button className="h-auto min-h-10 max-w-full whitespace-normal hover:bg-background hover:text-foreground" variant="outline" onClick={() => setCommand({ ...newActual(v.revisionId, false), entryId: v.entryId, expectedVersion: v.version, entryDate: v.entryDate, hours: v.hours, billable: v.billable, description: v.description, sourceKey: v.sourceKey, sourceReference: v.sourceReference, staffId: v.staffId, projectId: v.projectId, contractId: v.contractId, allocations: v.allocations })}>Correct draft time</Button></div>)}{!latest.length && !data.ownTime?.length && <p className="text-sm text-muted-foreground">No attributed actuals yet. Existing unmapped time and spending keep their original meaning.</p>}</div>
 </section>;
}
