import type {WorkProgramDraft} from "@/lib/programs/work-program/schema";
import type {WorkProgramSource} from "@/lib/programs/work-program/types";
/** Grouping aids inspection; only explicit source references establish a work mapping. */
export function WorkProgramComparison({draft,sources}:{draft:WorkProgramDraft;sources:WorkProgramSource[]}) {
  const codes=[...new Set(sources.flatMap(source=>source.extraction_json.elements.map(element=>element.code)))];
  return <section className="space-y-3 rounded border p-4"><h2 className="text-xl font-semibold">Predecessor, amendments and proposed cycle</h2><p className="text-sm">Codes group passages for comparison. A matching code or a later document date does not decide precedence or completion. Explain each relationship in the mapping and amendment tables.</p><div className="max-w-full overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Source work elements and explicitly mapped proposal work</caption><thead><tr><th className="p-2">Code</th>{sources.map(source=><th className="min-w-48 p-2" key={source.id}>{source.title}<br/>{source.source_role}</th>)}<th className="min-w-48 p-2">Proposed work and explanation</th></tr></thead><tbody>{codes.map(code=>{
    const refs=sources.flatMap(source=>source.extraction_json.elements.filter(element=>element.code===code).map(element=>({sourceId:source.id,key:element.key})));
    const mappings=draft.preparation?.mappings.filter(mapping=>mapping.sourceRefs.some(ref=>refs.some(row=>ref.sourceId===row.sourceId&&ref.elementKey===row.key)))??[];
    const targetIds=new Set(mappings.flatMap(mapping=>mapping.targetIds));
    const proposed=draft.elements.filter(element=>targetIds.has(element.id)||[element.source,...element.sourceRefs??[]].some(ref=>ref&&refs.some(row=>ref.sourceId===row.sourceId&&ref.elementKey===row.key)));
    return <tr key={code} className="border-t"><th className="p-2 align-top">{code}</th>{sources.map(source=><td key={source.id} className="p-2 align-top">{source.extraction_json.elements.filter(element=>element.code===code).map(element=><details key={element.key}><summary>{element.title}</summary><p className="whitespace-pre-wrap">{element.objective}</p><a className="underline" href={`/api/knowledge-base/documents/${source.document_id}/download?disposition=inline#page=${element.pageFrom}`} target="_blank" rel="noreferrer">Original PDF pages {element.pageFrom}–{element.pageTo}</a></details>)}{!source.extraction_json.elements.some(element=>element.code===code)&&"Not found in this extraction; disposition unresolved"}</td>)}<td className="p-2 align-top">{proposed.length?proposed.map(element=><p key={element.id}><a className="underline" href={`#owp-row-${element.id}`}>{element.title}</a>: {element.disposition}. {element.decisionNote||"Explanation unresolved."}</p>):"No proposed target recorded."}{mappings.map(mapping=><p key={mapping.id}>{mapping.disposition}: {mapping.note||"Explanation unresolved."}</p>)}</td></tr>;
  })}</tbody></table></div></section>;
}
