"use client";
import { Button } from "@/components/ui/button";
import type { WorkProgramElement } from "@/lib/programs/work-program/schema";
import type { WorkProgramSource } from "@/lib/programs/work-program/types";
import { Field, SelectField } from "./fields";

type Props = { element: WorkProgramElement; sources: WorkProgramSource[]; projects: { id: string; name: string }[]; onChange: (element: WorkProgramElement) => void };
export function WorkProgramElementEditor({ element, sources, projects, onChange }: Props) {
  const set = <K extends keyof WorkProgramElement>(key: K, value: WorkProgramElement[K]) => onChange({ ...element, [key]: value });
  const source = sources.find((row) => row.id === element.source?.sourceId);
  return <details className="min-w-0 rounded-lg border p-4" open={!element.title}>
    <summary className="cursor-pointer font-semibold break-words">{element.code} {element.title || "New work element"} · {element.disposition}</summary>
    <div className="mt-4 space-y-5">
      <div className="grid min-w-0 gap-4 md:grid-cols-2"><Field label="Work element code" value={element.code} onChange={(value) => set("code", value)} /><Field label="Work element title" value={element.title} onChange={(value) => set("title", value)} />
        <SelectField label="Carry-forward decision" value={element.disposition} onChange={(value) => set("disposition", value as WorkProgramElement["disposition"])}><option value="unresolved">Unresolved</option><option value="continuing">Continuing</option><option value="changed">Changed</option><option value="completed">Completed in predecessor</option>{!element.source && <option value="new">New work</option>}</SelectField>
        <SelectField label="Linked project, if applicable" value={element.projectId ?? ""} onChange={(value) => set("projectId", value || null)}><option value="">No project linked</option>{projects.map((project) => <option key={project.id} value={project.id}>{project.name}</option>)}</SelectField>
      </div>
      <Field label="Reason for the carry-forward decision" multiline value={element.decisionNote} onChange={(value) => set("decisionNote", value)} />
      {source && element.source?.elementKey ? <p className="text-sm">Retained source: {source.title}, PDF pages {element.source.pageFrom}–{element.source.pageTo}. Review the original in the source section.</p> : <div className="grid gap-4 md:grid-cols-2">
        <SelectField label="Manual source citation" value={element.source?.sourceId ?? ""} onChange={(value) => set("source", value ? { sourceId: value, elementKey: null, pageFrom: 0, pageTo: 0, tableLabel: "" } : null)}><option value="">No source citation</option>{sources.map((row) => <option key={row.id} value={row.id}>{row.title}</option>)}</SelectField>
        {element.source && <><Field label="First PDF page" type="number" value={String(element.source.pageFrom || "")} onChange={(value) => set("source", { ...element.source!, pageFrom: Number(value) })} /><Field label="Last PDF page" type="number" value={String(element.source.pageTo || "")} onChange={(value) => set("source", { ...element.source!, pageTo: Number(value) })} /><Field label="Table or passage reference" value={element.source.tableLabel} onChange={(value) => set("source", { ...element.source!, tableLabel: value })} /></>}
      </div>}
      <Field label="Proposed objective" multiline value={element.objective} onChange={(value) => set("objective", value)} />
      <Field label="Proposed discussion" multiline value={element.discussion} onChange={(value) => set("discussion", value)} />
      <div className="grid gap-4 md:grid-cols-2"><Field label="Proposed responsible person or organization" value={element.responsible} onChange={(value) => set("responsible", value)} /><Field label="Proposed person-months, blank if unresolved" type="number" value={element.personMonths === null ? "" : String(element.personMonths)} onChange={(value) => set("personMonths", value === "" ? null : Number(value))} /></div>
      <Field label="Proposed completion schedule" multiline value={element.schedule} onChange={(value) => set("schedule", value)} />
      {(["tasks", "products"] as const).map((kind) => <section key={kind} className="space-y-3"><h3 className="font-semibold">Proposed {kind}</h3>{element[kind].map((row, index) => <div key={row.id} className="space-y-3 rounded border p-3"><Field label={`${kind === "tasks" ? "Task" : "Product"} ${index + 1}`} multiline value={row.description} onChange={(value) => set(kind, element[kind].map((item) => item.id === row.id ? { ...item, description: value } : item))} /><div className="grid gap-3 md:grid-cols-2"><Field label={`Responsible for ${kind} ${index + 1}`} value={row.responsible} onChange={(value) => set(kind, element[kind].map((item) => item.id === row.id ? { ...item, responsible: value } : item))} /><Field label={`Schedule for ${kind} ${index + 1}`} value={row.schedule} onChange={(value) => set(kind, element[kind].map((item) => item.id === row.id ? { ...item, schedule: value } : item))} /></div><Button type="button" variant="outline" onClick={() => set(kind, element[kind].filter((item) => item.id !== row.id))}>Remove proposed {kind === "tasks" ? "task" : "product"} {index + 1}</Button></div>)}<Button type="button" variant="outline" onClick={() => set(kind, [...element[kind], { id: crypto.randomUUID(), description: "", responsible: "", schedule: "" }])}>Add {kind === "tasks" ? "task" : "product"}</Button></section>)}
      <section className="space-y-4"><h3 className="font-semibold">Proposed budget</h3><p className="text-sm text-muted-foreground">Enter reviewed funding and cost lines. Blank amounts remain unresolved. Explain indirect-cost allocations so they are counted once. Completed predecessor work stays in the history and is excluded from proposed totals.</p>
        <SelectField label="Treatment in program totals" value={element.budgetTreatment} onChange={(value) => set("budgetTreatment", value as WorkProgramElement["budgetTreatment"])}><option value="unresolved">Unresolved</option><option value="included">Include in proposed totals</option><option value="informational">Information only, allocated elsewhere</option></SelectField>
        <Field label="Allocation or budget treatment explanation" multiline value={element.budgetTreatmentNote} onChange={(value) => set("budgetTreatmentNote", value)} />
        {element.budget.map((line, index) => {
          const update = (patch: Partial<typeof line>) => set("budget", element.budget.map((row) => row.id === line.id ? { ...row, ...patch } : row));
          return <div key={line.id} className="space-y-3 rounded border p-3"><h4 className="font-medium">Budget line {index + 1}</h4><div className="grid gap-3 md:grid-cols-2"><SelectField label={`Line ${index + 1} kind`} value={line.kind} onChange={(value) => update({ kind: value as typeof line.kind })}><option value="revenue">Revenue</option><option value="cost">Cost</option></SelectField><Field label={`Line ${index + 1} funding source or cost category`} value={line.label} onChange={(value) => update({ label: value })} /><Field label={`Line ${index + 1} amount, blank if unresolved`} type="number" value={line.amount === null ? "" : String(line.amount)} onChange={(value) => update({ amount: value === "" ? null : Number(value) })} /><Field label={`Line ${index + 1} funding year`} value={line.fundingYear} onChange={(value) => update({ fundingYear: value })} /><SelectField label={`Line ${index + 1} review state`} value={line.basis} onChange={(value) => update({ basis: value as typeof line.basis })}><option value="unresolved">Unresolved</option><option value="proposed">Reviewed for this proposal</option></SelectField></div><Field label={`Line ${index + 1} calculation and source reference`} multiline value={line.note} onChange={(value) => update({ note: value })} /><Button type="button" variant="outline" onClick={() => set("budget", element.budget.filter((row) => row.id !== line.id))}>Remove budget line {index + 1}</Button></div>;
        })}
        <Button type="button" variant="outline" onClick={() => set("budget", [...element.budget, { id: crypto.randomUUID(), kind: "revenue", label: "", amount: null, fundingYear: "", basis: "unresolved", note: "" }])}>Add budget line</Button>
      </section>
    </div>
  </details>;
}
