"use client";
import { useState } from "react";
import { downloadAuthenticatedArtifact } from "@/lib/export/download";
import { Button } from "@/components/ui/button";
import { Field, SelectField } from "./fields";
import { summarizeReport, type ManagementCommand, type ReportingPeriod, type PeriodReport, type PeriodProgress, type ReportSnapshot } from "@/lib/programs/work-program/reporting";
import type { ReportingData } from "./actual-entry";
type Data = ReportingData & { periods: ReportingPeriod[]; reports: PeriodReport[]; events: { id: string; revision_id: string; kind: string; payload: { targetEventId?: string } }[] };
export function BudgetPosition({ snapshot }: { snapshot: ReportSnapshot }) {
 let totals: ReturnType<typeof summarizeReport>;
 try { totals = summarizeReport(snapshot); } catch (e) { return <p role="alert">Budget could not reconcile: {e instanceof Error ? e.message : "invalid report"}</p>; }
  return <section id="budget-position" className="space-y-4 rounded-xl border p-4 min-w-0"><h2 className="text-xl font-semibold">Budget position</h2><p className="text-sm">Adopted revision {snapshot.baseline.revision} · {snapshot.baseline.content_json.currency}. Source cutoff {snapshot.period.source_cutoff}. Remaining work comes from dated estimates. {snapshot.workingPreview && "Working preview; unresolved costs are omitted from totals."}</p><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">{["incurred", "commitments", "billed", "payments"].map(key => <div key={key} className="rounded-lg border bg-card text-card-foreground p-3"><p className="capitalize text-sm">{key}</p><p className="font-semibold">{totals.total.cumulative[key as keyof typeof totals.total.cumulative]}</p><p className="text-xs">Period: {totals.total.period[key as keyof typeof totals.total.period]}</p></div>)}</div>{totals.budget.map(b => <div key={b.elementId} className="space-y-2 rounded-lg border p-3"><h3 className="font-semibold">{b.label}</h3><dl className="grid grid-cols-2 gap-2 text-sm">{[["Adopted budget", b.approved], ["Incurred cost", b.incurred], ["Budget remaining", b.budgetRemaining], ["Remaining estimate", b.remainingEstimate], ["Actual plus remaining", b.actualPlusRemaining]].map(([label, value]) => <div key={label}><dt>{label}</dt><dd className="font-semibold">{value ?? "Incomplete"}</dd></div>)}</dl></div>)}<details><summary>Reconcile element, task, staff and source totals</summary>{[["Elements", totals.byElement], ["Tasks", totals.byTask], ["Staff", totals.byStaff], ["Sources", totals.bySource]].map(([label, values]) => <div key={String(label)} className="mt-3"><h3 className="font-semibold">{String(label)}</h3>{(values as typeof totals.byElement).map(row => <p key={row.key} className="break-words text-sm">{row.label}: period incurred {row.period.incurred}; cumulative incurred {row.cumulative.incurred}; hours {row.cumulative.hours}; commitments {row.cumulative.commitments}; billed {row.cumulative.billed}; payments {row.cumulative.payments}</p>)}</div>)}</details><p className="text-sm">{totals.unresolved.length} excluded or unresolved entries retained. Unrecorded costs and agency accounting completeness remain unassessed.</p></section>;
}
export function PeriodReporting({ programId, data, save, disabled }: { programId: string; data: Data; save: (command: ManagementCommand) => Promise<boolean>; disabled: boolean }) {
 const empty = (): ReportingPeriod => ({ id: crypto.randomUUID(), name: "", starts_on: "", ends_on: "", baseline_id: null, source_cutoff: new Date().toISOString(), version: 0, state: "draft", progress: [], note: "", review_snapshot: null });
 const [period, setPeriod] = useState<ReportingPeriod>(empty);
 const [actionNote, setActionNote] = useState("");
 const [shown, setShown] = useState<ReportSnapshot | null>(null);
 const [exports, setExports] = useState<Record<string, { status: string; document?: { id: string; checksum: string | null }; error?: string }>>({});
 const [rate, setRate] = useState({ staffId: "", startsOn: "", endsOn: "", hourlyCost: "", sourceReference: "" });
 const baseline = data.revisions.find(r => r.id === period.baseline_id);
 const adopted = new Set(data.events.filter(e => e.kind === "adoption" && !data.events.some(n => n.kind === "withdraw_authority" && n.payload.targetEventId === e.id)).map(e => e.revision_id));
 const editProgress = (i: number, change: Partial<PeriodProgress>) => setPeriod(p => ({ ...p, progress: p.progress.map((r, index) => i === index ? { ...r, ...change } : r) }));
 async function artifact(reportId: string, format: "pdf" | "xlsx", queue: boolean) {
  const key = `${reportId}-${format}`, url = `/api/programs/${programId}/work-program/reporting/reports?reportId=${reportId}&format=${format}`;
  try {
   if (queue) { const response = await fetch(url, { method: "POST" }); const body = await response.json(); if (!response.ok) throw new Error(body.error); }
   const response = await fetch(url); const body = await response.json(); if (!response.ok) throw new Error(body.error); setExports(v => ({ ...v, [key]: body }));
  } catch (e) { setExports(v => ({ ...v, [key]: { status: "unavailable", error: e instanceof Error ? e.message : "Export unavailable" } })); }
 }
 return <>
 <section id="period-reports" className="space-y-5 rounded-xl border p-4 min-w-0"><h2 className="text-xl font-semibold">Period reports</h2><p className="text-sm">Internal management reports contain private cost information and are restricted to owners and administrators. Review freezes the exact source versions. Issue retains that snapshot; corrections produce another version.</p>
 <div className="flex flex-wrap gap-2">{data.periods.map(p => <Button className="h-auto min-h-10 max-w-full whitespace-normal" key={p.id} variant="outline" onClick={() => { setPeriod(p); setShown(p.review_snapshot); }}>{p.name} · {p.state}</Button>)}<Button className="h-auto min-h-10 max-w-full whitespace-normal hover:bg-background hover:text-foreground" variant="outline" onClick={() => { setPeriod(empty()); setShown(null); }}>New reporting period</Button></div>
 <form className="space-y-4" onSubmit={async e => { e.preventDefault(); const ok = await save({ kind: "period", requestId: crypto.randomUUID(), periodId: period.id, expectedVersion: period.version, name: period.name, startsOn: period.starts_on, endsOn: period.ends_on, baselineId: period.baseline_id, sourceCutoff: period.source_cutoff, progress: period.progress, note: period.note }); if (ok) setPeriod(p => ({ ...p, version: p.version + 1 })); }}><fieldset disabled={disabled || ["review", "issued"].includes(period.state)} className="space-y-4 min-w-0">
 <div className="grid gap-4 md:grid-cols-2"><Field label="Reporting period name" value={period.name} onChange={v => setPeriod(p => ({ ...p, name: v }))}/><SelectField label="Adopted reporting baseline" value={period.baseline_id ?? ""} onChange={v => setPeriod(p => ({ ...p, baseline_id: v || null, progress: [] }))}><option value="">No adopted baseline, draft collection only</option>{data.revisions.filter(r => adopted.has(r.id)).map(r => <option key={r.id} value={r.id}>Revision {r.revision}</option>)}</SelectField><Field label="Period start" type="date" value={period.starts_on} onChange={v => setPeriod(p => ({ ...p, starts_on: v }))}/><Field label="Period end" type="date" value={period.ends_on} onChange={v => setPeriod(p => ({ ...p, ends_on: v }))}/><Field label="Source cutoff (ISO date and time)" value={period.source_cutoff} onChange={v => setPeriod(p => ({ ...p, source_cutoff: v }))}/><Button className="h-auto min-h-10 max-w-full whitespace-normal" type="button" variant="outline" onClick={() => setPeriod(p => ({ ...p, source_cutoff: new Date().toISOString() }))}>Include entries saved through now</Button></div>
 <Field label="Period notes" multiline value={period.note} onChange={v => setPeriod(p => ({ ...p, note: v }))}/>
 <Button className="h-auto min-h-10 max-w-full whitespace-normal" type="button" variant="outline" disabled={!baseline || !period.starts_on || !period.ends_on} onClick={() => {
  if (!baseline) return;
  const versions = (data.actuals ?? []).filter(v => v.created_at <= period.source_cutoff).sort((a, b) => a.version - b.version);
  const actuals = [...new Map(versions.map(v => [v.entry_id, v])).values()].filter(v => v.entry_date <= period.ends_on && (v.entry_date >= baseline.content_json.periodStart || v.kind === "opening"));
  setShown({ schemaVersion: 1, workingPreview: true, period, baseline, actuals, valuationHistory: versions, reviewNote: "Working preview; draft and excluded costs are unresolved and omitted from incurred totals." });
 }}>Preview current budget position</Button>
 <h3 className="font-semibold">Progress and remaining work</h3><p className="text-sm">Describe completed products and issues independently of spending. A blank estimate remains incomplete. Use element totals or complete task estimates, without adding both.</p>
 {period.progress.map((p, i) => <div key={i} className="space-y-3 rounded-lg border p-3"><div className="grid gap-3 md:grid-cols-2"><SelectField label={`Progress element ${i + 1}`} value={p.elementId} onChange={v => editProgress(i, { elementId: v, taskId: null })}><option value="">Select element</option>{baseline?.content_json.elements.map(e => <option key={e.id} value={e.id}>{e.code} {e.title}</option>)}</SelectField><SelectField label={`Progress task ${i + 1}`} value={p.taskId ?? ""} onChange={v => editProgress(i, { taskId: v || null })}><option value="">Element total</option>{baseline?.content_json.elements.find(e => e.id === p.elementId)?.tasks.map(t => <option key={t.id} value={t.id}>{t.description}</option>)}</SelectField><Field label={`Estimate as of ${i + 1}`} type="date" value={p.asOf} onChange={v => editProgress(i, { asOf: v })}/><Field label={`Remaining hours ${i + 1}`} value={p.remainingHours ?? ""} onChange={v => editProgress(i, { remainingHours: v || null })}/><Field label={`Remaining cost ${i + 1}`} value={p.remainingCost ?? ""} onChange={v => editProgress(i, { remainingCost: v || null })}/></div>{([ ["completed", "Completed products"], ["outstanding", "Outstanding work"], ["issues", "Issues"], ["estimateBasis", "Estimate basis"] ] as const).map(([key, label]) => <Field key={key} label={`${label} ${i + 1}`} multiline value={p[key]} onChange={v => editProgress(i, { [key]: v })}/>)}<Button className="h-auto min-h-10 max-w-full whitespace-normal" type="button" variant="outline" onClick={() => setPeriod(v => ({ ...v, progress: v.progress.filter((_, index) => i !== index) }))}>Remove progress row</Button></div>)}
 <Button className="h-auto min-h-10 max-w-full whitespace-normal" type="button" variant="outline" disabled={!baseline} onClick={() => setPeriod(p => ({ ...p, progress: [...p.progress, { elementId: "", taskId: null, asOf: p.ends_on, completed: "", outstanding: "", issues: "", remainingHours: null, remainingCost: null, estimateBasis: "" }] }))}>Add progress and estimate</Button>
 <div><Button className="h-auto min-h-10 max-w-full whitespace-normal" type="submit">Save reporting period</Button></div></fieldset></form>
 {period.version > 0 && <div className="space-y-3"><Field label="Review, return, issue or correction note" value={actionNote} onChange={setActionNote} multiline/><div className="flex flex-wrap gap-2">{(["review", "return", "issue", "correct"] as const).filter(k => k === "review" ? ["draft", "returned", "correcting"].includes(period.state) : k === "correct" ? period.state === "issued" : period.state === "review").map(kind => <Button className="h-auto min-h-10 max-w-full whitespace-normal" key={kind} disabled={disabled || !actionNote.trim()} onClick={async () => { if (await save({ kind, requestId: crypto.randomUUID(), periodId: period.id, expectedVersion: period.version, note: actionNote })) { setPeriod(p => ({ ...p, version: p.version + 1, state: kind === "correct" ? "correcting" : kind === "return" ? "returned" : kind === "issue" ? "issued" : "review" })); setActionNote(""); } }}>{kind === "review" ? "Freeze report for review" : kind === "return" ? "Return for changes" : kind === "issue" ? "Issue reviewed report" : "Start corrected version"}</Button>)}</div><p className="text-sm">Select the saved period above to inspect its frozen review and current state.</p></div>}
 {data.periods.find(p => p.id === period.id)?.review_snapshot && <Button className="h-auto min-h-10 max-w-full whitespace-normal hover:bg-background hover:text-foreground" variant="outline" onClick={() => setShown(data.periods.find(p => p.id === period.id)!.review_snapshot)}>Inspect frozen budget position</Button>}
 <h3 className="font-semibold">Issued files and correction history</h3>{data.reports.map(r => <div key={r.id} className="space-y-3 rounded-lg border p-3"><p>{r.snapshot.period.name} · version {r.version} · {r.corrects_report_id ? "Corrected report" : "Original issue"}</p><Button className="h-auto min-h-10 max-w-full whitespace-normal hover:bg-background hover:text-foreground" variant="outline" onClick={() => setShown(r.snapshot)}>Inspect issued budget</Button><div className="flex flex-wrap gap-3">{(["pdf", "xlsx"] as const).map(format => { const status = exports[`${r.id}-${format}`]; return <div key={format} className="space-y-2"><Button className="h-auto min-h-10 max-w-full whitespace-normal" disabled={disabled} variant="outline" onClick={() => artifact(r.id, format, true)}>Prepare {format.toUpperCase()}</Button><Button className="h-auto min-h-10 max-w-full whitespace-normal" variant="ghost" onClick={() => artifact(r.id, format, false)}>Check {format.toUpperCase()}</Button>{status && <p role="status" className="text-sm">{status.status}{status.error ? `: ${status.error}` : ""}</p>}{status?.document?.checksum && <Button className="h-auto min-h-10 max-w-full whitespace-normal hover:bg-background hover:text-foreground" variant="outline" onClick={async () => { try { await downloadAuthenticatedArtifact(`/api/knowledge-base/documents/${status.document!.id}/download?delivery=authenticated`, `management-${r.snapshot.period.name.replace(/[^a-zA-Z0-9-]/g, "-")}-v${r.version}.${format}`, status.document!.checksum!); } catch (e) { setExports(v => ({ ...v, [`${r.id}-${format}`]: { ...status, error: e instanceof Error ? e.message : "Download could not be verified" } })); } }}>Download {format.toUpperCase()}</Button>}</div>; })}</div><p className="break-all text-xs text-muted-foreground">Report {r.id} · SHA256 {r.snapshot_hash}</p></div>)}
 </section>
 {shown ? <BudgetPosition snapshot={shown}/> : <section id="budget-position" className="rounded-xl border p-4"><h2 className="text-xl font-semibold">Budget position</h2><p className="text-sm">Select a baseline and dates to preview costs, or inspect a retained report above.</p></section>}
 <details className="rounded-xl border p-4"><summary className="cursor-pointer font-semibold">Private approved cost rates</summary><form className="space-y-3 mt-3" onSubmit={async e => { e.preventDefault(); if (await save({ kind: "rate", requestId: crypto.randomUUID(), rateId: crypto.randomUUID(), ...rate })) setRate({ staffId: "", startsOn: "", endsOn: "", hourlyCost: "", sourceReference: "" }); }}><p className="text-sm">A new rate leaves every original valuation intact. Select the appropriate approved rate on each cost entry; correct past records explicitly.</p><SelectField label="Rate staff" value={rate.staffId} onChange={v => setRate(r => ({ ...r, staffId: v }))}><option value="">Select staff</option>{data.staff.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}</SelectField>{([ ["startsOn", "Rate effective start", "date"], ["endsOn", "Rate effective end", "date"], ["hourlyCost", "Hourly cost, not billing rate", "text"], ["sourceReference", "Approved rate source and basis", "text"] ] as const).map(([key, label, type]) => <Field key={key} label={label} type={type} value={rate[key]} onChange={v => setRate(r => ({ ...r, [key]: v }))}/>)}<Button className="h-auto min-h-10 max-w-full whitespace-normal" disabled={disabled} type="submit">Save approved cost rate</Button></form></details>
 </>;
}
