"use client";
import { useState } from "react";
import { Button } from "@/components/ui/button";
import type { WorkProgramDraft, WorkProgramStructuredPreparation as Preparation } from "@/lib/programs/work-program/schema";
import type { WorkProgramSource } from "@/lib/programs/work-program/types";
import { Field, SelectField } from "./fields";
import { WorkProgramReferences, type SourceReference } from "./references";

type Option = { value: string; label: string };
type Column<Row> = { key: Extract<keyof Row, string>; label: string; kind?: "number" | "date" | "select" | "boolean" | "multiselect"; options?: Option[]; nullable?: boolean };
function Rows<Row extends { id: string; sourceRefs: SourceReference[] }>({ title, rows, columns, create, sources, onChange }: { title: string; rows: Row[]; columns: Column<Row>[]; create: () => Row; sources: WorkProgramSource[]; onChange: (rows: Row[]) => void }) {
  const [expanded, setExpanded] = useState<Set<string>>(new Set());
  return <details className="min-w-0 rounded-lg border p-4"><summary className="cursor-pointer font-semibold">{title} ({rows.length})</summary><div className="mt-4 space-y-4">
    {rows.map((row, index) => <details id={`owp-row-${row.id}`} key={row.id} className="scroll-mt-24 rounded border p-3" onToggle={(event) => { const open = event.currentTarget.open; setExpanded((current) => { const next = new Set(current); if (open) next.add(row.id); else next.delete(row.id); return next; }); }}><summary className="cursor-pointer text-sm">{title} row {index + 1}: {columns.filter((column) => ["name","label","role","table","row","title","description"].includes(column.key)).map((column) => String(row[column.key] ?? "")).join(" · ").slice(0,180)}</summary>{expanded.has(row.id) && <div className="mt-3 space-y-3"><div className="grid min-w-0 gap-3 md:grid-cols-2">{columns.map((column) => {
      const value = row[column.key];
      const change = (next: unknown) => onChange(rows.map((item) => item.id === row.id ? { ...item, [column.key]: next } : item));
      if (column.kind === "boolean") return <label key={column.key} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Boolean(value)} onChange={(event) => change(event.target.checked)} />{column.label}</label>;
      if (column.kind === "multiselect") return <fieldset key={column.key} className="rounded border p-2"><legend className="text-sm">{column.label}</legend>{column.options?.map((option) => <label key={option.value} className="flex items-center gap-2 text-sm"><input type="checkbox" checked={Array.isArray(value) && value.includes(option.value)} onChange={(event) => change(event.target.checked ? [...(Array.isArray(value) ? value : []), option.value] : (Array.isArray(value) ? value : []).filter((id) => id !== option.value))} />{option.label}</label>)}</fieldset>;
      if (column.kind === "select") return <SelectField key={column.key} label={column.label} value={String(value ?? "")} onChange={(value) => change(value === "" && column.nullable ? null : value)}><option value="">Choose / unresolved</option>{column.options?.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}</SelectField>;
      return <Field key={column.key} label={column.label} value={String(value ?? "")} type={column.kind === "number" ? "number" : column.kind === "date" ? "date" : "text"} multiline={column.key.toLowerCase().includes("note") || column.key === "resolution" || column.key === "proposedText"} onChange={(value) => change(column.kind === "number" ? value === "" ? null : Number(value) : value)} />;
    })}</div><WorkProgramReferences value={row.sourceRefs} sources={sources} onChange={(sourceRefs) => onChange(rows.map((item) => item.id === row.id ? { ...item, sourceRefs } : item))} /><Button type="button" variant="outline" onClick={() => onChange(rows.filter((item) => item.id !== row.id))}>Remove proposed row</Button></div>}</details>)}
    <Button type="button" variant="outline" onClick={() => onChange([...rows, create()])}>Add {title.toLowerCase()} row</Button>
  </div></details>;
}
const choices = (...values: string[]): Option[] => values.map((value) => ({ value, label: value.replaceAll("_", " ") }));
type Props = { draft: WorkProgramDraft; sources: WorkProgramSource[]; staff: Option[]; contracts: Option[]; onChange: (value: Preparation) => void };
export function StructuredWorkProgramEditor({ draft, sources, staff, contracts, onChange }: Props) {
  const p = draft.preparation;
  if (!p) return null;
  const identity = () => ({ id: crypto.randomUUID(), sourceRefs: [] });
  const target = () => ({ elementId: draft.elements[0]?.id ?? "", taskId: null });
  const period = () => ({ periodStart: draft.periodStart, periodEnd: draft.periodEnd });
  const elementOptions = draft.elements.map((row) => ({ value: row.id, label: `${row.code} ${row.title}` }));
  const fundOptions = p.funds.map((row) => ({ value: row.id, label: `${row.name} · ${row.vintage}` }));
  const sourceOptions = sources.map((row) => ({ value: row.id, label: row.title }));
  const taskOptions = draft.elements.flatMap((element) => element.tasks.map((row) => ({ value: row.id, label: `${element.code} · ${row.description.slice(0, 90)}` })));
  const targetColumns = [{ key: "elementId", label: "Work element", kind: "select", options: elementOptions }, { key: "taskId", label: "Task, if applicable", kind: "select", nullable: true, options: taskOptions }] as const;
  return <section className="min-w-0 space-y-4"><h2 className="text-xl font-semibold">Funding, staffing and source decisions</h2><p className="text-sm">Blank figures remain unresolved. Reference authority and balances stay separate from proposed funding. Totals use the tables below; original budget notes remain in history.</p>
    <Rows<NonNullable<Preparation["referenceFigures"]>[number]> title="Source financial and staffing figures" rows={p.referenceFigures ?? []} sources={sources} onChange={(referenceFigures) => onChange({ ...p, referenceFigures })} create={() => ({ ...identity(), table: "", row: "", column: "", unit: "", value: null, sourceText: "", state: "unavailable", note: "" })} columns={[{ key: "table", label: "Original table" }, { key: "row", label: "Original row" }, { key: "column", label: "Original column" }, { key: "unit", label: "Source units" }, { key: "value", label: "Numeric reference value", kind: "number" }, { key: "sourceText", label: "Exact printed cell" }, { key: "state", label: "Printed state", kind: "select", options: choices("amount", "blank", "dash", "unavailable") }, { key: "note", label: "Reference meaning; excluded from proposed totals" }]} />
      <Rows<Preparation["funds"][number]> title="Funding sources" rows={p.funds} sources={sources} onChange={(funds) => onChange({ ...p, funds })} create={() => ({ ...identity(), ...period(), name: "", vintage: "", kind: "proposed", amount: null, basis: "unresolved", note: "" })} columns={[{ key: "name", label: "Funding source" }, { key: "vintage", label: "Funding vintage" }, { key: "kind", label: "Funding meaning", kind: "select", options: choices("proposed", "match", "carryover", "prior_authority", "prior_balance") }, { key: "amount", label: `Amount (${draft.currency})`, kind: "number" }, { key: "basis", label: "Availability basis", kind: "select", options: choices("proposed", "reference", "unresolved") }, { key: "periodStart", label: "Effective from", kind: "date" }, { key: "periodEnd", label: "Effective through", kind: "date" }, { key: "matchBasis", label: "Match requirement basis", kind: "select", options: choices("unresolved", "not_required", "amount", "percent_funded_amount", "percent_total_cost") }, { key: "matchValue", label: "Required match amount or percent, according to basis", kind: "number" }, { key: "matchNote", label: "Source applicability of match requirement" }, { key: "note", label: "Funding and carryover assumptions" }]} />
    <Rows<Preparation["allocations"][number]> title="Allocations" rows={p.allocations} sources={sources} onChange={(allocations) => onChange({ ...p, allocations })} create={() => ({ ...identity(), ...target(), fundId: p.funds[0]?.id ?? "", amount: null, matchForFundId: null, note: "" })} columns={[...targetColumns, { key: "fundId", label: "Funding source and vintage", kind: "select", options: fundOptions }, { key: "amount", label: `Proposed allocation (${draft.currency})`, kind: "number" }, { key: "matchForFundId", label: "Provides match for", kind: "select", nullable: true, options: fundOptions }, { key: "note", label: "Allocation and match basis" }]} />
    <Rows<Preparation["costs"][number]> title="Expenditures" rows={p.costs} sources={sources} onChange={(costs) => onChange({ ...p, costs })} create={() => ({ ...identity(), ...target(), label: "", category: "direct", amount: null, contractId: null, indirectPoolId: null, note: "" })} columns={[...targetColumns, { key: "label", label: "Expenditure category or description" }, { key: "category", label: "Cost treatment", kind: "select", options: choices("direct", "consultant", "indirect", "labor_summary") }, { key: "amount", label: `Proposed cost (${draft.currency})`, kind: "number" }, { key: "contractId", label: "Existing contract", kind: "select", nullable: true, options: contracts }, { key: "indirectPoolId", label: "Indirect pool", kind: "select", nullable: true, options: p.indirectPools.map((row) => ({ value: row.id, label: row.name })) }, { key: "note", label: "Cost source and allocation explanation" }]} />
    <Rows<Preparation["staffing"][number]> title="Staffing" rows={p.staffing} sources={sources} onChange={(staffing) => onChange({ ...p, staffing })} create={() => ({ ...identity(), ...target(), ...period(), staffId: null, role: "", quantity: null, unit: "hours", capacityHours: null, hoursPerUnit: null, capacityBasis: "", costTreatment: "capacity_only", rate: null, rateBasis: "unresolved", rateStart: draft.periodStart, rateEnd: draft.periodEnd, rateNote: "", includesIndirect: false })} columns={[...targetColumns, { key: "staffId", label: "Existing staff member", kind: "select", nullable: true, options: staff }, { key: "role", label: "Unfilled role or source staffing description" }, { key: "quantity", label: "Planned quantity", kind: "number" }, { key: "unit", label: "Quantity unit", kind: "select", options: choices("hours", "fte", "person_months") }, { key: "periodStart", label: "Allocation starts", kind: "date" }, { key: "periodEnd", label: "Allocation ends", kind: "date" }, { key: "capacityHours", label: "Available person / role hours for this allocation period", kind: "number" }, { key: "hoursPerUnit", label: "Hours per FTE or person-month, explicit conversion only", kind: "number" }, { key: "capacityBasis", label: "Explicit capacity and conversion basis" }, { key: "costTreatment", label: "Use in cost totals", kind: "select", options: choices("capacity_only", "calculate") }, { key: "rate", label: `Labor cost per hour (${draft.currency})`, kind: "number" }, { key: "rateBasis", label: "Rate meaning", kind: "select", options: choices("labor_cost", "billing", "unresolved") }, { key: "rateStart", label: "Rate effective from", kind: "date" }, { key: "rateEnd", label: "Rate effective through", kind: "date" }, { key: "rateNote", label: "Rate source and cost assumptions" }, { key: "includesIndirect", label: "This labor rate already includes indirect costs", kind: "boolean" }]} />
    <Rows<Preparation["indirectPools"][number]> title="Indirect pools" rows={p.indirectPools} sources={sources} onChange={(indirectPools) => onChange({ ...p, indirectPools })} create={() => ({ ...identity(), name: "", amount: null, note: "" })} columns={[{ key: "name", label: "Indirect pool" }, { key: "amount", label: `Pool total, allocated elsewhere (${draft.currency})`, kind: "number" }, { key: "note", label: "Pool source, basis and effective period" }]} />
    <Rows<Preparation["mappings"][number]> title="Work mappings" rows={p.mappings} sources={sources} onChange={(mappings) => onChange({ ...p, mappings })} create={() => ({ ...identity(), disposition: "unresolved", targetIds: [], note: "" })} columns={[{ key: "disposition", label: "Mapping decision", kind: "select", options: choices("unresolved", "continuing", "changed", "completed", "new", "split", "merged") }, { key: "targetIds", label: "Proposed work elements", kind: "multiselect", options: elementOptions }, { key: "note", label: "Explanation of predecessor, amendment and proposed work" }]} />
    <Rows<Preparation["sourceSections"][number]> title="Material source sections" rows={p.sourceSections} sources={sources} onChange={(sourceSections) => onChange({ ...p, sourceSections })} create={() => ({ ...identity(), title: "", status: "unresolved", note: "" })} columns={[{ key: "title", label: "Program section or table" }, { key: "proposedText", label: "Editable proposed section narrative" }, { key: "retainPageImages", label: "Include original cited pages in HTML and PDF to preserve charts and table layout", kind: "boolean" }, { key: "status", label: "Treatment in proposal", kind: "select", options: choices("unresolved", "incorporated", "reference_only", "not_applicable") }, { key: "note", label: "Section review and explanation" }]} />
    <Rows<Preparation["amendments"][number]> title="Amendment relationships" rows={p.amendments} sources={sources} onChange={(amendments) => onChange({ ...p, amendments })} create={() => ({ ...identity(), amendmentSourceId: sources[0]?.id ?? "", modifiesSourceId: "", status: "unresolved", note: "" })} columns={[{ key: "amendmentSourceId", label: "Amendment source", kind: "select", options: sourceOptions }, { key: "modifiesSourceId", label: "Explicitly changes this source", kind: "select", options: sourceOptions }, { key: "status", label: "Applicability decision", kind: "select", options: choices("unresolved", "applies", "separate_cycle", "superseded") }, { key: "note", label: "Relationship and authority explanation" }]} />
    <Rows<Preparation["conflicts"][number]> title="Source conflicts" rows={p.conflicts} sources={sources} onChange={(conflicts) => onChange({ ...p, conflicts })} create={() => ({ ...identity(), description: "", resolution: "", status: "unresolved" })} columns={[{ key: "description", label: "Conflicting figures or passages" }, { key: "status", label: "Conflict state", kind: "select", options: choices("unresolved", "resolved") }, { key: "resolution", label: "Explicit resolution, or evidence still needed" }]} />
  </section>;
}
