import { chromium } from 'playwright';
const OUT = process.env.OUT_DIR;
const b = await chromium.launch({ channel: 'chrome' });
const p = await b.newPage({ viewport: { width: 1500, height: 1000 } });
p.on('console', m => { if (m.type() === 'error') console.log('CONSOLE ERROR:', m.text().slice(0,140)); });
await p.goto('http://localhost:3200/sign-in', { waitUntil: 'domcontentloaded' });
await p.getByLabel(/email/i).fill('mapaudit@openplan.test');
await p.getByLabel(/password/i).fill('MapAudit!2026');
await p.getByRole('button', { name: /sign in/i }).click();
await p.waitForURL(u => !u.pathname.includes('sign-in'), { timeout: 30000 });
await p.goto('http://localhost:3200/plans', { waitUntil: 'networkidle', timeout: 90000 });
await p.waitForTimeout(1500);
await p.screenshot({ path: `${OUT}/plans-before-open.png` });
console.log('form open on page load?', await p.getByLabel('Name').count());
await p.getByTestId('plan-creator-open').click();
await p.waitForTimeout(900);
await p.screenshot({ path: `${OUT}/plans-flow-step1.png` });
const dlg = p.locator('dialog[open]');
console.log('dialog open:', await dlg.count());
console.log('--- step 1 ---'); console.log((await dlg.innerText()).slice(0, 700));
await b.close();
