import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";
import type { ApprovedSubmittalRecoveryEntry } from "@/lib/assistant/project-submittal-recovery";
const execute=vi.hoisted(()=>vi.fn());
vi.mock("@/lib/runtime/action-registry",()=>({executeAction:execute}));
import { ApprovedSubmittalRecovery } from "@/components/assistant/approved-hold-recovery";
const fetchMock=vi.fn();
const entry:ApprovedSubmittalRecoveryEntry={approvalId:"approval-original",inputHash:"original-hash",approvedAt:"2026-09-10T00:00:00Z",expiresAt:"2099-01-01T00:00:00Z",projectName:"Synthetic original project",action:{kind:"create_project_record",projectId:"project",recordType:"submittal",title:"Synthetic original submittal",notes:"Synthetic approval notes"},receipt:null,issue:null};
const receipt:NonNullable<ApprovedSubmittalRecoveryEntry["receipt"]>={schemaVersion:1,recordType:"submittal",record:{id:"record-original",project_id:"project",title:"Synthetic original submittal",status:"draft",submittal_type:"other",notes:"Synthetic approval notes",created_by:"user",created_at:"2026-09-10T00:01:00Z",agency_label:null,assignee_user_id:null,reference_number:null,due_date:null,submitted_at:null,review_cycle:1}};
function response(items=[entry],nextOffset:number|null=null,status=200){return new Response(JSON.stringify({items,nextOffset}),{status});}
beforeEach(()=>{vi.clearAllMocks();vi.stubGlobal("fetch",fetchMock);fetchMock.mockResolvedValue(response());execute.mockImplementation(async(_action,host)=>host.onCompleted({regrounding:"none"}));});
describe("approved submittal recovery controls",()=>{
  it("identifies the original named project and creation result without claiming the record is unchanged",async()=>{fetchMock.mockResolvedValue(response([{...entry,receipt}]));render(<ApprovedSubmittalRecovery workspaceId="workspace"/>);await screen.findByText(/Synthetic original project \(name at approval\)/);expect(screen.getByText(/This is the result at creation/)).toBeVisible();expect(screen.getByText("Original status: draft. Submittal type: other.")).toBeVisible();expect(execute).not.toHaveBeenCalled()});
  it("initial and manual checks only read saved results",async()=>{render(<ApprovedSubmittalRecovery workspaceId="workspace"/>);await screen.findByText(entry.action!.notes!);fireEvent.click(screen.getByRole("button",{name:"Check saved results"}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledTimes(2));expect(execute).not.toHaveBeenCalled();for(const [url,options] of fetchMock.mock.calls){expect(url).toBe("/api/assistant/actions/submittals?workspaceId=workspace&offset=0");expect(options).toMatchObject({cache:"no-store"});expect(options.method).toBeUndefined();}});
  it("explicit resume reuses the exact consent and confirms its older receipt by ID",async()=>{fetchMock.mockResolvedValueOnce(response()).mockResolvedValueOnce(response([{...entry,receipt}]));render(<ApprovedSubmittalRecovery workspaceId="workspace"/>);fireEvent.click(await screen.findByRole("button",{name:"Resume approved submittal"}));await screen.findByText("The saved submittal and its receipt are confirmed.");expect(execute).toHaveBeenCalledWith(entry.action,expect.any(Object),{approvalEvidence:{approvalId:entry.approvalId,inputHash:entry.inputHash,executionSource:"planner_agent_quick_link"}});expect(fetchMock.mock.calls[1][0]).toContain("&approvalId=approval-original");expect(screen.queryByRole("button",{name:"Resume approved submittal"})).toBeNull();});
  it("does not claim failure or rollback when execution completes but readback fails",async()=>{fetchMock.mockResolvedValueOnce(response()).mockRejectedValueOnce(new Error("Receipt connection lost"));render(<ApprovedSubmittalRecovery workspaceId="workspace"/>);fireEvent.click(await screen.findByRole("button",{name:"Resume approved submittal"}));expect(await screen.findByRole("alert")).toHaveTextContent("The request finished, but its receipt could not be refreshed");expect(screen.queryByText("The saved submittal and its receipt are confirmed.")).toBeNull();expect(execute).toHaveBeenCalledTimes(1);});
  it("keeps an uncertain response available for a read-only check",async()=>{execute.mockRejectedValueOnce(new Error("Response lost"));render(<ApprovedSubmittalRecovery workspaceId="workspace"/>);fireEvent.click(await screen.findByRole("button",{name:"Resume approved submittal"}));expect(await screen.findByRole("alert")).toHaveTextContent("Response lost");fireEvent.click(screen.getByRole("button",{name:"Check saved results"}));await waitFor(()=>expect(fetchMock).toHaveBeenCalledTimes(2));expect(execute).toHaveBeenCalledTimes(1);});
  it.each([{...entry,expiresAt:"2000-01-01T00:00:00Z"},{...entry,receipt},{...entry,action:null,issue:"Exact request unavailable"}])("does not offer execution for expired, completed or unavailable consent %#",async(item)=>{fetchMock.mockResolvedValue(response([item]));render(<ApprovedSubmittalRecovery workspaceId="workspace"/>);await screen.findByRole("heading",{name:item.action?.title ?? "Earlier submittal approval"});expect(screen.queryByRole("button",{name:"Resume approved submittal"})).toBeNull();expect(execute).not.toHaveBeenCalled();});
  it("appends older approvals without losing current entries",async()=>{fetchMock.mockResolvedValueOnce(response([entry],20)).mockResolvedValueOnce(response([{...entry,approvalId:"older",action:{...entry.action!,title:"Older submittal"}}]));render(<ApprovedSubmittalRecovery workspaceId="workspace"/>);fireEvent.click(await screen.findByRole("button",{name:"Load older approvals"}));await screen.findByRole("heading",{name:"Older submittal"});expect(screen.getByRole("heading",{name:entry.action!.title})).toBeVisible();expect(fetchMock.mock.calls[1][0]).toContain("offset=20");expect(execute).not.toHaveBeenCalled();});
});
