import { beforeEach, describe, expect, it, vi } from "vitest";
import { NextRequest } from "next/server";
const mocks=vi.hoisted(()=>({user:vi.fn(),from:vi.fn(),rpc:vi.fn()}));
vi.mock("@/lib/supabase/server",()=>({createClient:async()=>({auth:{getUser:mocks.user},from:mocks.from}),createServiceRoleClient:()=>({rpc:mocks.rpc,from:mocks.from})}));
vi.mock("@/lib/observability/audit",()=>({createApiAuditLogger:()=>({info:vi.fn(),warn:vi.fn(),error:vi.fn()})}));
import { POST } from "@/app/api/projects/[projectId]/records/route";
import { hashAssistantActionPayload } from "@/lib/assistant/action-approval-server";
const workspaceId="11111111-1111-4111-8111-111111111111",projectId="22222222-2222-4222-8222-222222222222",userId="33333333-3333-4333-8333-333333333333",approvalId="44444444-4444-4444-8444-444444444444";
const action={kind:"create_project_record" as const,projectId,recordType:"submittal" as const,title:"Synthetic invoice backup"};
const receipt={schemaVersion:1,recordType:"submittal",record:{id:"55555555-5555-4555-8555-555555555555",project_id:projectId,title:action.title,submittal_type:"other",status:"draft",notes:null,created_by:userId,created_at:"2026-09-10T10:00:00Z",agency_label:null,assignee_user_id:null,reference_number:null,due_date:null,submitted_at:null,review_cycle:1}};
function request(change:Record<string,unknown>={},headers:Record<string,string>={}){return new NextRequest(`http://localhost/api/projects/${projectId}/records`,{method:"POST",headers:{"content-type":"application/json","x-openplan-assistant-execution-source":"planner_agent_quick_link","x-openplan-assistant-approval-id":approvalId,"x-openplan-assistant-input-hash":hashAssistantActionPayload(action),...headers},body:JSON.stringify({recordType:"submittal",title:action.title,...change})});}
const context={params:Promise.resolve({projectId})};
beforeEach(()=>{vi.clearAllMocks();mocks.user.mockResolvedValue({data:{user:{id:userId}}});mocks.from.mockImplementation(()=>{throw new Error("Separate table access must not occur in transactional path")});mocks.rpc.mockResolvedValue({data:{workspaceId,receipt},error:null});});
describe("approved submittal route",()=>{
  it("recovers the original record without current-project reads, insert, audit or consent writes",async()=>{const response=await POST(request(),context);expect(response.status).toBe(200);expect(await response.json()).toEqual({...receipt,replayed:true});expect(mocks.rpc.mock.calls.map(call=>call[0])).toEqual(["read_assistant_action_receipt"]);expect(mocks.from).not.toHaveBeenCalled()});
  it("executes only the single transaction when no receipt exists",async()=>{mocks.rpc.mockResolvedValueOnce({data:{workspaceId,receipt:null},error:null}).mockResolvedValueOnce({data:{workspaceId,receipt,replayed:false},error:null});const response=await POST(request({title:` ${action.title} `,status:"draft",submittalType:"other",notes:"  "}),context);expect(response.status).toBe(201);expect(await response.json()).toEqual({...receipt,replayed:false});expect(mocks.rpc.mock.calls.map(call=>call[0])).toEqual(["read_assistant_action_receipt","record_assistant_project_submittal"]);expect(mocks.rpc.mock.calls[1][1]).toMatchObject({p_workspace_id:workspaceId,p_user_id:userId,p_approval_id:approvalId});expect(mocks.from).not.toHaveBeenCalled()});
  it("returns an intervening concurrent receipt as replay",async()=>{mocks.rpc.mockResolvedValueOnce({data:{workspaceId,receipt:null},error:null}).mockResolvedValueOnce({data:{workspaceId,receipt,replayed:true},error:null});expect((await POST(request(),context)).status).toBe(200)});
  it.each([{title:"Changed"},{assigneeUserId:userId},{agencyLabel:"Unapproved agency"},{reviewCycle:2},{recordType:"milestone"}])("refuses altered or wider requests before receipt access %j",async change=>{expect((await POST(request(change),context)).status).toBe(403);expect(mocks.rpc).not.toHaveBeenCalled();expect(mocks.from).not.toHaveBeenCalled()});
  it("requires valid approval headers even for readback",async()=>{expect((await POST(request({}, {"x-openplan-assistant-approval-id":""}),context)).status).toBe(403);expect(mocks.rpc).not.toHaveBeenCalled()});
  it("authenticates before privileged reads",async()=>{mocks.user.mockResolvedValue({data:{user:null}});expect((await POST(request(),context)).status).toBe(401);expect(mocks.rpc).not.toHaveBeenCalled()});
  it.each(["read","write"])("does not fall back after an uncertain %s",async phase=>{if(phase==="write")mocks.rpc.mockResolvedValueOnce({data:{workspaceId,receipt:null},error:null});mocks.rpc.mockResolvedValue({data:null,error:{code:"XX000",message:"Lost database response"}});expect((await POST(request(),context)).status).toBe(503);expect(mocks.from).not.toHaveBeenCalled();expect(mocks.rpc).toHaveBeenCalledTimes(phase==="read"?1:2)});
});
