import {describe,it,expect} from "vitest";
import {randomUUID} from "node:crypto";
import {deliveryFixture} from "./fixtures/contract-delivery";
import {accountingHandoffRows,accountingHandoffCsv,type CloseoutPackage} from "@/lib/invoicing/contracts/closeout-export";
function fixture(){const f=deliveryFixture(),version=randomUUID(),entry=randomUUID(),file=randomUUID(),invoice=randomUUID(),importId=randomUUID();f.state.receivedInvoices=[{id:randomUUID(),invoice_id:invoice,version:5,state:"approved",created_at:"2026-09-08T00:00:00Z",content:{number:"SYNTH-001",date:"2026-09-08",currency:"USD",total:"25.01",fileId:file,lines:[{description:"Synthetic direct service",amount:"20.00",treatment:"direct",basis:"Retained direct service"},{description:"Synthetic indirect",amount:"5.01",treatment:"indirect",basis:"Retained agreement allocation"}]},matches:[{entryId:entry,versionId:version,amount:"25.01",staffId:f.staff,sourceKey:"SYNTH-COST-01",category:"expense",allocations:[{taskId:f.task,deliverableId:f.review,share:10000,amount:"50.02",hours:null}]}],review_note:"Synthetic approval"}];f.state.accountingImports=[{id:importId,filename:"synthetic-original.csv",source_hash:"a".repeat(64),created_at:"2026-09-08T00:00:00Z",rows:[{externalId:"SYNTH-POST-01",sourceKey:"SYNTH-COST-01",amount:"50.02",hours:null,currency:"USD"}]}];f.state.accountingReviews=[{id:randomUUID(),import_id:importId,row_index:0,version:1,actual_version_id:null,state:"unresolved",evidence:"Initial discrepancy",created_at:"2026-09-08T01:00:00Z"},{id:randomUUID(),import_id:importId,row_index:0,version:2,actual_version_id:version,state:"reconciled",evidence:"Exact retained source matched",created_at:"2026-09-08T02:00:00Z"}];const pkg:CloseoutPackage={formatVersion:2,state:f.state,request:{asOf:"2026-09-08"},position:{invoices:[],workAccepted:false,financialSettled:false,incurred:"50.02",authorizedCost:"500.00",underspend:"449.98",commitments:"0.00",warnings:[],openObligations:0}};return {...f,pkg,version,entry,file,importId};}
describe("versioned accounting handoff attribution",()=>{
 it("retains received line basis and exact source allocations without calling the full source an invoice allocation",()=>{const f=fixture(),rows=accountingHandoffRows(f.pkg);expect(rows.every(r=>r.length===25)).toBe(true);const lines=rows.filter(r=>r[0]==="received_invoice_line");expect(lines.map(r=>[r[9],r[20]])).toEqual([["20.00","direct"],["5.01","indirect"]]);expect(lines[1][15]).toContain("Retained agreement allocation");const match=rows.find(r=>r[0]==="received_cost_match")!;expect([match[3],match[9],match[12],match[16],match[17],match[18]]).toEqual([f.entry,"25.01",f.staff,"SYNTH-COST-01",f.version,f.file]);const allocation=rows.find(r=>r[0]==="received_match_source_allocation")!;expect([allocation[9],allocation[11],allocation[12],allocation[13],allocation[21],allocation[22]]).toEqual(["",f.task,f.staff,f.review,"10000","50.02"]);expect(allocation[15]).toContain("not an allocation of the matched invoice amount");expect(rows.filter(r=>r[0]==="contract_total_incurred").map(r=>r[9])).toEqual(["50.02"]);});
 it("retains original accounting identity and every review version",()=>{const f=fixture(),rows=accountingHandoffRows(f.pkg),source=rows.find(r=>r[0]==="accounting_import_row")!;expect([source[3],source[4],source[9],source[16],source[19],source[24]]).toEqual([f.importId,"SYNTH-POST-01","50.02","SYNTH-COST-01","a".repeat(64),"0"]);const reviews=rows.filter(r=>r[0]==="accounting_review_version");expect(reviews.map(r=>[r[2],r[14],r[17],r[24]])).toEqual([["1","unresolved","","0"],["2","reconciled",f.version,"0"]]);expect(accountingHandoffCsv(f.pkg)).toContain('"handoff_format"');});
 it("leaves format 1 columns and rows unchanged and marks missing older match custody explicitly",()=>{const f=fixture();const legacy=accountingHandoffRows({...f.pkg,formatVersion:1});expect(legacy.every(r=>r.length===16)).toBe(true);expect(legacy.map(r=>r[0])).toEqual(["record_type","received_invoice_version","contract_total_incurred"]);delete f.state.receivedInvoices![0].matches![0].allocations;const rows=accountingHandoffRows(f.pkg);expect(rows.filter(r=>r[0]==="received_match_source_allocation")).toHaveLength(0);expect(rows.filter(r=>r[0]==="received_cost_match")).toHaveLength(1);});
});
