import { describe,expect,it } from "vitest";
import { randomUUID } from "node:crypto";
import { deliveryFixture } from "./fixtures/contract-delivery";
import { forecastDelivery } from "@/lib/invoicing/contracts/delivery";
import { compareResponse } from "@/lib/invoicing/contracts/response";
import { contractCommandSchema } from "@/lib/invoicing/contracts/schema";
import { contractSnapshotTables } from "@/lib/invoicing/contracts/export";
import type { ResponseCommand } from "@/lib/invoicing/contracts/response-schema";
function fixture(){const f=deliveryFixture(),record={id:randomUUID(),recordType:"issue" as const,title:"Synthetic additional review work",status:"open",recordHash:"d".repeat(64),updated_at:"2026-09-08T00:00:00Z"},forecast={id:randomUUID(),version:1,input_hash:f.delivery.inputHash,content:{inputs:{},result:forecastDelivery(f.state,f.delivery,f.options),reviewEvidence:"Synthetic",coverageEvidence:"Synthetic"},created_at:record.updated_at};f.delivery.forecasts=[forecast];f.state.delivery=f.delivery;f.state.responses={records:[record],responses:[],applications:[]};const command:ResponseCommand={kind:"response",requestId:randomUUID(),forecastId:forecast.id,recordType:"issue",recordId:record.id,recordUpdatedAt:record.updated_at,recordHash:record.recordHash,schedule:structuredClone(f.schedule),workAssumptions:[],evidence:"Synthetic extra review"};return {...f,command,record,forecast};}
describe("weekly PM response comparisons",()=>{
 it("retains the reviewed baseline and separates added-work assumptions from staff acceptance",()=>{const f=fixture(),before=structuredClone(f.state);f.command.workAssumptions=[{update:{...f.delivery.workUpdates[0].content,hours:"20.01"},remainingCost:"600.01",remainingGrossBilling:"1200.02",valuationEvidence:"Synthetic additional effort valuation"}];const result=compareResponse(f.state,f.command);expect(result.before.finish).toBe("2026-09-13");expect(result.after.finish).toBe("2026-09-18");expect(result.after.warnings.map(w=>w.code)).toEqual(expect.arrayContaining(["cost_threat","fee_threat"]));expect(f.state).toEqual(before);expect(result.after.remainingCost).toBe("600.01");expect(JSON.stringify(result.inputs)).toContain("PM scenario assumption only");});
 it("refuses stale forecasts, a superseded forecast and changed project decisions",()=>{for(const mode of ["hash","forecast","record","recordHash"]){const f=fixture();if(mode==="hash")f.delivery.inputHash="changed";if(mode==="forecast")f.command.forecastId=randomUUID();if(mode==="recordHash")f.record.recordHash="e".repeat(64);if(mode==="record")f.record.updated_at="2026-09-09T00:00:00Z";expect(()=>compareResponse(f.state,f.command)).toThrow(mode.startsWith("record")?"decision changed":"current reviewed forecast");}});
 it("exposes unavailable reviewers, impossible dependencies and unrelated assumptions",()=>{const f=fixture();f.command.schedule.nodes[1].reviewStatus="unavailable";expect(compareResponse(f.state,f.command).after.finish).toBeNull();f.command.schedule.nodes[0].predecessors=[f.review];expect(()=>compareResponse(f.state,f.command)).toThrow("cycle");f.command.schedule=structuredClone(f.schedule);f.command.workAssumptions=[{update:{...f.delivery.workUpdates[0].content,staffId:randomUUID()},remainingCost:"0",remainingGrossBilling:null,valuationEvidence:"Synthetic"}];expect(()=>compareResponse(f.state,f.command)).toThrow("proposed schedule");});
 it("excludes private rate records and rejects injected calculations",()=>{const f=fixture();f.state.rates=[{id:randomUUID(),staff_id:f.staff,basis:"cost",starts_on:"2026-09-01",ends_on:"2026-10-01",hourly_rate:"123.45",source_reference:"PRIVATE SOURCE"}];expect(JSON.stringify(compareResponse(f.state,f.command).inputs)).not.toContain("PRIVATE SOURCE");expect(contractCommandSchema.safeParse({...f.command,_comparison:{after:{finish:"2026-09-08"}}}).success).toBe(false);});
 it("exports retained response assumptions and applied working decisions",()=>{const f=fixture();f.command.workAssumptions=[{update:f.delivery.workUpdates[0].content,remainingCost:"111.01",remainingGrossBilling:null,valuationEvidence:"Synthetic visible assumption"}];const id=randomUUID();f.state.responses!.responses=[{id,forecast_id:f.forecast.id,input_hash:f.delivery.inputHash,content:compareResponse(f.state,f.command),created_at:f.record.updated_at}];f.state.responses!.applications=[{id:randomUUID(),response_id:id,schedule_id:randomUUID(),evidence:"Synthetic working schedule decision",created_at:f.record.updated_at}];const tables=contractSnapshotTables({id:randomUUID(),title:"Synthetic",created_at:f.record.updated_at,snapshot_hash:"a".repeat(64),snapshot:{...f.state,schemaVersion:4,asOf:f.options.asOf,sourceCutoff:f.record.updated_at,coverageComplete:true,coverageEvidence:"Synthetic",baselineId:f.state.baselines[0].id,originalBaselineId:f.state.baselines[0].id}});expect(tables.find(t=>t.name==="PM response comparisons")?.rows[1]??[]).toContain(id);expect(JSON.stringify(tables.find(t=>t.name==="Response assumptions"))).toContain("Synthetic visible assumption");expect(JSON.stringify(tables.find(t=>t.name==="Applied working responses"))).toContain("Synthetic working schedule decision");expect(tables.some(t=>t.name==="Reviewed forecasts")).toBe(true);});
});
