import { beforeEach,describe,expect,it,vi } from "vitest";
import { randomUUID } from "node:crypto";
import { NextRequest } from "next/server";
import { deliveryFixture } from "./fixtures/contract-delivery";
const mocks=vi.hoisted(()=>({rpc:vi.fn(),getUser:vi.fn()}));
vi.mock("server-only",()=>({}));
vi.mock("@/lib/supabase/server",()=>({createClient:async()=>({auth:{getUser:mocks.getUser}}),createServiceRoleClient:()=>({rpc:mocks.rpc})}));
import { saveContractCommand } from "@/lib/invoicing/contracts/server";
const request=()=>new NextRequest("http://m11.localhost:3247/api/invoicing/engagements/synthetic/management",{method:"POST"});
describe("server calculated closeout and settlement",()=>{
 beforeEach(()=>{vi.clearAllMocks();mocks.getUser.mockResolvedValue({data:{user:{id:randomUUID()}}});});
 function context(){const f=deliveryFixture();f.state.role="finance";f.state.delivery=f.delivery;f.state.closeout={settlements:[],deliverableEvents:[],versions:[],inputHash:"c".repeat(64)};mocks.rpc.mockImplementation(async()=>({data:f.state,error:null}));const command={kind:"closeout",requestId:randomUUID(),expectedVersion:0,title:"Synthetic",asOf:"2026-09-08",coverageComplete:true,coverageEvidence:"Synthetic coverage",workAccepted:false,workAuthority:"Unassessed",financialSettled:false,financeAuthority:"Synthetic finance",obligations:[],evidence:"Synthetic decision"};return {...f,command};}
 it("computes the retained position itself and omits raw rate records from the package",async()=>{const f=context();f.state.rates=[{id:randomUUID(),staff_id:f.staff,basis:"cost",starts_on:"2026-09-01",ends_on:"2026-10-01",hourly_rate:"123.45",source_reference:"PRIVATE RATE"}];const result=await saveContractCommand(request(),f.state.engagement.id,f.command);expect(result.status).toBe(200);const write=mocks.rpc.mock.calls.find(([name])=>name==="record_contract_command")![1].p_command;expect(write._position).toMatchObject({incurred:"0.00",underspend:"500.00",workAccepted:false,financialSettled:true});expect(write._inputHash).toBe(f.state.closeout!.inputHash);expect(JSON.stringify(write._package)).not.toContain("PRIVATE RATE");expect(write._request).toEqual(f.command);});
 it("refuses a changed source set before writing or an unsupported work-acceptance claim",async()=>{const f=context();let reads=0;mocks.rpc.mockImplementation(async(name:string)=>({data:name==="read_contract_management"?{...f.state,closeout:{...f.state.closeout,inputHash:++reads<3?f.state.closeout!.inputHash:"changed"}}:f.state,error:null}));const result=await saveContractCommand(request(),f.state.engagement.id,f.command);expect(result.status).toBe(400);expect((await result.json()).error).toContain("changed during reading");expect(mocks.rpc.mock.calls.some(([name])=>name==="record_contract_command")).toBe(false);const second=context();const unsupported=await saveContractCommand(request(),second.state.engagement.id,{...second.command,workAccepted:true});expect(unsupported.status).toBe(400);expect((await unsupported.json()).error).toContain("authorized accepted deliverable");});
 it("rejects excess retention release through the real command schema and computes a partial payment",async()=>{const f=context(),invoice=randomUUID(),stamp="2026-09-08T00:00:00Z";f.state.invoices=[{id:invoice,invoice_number:"SYNTH-01",status:"sent",subtotal_amount:"100.01",retention_amount:"10.00",currency_code:"USD",invoice_date:"2026-09-01",sent_date:"2026-09-01",updated_at:stamp}];const command={kind:"settlement",requestId:randomUUID(),expectedVersion:0,content:{eventId:randomUUID(),sourceKey:"SYNTH-POST-01",direction:"outgoing",invoiceId:invoice,invoiceVersion:stamp,date:"2026-09-08",kind:"retention_release",amount:"11.00",currency:"USD",state:"recorded",documentId:randomUUID(),sourceReference:"Synthetic",correctionEvidence:"",legacyActualId:null}};const refused=await saveContractCommand(request(),f.state.engagement.id,command);expect(refused.status).toBe(400);expect(mocks.rpc.mock.calls.some(([name])=>name==="record_contract_command")).toBe(false);const accepted=await saveContractCommand(request(),f.state.engagement.id,{...command,content:{...command.content,kind:"payment",amount:"40.01"}});expect(accepted.status).toBe(200);const write=mocks.rpc.mock.calls.find(([name])=>name==="record_contract_command")![1].p_command;expect(write._position[0]).toMatchObject({open:"60.00",currentlyDue:"50.00",payments:"40.01"});});
});
