import { describe,it,expect } from "vitest";
import { randomUUID } from "node:crypto";
import { deliveryFixture } from "./fixtures/contract-delivery";
import { reconcileContract } from "@/lib/invoicing/contracts/reconciliation";
import { forecastDelivery } from "@/lib/invoicing/contracts/delivery";
import { baselineSchema,type ReceivedInvoice } from "@/lib/invoicing/contracts/schema";
function fixture(){const f=deliveryFixture();f.state.schemaVersion=6;f.state.baselines[0].content.billingDirection="received";const invoice:ReceivedInvoice={id:randomUUID(),invoice_id:randomUUID(),version:1,state:"approved",content:{number:"SYNTH-SUPPLIER",date:"2026-09-01",currency:"USD",total:"25.01",fileId:randomUUID(),lines:[{description:"Synthetic direct",amount:"25.01",treatment:"direct",basis:"Synthetic agreement"}]},review_note:"Synthetic approval",created_at:"2026-09-01T00:00:00Z"};f.state.receivedInvoices=[invoice];f.state.invoices=[{id:randomUUID(),invoice_number:"SYNTH-CLIENT",status:"sent",subtotal_amount:"90.02",retention_amount:"4.00",currency_code:"USD",invoice_date:"2026-09-01",sent_date:"2026-09-01",updated_at:"2026-09-01T00:00:00Z"}];return {...f,invoice};}
describe("approved agreement billing direction",()=>{
 it("draws agency fee from current approved supplier invoices without adding client billing or incurred cost",()=>{const f=fixture();const r=reconcileContract(f.state);expect([r.grossBilled,r.grossFeeRemaining,r.total.incurred,r.retention]).toEqual(["25.01","974.99","0.00",null]);expect(r.billingLabel).toBe("Approved supplier gross invoices");f.state.receivedInvoices!.push({...f.invoice,id:randomUUID(),version:2,content:{...f.invoice.content,total:"30.02"}});expect(reconcileContract(f.state).grossBilled).toBe("30.02");});
 it("does not infer zero from a pending correction or combine currencies",()=>{const f=fixture();f.state.receivedInvoices!.push({...f.invoice,id:randomUUID(),version:2,state:"submitted"});expect(reconcileContract(f.state).grossBilled).toBeNull();f.state.receivedInvoices!.at(-1)!.state="approved";f.state.receivedInvoices!.at(-1)!.content={...f.invoice.content,currency:"CAD"};expect(reconcileContract(f.state).currencyMismatch).toBe(true);expect(reconcileContract(f.state).grossFeeRemaining).toBeNull();});
 it("preserves issued format 5 and legacy absent-direction meanings",()=>{const f=fixture();f.state.schemaVersion=5;expect(reconcileContract(f.state).grossBilled).toBe("90.02");f.state.schemaVersion=6;delete f.state.baselines[0].content.billingDirection;expect(reconcileContract(f.state).grossBilled).toBe("90.02");});
 it("separates outgoing, internal and unassessed agreements",()=>{const f=fixture();f.state.baselines[0].content.billingDirection="outgoing";expect(reconcileContract(f.state).grossBilled).toBe("90.02");for(const direction of ["internal","unassessed"] as const){f.state.baselines[0].content.billingDirection=direction;expect(reconcileContract(f.state).grossBilled).toBeNull();f.delivery.scheduleVersions[0].content.billingTreatment="time_materials";expect(forecastDelivery(f.state,f.delivery,{asOf:"2026-09-08",horizonEnd:"2026-09-30",coverageComplete:true}).remainingGrossBilling).toBeNull();}});
 it("respects as-of dates and leaves proposed direction without authority",()=>{const f=fixture();f.invoice.content.date="2026-09-10";expect(reconcileContract(f.state,{asOf:"2026-09-08"}).grossBilled).toBe("0.00");f.state.baselines.push({...f.state.baselines[0],id:randomUUID(),version:2,state:"proposed",content:{...f.state.baselines[0].content,billingDirection:"outgoing"}});expect(reconcileContract(f.state).billingDirection).toBe("received");expect(baselineSchema.safeParse({...f.state.baselines[0].content,billingDirection:"invented"}).success).toBe(false);});
});
