import { describe,it,expect } from "vitest";
import { randomUUID } from "node:crypto";
import { deliveryFixture } from "./fixtures/contract-delivery";
import { settlementPosition,closeoutPosition } from "@/lib/invoicing/contracts/closeout";
import { accountingHandoffCsv,accountingHandoffRows } from "@/lib/invoicing/contracts/closeout-export";
import { contractCommandSchema,type ActualVersion } from "@/lib/invoicing/contracts/schema";
import type { CloseoutCommand,SettlementEvent } from "@/lib/invoicing/contracts/closeout-schema";
function fixture(){const f=deliveryFixture(),invoice=randomUUID(),document=randomUUID(),deliverable=randomUUID(),date="2026-09-08T00:00:00Z";f.state.invoices=[{id:invoice,invoice_number:"SYNTH-01",status:"sent",subtotal_amount:"100.01",retention_amount:"10.00",currency_code:"USD",invoice_date:"2026-09-01",sent_date:"2026-09-01",updated_at:date}];f.state.closeout={settlements:[],deliverableEvents:[],versions:[],inputHash:"c".repeat(64)};f.state.baselines[0].content.tasks[0].deliverableId=deliverable;const command:CloseoutCommand={kind:"closeout",requestId:randomUUID(),expectedInputHash:"c".repeat(64),expectedVersion:0,title:"Synthetic closeout",asOf:"2026-09-08",coverageComplete:true,coverageEvidence:"Synthetic complete source set",workAccepted:false,workAuthority:"Synthetic PM",financialSettled:false,financeAuthority:"Synthetic finance",obligations:[],evidence:"Synthetic decision"};
 const add=(kind:SettlementEvent["kind"],amount:string,overrides:Partial<SettlementEvent>={})=>{const event={id:randomUUID(),version:1,content:{eventId:randomUUID(),sourceKey:randomUUID(),direction:"outgoing" as const,invoiceId:invoice,invoiceVersion:date,date:"2026-09-08",kind,amount,currency:"USD",state:"recorded" as const,documentId:document,sourceReference:"Synthetic posted source",correctionEvidence:"",legacyActualId:null,...overrides},source_receipt:{id:document,checksum:"a".repeat(64),storageRef:"synthetic",bytes:100},created_at:date};f.state.closeout!.settlements.push(event);return event;};return {...f,invoice,document,deliverable,date,command,add};}
describe("documented financial settlement and closeout",()=>{
 it("reconciles partial cash, retention, disputes, credits, corrections and refunds exactly",()=>{const f=fixture();f.add("payment","50.01");f.add("dispute_open","20.00");const p=settlementPosition(f.state)[0];expect([p.open,p.currentlyDue,p.retention,p.disputed]).toEqual(["50.00","20.00","10.00","20.00"]);f.add("credit","10.00");f.add("dispute_resolve","20.00");f.add("retention_release","10.00");f.add("payment","40.00");expect(settlementPosition(f.state)[0].open).toBe("0.00");f.add("refund","5.00");expect(settlementPosition(f.state)[0].open).toBe("5.00");const debit=f.add("adjustment_debit","2.01");f.add("adjustment_credit","7.01");expect(settlementPosition(f.state)[0].open).toBe("0.00");f.state.closeout!.settlements.push({...debit,id:randomUUID(),version:2,content:{...debit.content,amount:"3.01",correctionEvidence:"Synthetic correction"}});expect(settlementPosition(f.state)[0].open).toBe("1.00");expect(f.state.actuals).toEqual([]);});
 it("counts a linked legacy payment once and exposes a changed source",()=>{const f=fixture(),entry=randomUUID();f.state.actuals=[{id:randomUUID(),entry_id:entry,version:1,command:{invoiceId:f.invoice,category:"payment",status:"approved",entryDate:"2026-09-08"},amount:"25.01"} as ActualVersion];f.add("payment","25.01",{legacyActualId:entry});expect(settlementPosition(f.state)[0].payments).toBe("25.01");f.state.actuals[0].amount="30.01";const p=settlementPosition(f.state)[0];expect(p.payments).toBe("30.01");expect(p.warnings).toContain("Linked legacy payment or credit changed or is missing.");});
 it("keeps received payables separate and refuses wrong currency or unsupported releases",()=>{const f=fixture();f.state.receivedInvoices=[{id:randomUUID(),invoice_id:randomUUID(),version:3,state:"approved",content:{number:"SYNTH-VENDOR",date:"2026-09-01",currency:"USD",total:"77.07",fileId:f.document,lines:[{description:"Synthetic indirect cost",amount:"77.07",treatment:"indirect",basis:"Synthetic agreement basis"}]},review_note:"Synthetic",created_at:f.date}];expect(settlementPosition(f.state).find(i=>i.direction==="received")?.open).toBe("77.07");f.add("retention_release","11.00");expect(settlementPosition(f.state)[0].warnings.join(" ")).toContain("exceeds");f.add("payment","1.00",{currency:"CAD"});expect(()=>settlementPosition(f.state)).toThrow("currency");});
 it("allows underspend and zero-dollar settlement with a retained continuing obligation",()=>{const f=fixture();f.state.invoices=[];f.state.closeout!.deliverableEvents=[{id:randomUUID(),version:2,deliverable_id:f.deliverable,state:"accepted",date:"2026-09-08",authority:"Synthetic designated PM",evidence:"Synthetic accepted artifact",source_receipt:{id:f.document,checksum:"a".repeat(64),storageRef:"synthetic",bytes:100},created_at:f.date}];f.command.workAccepted=true;f.command.financialSettled=true;f.command.obligations=[{id:randomUUID(),title:"Retain records",owner:"Synthetic agency",dueOn:null,status:"open",basis:"Synthetic continuing condition"}];const p=closeoutPosition(f.state,f.command);expect(p).toMatchObject({workAccepted:true,financialSettled:true,incurred:"0.00",underspend:"500.00",openObligations:1});});
 it("refuses unsupported work acceptance, unresolved finances and missing coverage",()=>{const f=fixture();expect(()=>closeoutPosition(f.state,{...f.command,workAccepted:true})).toThrow("authorized accepted deliverable");expect(()=>closeoutPosition(f.state,{...f.command,financialSettled:true})).toThrow("unresolved source coverage");f.state.invoices=[];expect(()=>closeoutPosition(f.state,{...f.command,coverageComplete:false,financialSettled:true})).toThrow("Financial settlement");});
 it("retains stable handoff identities and protects spreadsheet cells without changing exact amount strings",()=>{const f=fixture();const event=f.add("payment","50.01",{sourceKey:"=SYNTHETIC_FORMULA",sourceReference:"Synthetic quoted \"source\""}),position=closeoutPosition(f.state,f.command),pkg={formatVersion:1 as const,state:f.state,position,request:f.command};const rows=accountingHandoffRows(pkg);expect(rows.find(r=>r[0]==="financial_payment")?.slice(1,5)).toEqual([event.id,"1",event.content.eventId,"=SYNTHETIC_FORMULA"]);const csv=accountingHandoffCsv(pkg);expect(csv).toContain('"\'=SYNTHETIC_FORMULA"');expect(csv).toContain('"50.01"');expect(csv).toContain('"invoice_total_open"');expect(csv).toContain('"contract_total_incurred"');expect(contractCommandSchema.safeParse({...f.command,_position:{financialSettled:true}}).success).toBe(false);});
});
