import {describe,it,expect} from "vitest";
import {randomUUID} from "node:crypto";
import {deliveryFixture} from "./fixtures/contract-delivery";
import {accountingHandoffRows,accountingHandoffCsv,type CloseoutPackage} from "@/lib/invoicing/contracts/closeout-export";
import {contractSnapshotTables,contractSnapshotWorkbook} from "@/lib/invoicing/contracts/export";
import type {ContractSnapshot} from "@/lib/invoicing/contracts/schema";
import {utils} from "xlsx";
function fixture(){const f=deliveryFixture(),version=randomUUID(),entry=randomUUID(),file=randomUUID(),invoice=randomUUID(),importId=randomUUID();f.state.receivedInvoices=[{id:randomUUID(),invoice_id:invoice,version:5,state:"approved",created_at:"2026-09-08T00:00:00Z",content:{number:"SYNTH-001",date:"2026-09-08",currency:"USD",total:"25.01",fileId:file,lines:[{description:"Synthetic direct service",amount:"20.00",treatment:"direct",basis:"Retained direct service"},{description:"Synthetic indirect",amount:"5.01",treatment:"indirect",basis:"Retained agreement allocation"}]},matches:[{entryId:entry,versionId:version,amount:"25.01",staffId:f.staff,sourceKey:"SYNTH-COST-01",category:"expense",allocations:[{taskId:f.task,deliverableId:f.review,share:10000,amount:"50.02",hours:null}]}],review_note:"Synthetic approval"}];f.state.accountingImports=[{id:importId,filename:"synthetic-original.csv",source_hash:"a".repeat(64),created_at:"2026-09-08T00:00:00Z",rows:[{externalId:"SYNTH-POST-01",sourceKey:"SYNTH-COST-01",amount:"50.02",hours:null,currency:"USD"}]}];f.state.accountingReviews=[{id:randomUUID(),import_id:importId,row_index:0,version:1,actual_version_id:null,state:"unresolved",evidence:"Initial discrepancy",created_at:"2026-09-08T01:00:00Z"},{id:randomUUID(),import_id:importId,row_index:0,version:2,actual_version_id:version,state:"reconciled",evidence:"Exact retained source matched",created_at:"2026-09-08T02:00:00Z"}];const pkg:CloseoutPackage={formatVersion:2,state:f.state,request:{asOf:"2026-09-08"},position:{invoices:[],workAccepted:false,financialSettled:false,incurred:"50.02",authorizedCost:"500.00",underspend:"449.98",commitments:"0.00",warnings:[],openObligations:0}};return {...f,pkg,version,entry,file,importId};}
describe("versioned accounting handoff attribution",()=>{
 it("retains received line basis and exact source allocations without calling the full source an invoice allocation",()=>{const f=fixture(),rows=accountingHandoffRows(f.pkg);expect(rows.every(r=>r.length===25)).toBe(true);const lines=rows.filter(r=>r[0]==="received_invoice_line");expect(lines.map(r=>[r[9],r[20]])).toEqual([["20.00","direct"],["5.01","indirect"]]);expect(lines[1][15]).toContain("Retained agreement allocation");const match=rows.find(r=>r[0]==="received_cost_match")!;expect([match[3],match[9],match[12],match[16],match[17],match[18]]).toEqual([f.entry,"25.01",f.staff,"SYNTH-COST-01",f.version,f.file]);const allocation=rows.find(r=>r[0]==="received_match_source_allocation")!;expect([allocation[9],allocation[11],allocation[12],allocation[13],allocation[21],allocation[22]]).toEqual(["",f.task,f.staff,f.review,"10000","50.02"]);expect(allocation[15]).toContain("not an allocation of the matched invoice amount");expect(rows.filter(r=>r[0]==="contract_total_incurred").map(r=>r[9])).toEqual(["50.02"]);});
 it("retains original accounting identity and every review version",()=>{const f=fixture(),rows=accountingHandoffRows(f.pkg),source=rows.find(r=>r[0]==="accounting_import_row")!;expect([source[3],source[4],source[9],source[16],source[19],source[24]]).toEqual([f.importId,"SYNTH-POST-01","50.02","SYNTH-COST-01","a".repeat(64),"0"]);const reviews=rows.filter(r=>r[0]==="accounting_review_version");expect(reviews.map(r=>[r[2],r[14],r[17],r[24]])).toEqual([["1","unresolved","","0"],["2","reconciled",f.version,"0"]]);expect(accountingHandoffCsv(f.pkg)).toContain('"handoff_format"');});
 it("leaves format 1 columns and rows unchanged and marks missing older match custody explicitly",()=>{const f=fixture();const legacy=accountingHandoffRows({...f.pkg,formatVersion:1});expect(legacy.every(r=>r.length===16)).toBe(true);expect(legacy.map(r=>r[0])).toEqual(["record_type","received_invoice_version","contract_total_incurred"]);delete f.state.receivedInvoices![0].matches![0].allocations;const rows=accountingHandoffRows(f.pkg);expect(rows.filter(r=>r[0]==="received_match_source_allocation")).toHaveLength(0);expect(rows.filter(r=>r[0]==="received_cost_match")).toHaveLength(1);});
});

describe("source receipts and readable current management position",()=>{
 it("retains received original checksums only in the new package format",()=>{
  const f=fixture(),invoice=f.state.receivedInvoices![0];invoice.source_receipt={id:f.file,filename:"synthetic-original.txt",checksum:"d".repeat(64),contentType:"text/plain",bytes:123};
  const old=accountingHandoffRows(f.pkg),rows=accountingHandoffRows({...f.pkg,formatVersion:3});
  expect(old.find(r=>r[0]==="received_invoice_line")![19]).toBe("");expect(old.some(r=>r[0]==="received_file_receipt")).toBe(false);
  for(const kind of ["received_invoice_line","received_cost_match","received_match_source_allocation","received_file_receipt"])expect(rows.filter(r=>r[0]===kind).map(r=>r[19])).toEqual(Array(rows.filter(r=>r[0]===kind).length).fill("d".repeat(64)));
  expect(rows.find(r=>r[0]==="received_file_receipt")![15]).toContain("123 bytes");
  delete invoice.source_receipt;expect(accountingHandoffRows({...f.pkg,formatVersion:3}).find(r=>r[0]==="received_invoice_line")![19]).toBe("unassessed");
 });
 it("shows documented cash up front without duplicate legacy rollup columns and preserves earlier formats",()=>{
  const f=fixture();f.state.schemaVersion=7;const invoice=f.state.receivedInvoices![0];
  f.state.closeout={inputHash:"e".repeat(64),versions:[],deliverableEvents:[{id:randomUUID(),deliverable_id:f.review,version:1,state:"submitted",date:"2026-09-08",authority:"Synthetic PM",evidence:"Synthetic",source_receipt:{id:f.file,checksum:"d".repeat(64),storageRef:"storage://synthetic/report.txt",bytes:123},created_at:"2026-09-08"}],settlements:[{id:randomUUID(),version:1,content:{eventId:randomUUID(),sourceKey:"SYNTH-PAYMENT",direction:"received",invoiceId:invoice.invoice_id,invoiceVersion:"5",date:"2026-09-08",kind:"payment",amount:"24.00",currency:"USD",state:"recorded",documentId:f.file,sourceReference:"Synthetic payment receipt",correctionEvidence:"",legacyActualId:null},source_receipt:{id:f.file,checksum:"d".repeat(64),storageRef:"synthetic",bytes:123},created_at:"2026-09-08"}]};
  const report:ContractSnapshot={id:randomUUID(),title:"Synthetic",created_at:"2026-09-08",snapshot_hash:"f".repeat(64),snapshot:{...f.state,asOf:"2026-09-08",sourceCutoff:"2026-09-08T12:00:00Z",coverageComplete:true,coverageEvidence:"Synthetic",baselineId:f.state.baselines[0].id,originalBaselineId:f.state.baselines[0].id}};
  const tables=contractSnapshotTables(report);expect(tables[1].name).toBe("Current invoice position");expect(tables[1].rows).toContainEqual(["SYNTH-001 / received","payments","24.00 USD"]);
  expect(tables.find(t=>t.name==="Contract totals")!.rows[0]).not.toContain("payments");expect(tables.find(t=>t.name==="Contract totals")!.rows[0]).not.toContain("credits");
  const acceptance=tables.find(t=>t.name==="Deliverable acceptance")!;expect(acceptance.rows[0].slice(-2)).toEqual(["Storage reference","Retained bytes"]);expect(acceptance.rows[1].slice(-2)).toEqual(["storage://synthetic/report.txt",123]);
  report.snapshot.schemaVersion=6;const old=contractSnapshotTables(report);expect(old.some(t=>t.name==="Current invoice position")).toBe(false);expect(old.find(t=>t.name==="Contract totals")!.rows[0]).toContain("payments");expect(old.find(t=>t.name==="Deliverable acceptance")!.rows[1].at(-1)).toBe("storage://synthetic/report.txt");
 });
 it("keeps one accounting row per stable record in the new workbook",()=>{
  const f=fixture();f.state.receivedInvoices![0].review_note="Synthetic long accounting evidence ".repeat(30);f.state.receivedInvoices![0].content.number="00123.00";f.state.accountingImports![0].rows[0].externalId="00045.00";f.state.accountingImports![0].rows[0].sourceKey="00067.00";f.pkg.formatVersion=3;
  const request={kind:"closeout" as const,requestId:randomUUID(),expectedInputHash:"e".repeat(64),expectedVersion:0,title:"Synthetic closeout",asOf:"2026-09-08",coverageComplete:true,coverageEvidence:"Synthetic",workAccepted:false,workAuthority:"Synthetic PM",financialSettled:false,financeAuthority:"Synthetic finance",obligations:[],evidence:"Synthetic"};
  const state={...f.state,schemaVersion:7 as const,closeout:{settlements:[],deliverableEvents:[],inputHash:"a".repeat(64),versions:[{id:randomUUID(),version:1,state:"closed" as const,previous_id:null,input_hash:"a".repeat(64),content:{request,package:f.pkg},content_hash:"b".repeat(64),created_at:"2026-09-08"}]}};
  const report:ContractSnapshot={id:randomUUID(),title:"Synthetic",created_at:"2026-09-08",snapshot_hash:"c".repeat(64),snapshot:{...state,asOf:"2026-09-08",sourceCutoff:"2026-09-08T12:00:00Z",coverageComplete:true,coverageEvidence:"Synthetic",baselineId:f.state.baselines[0].id,originalBaselineId:f.state.baselines[0].id}};
  const book=contractSnapshotWorkbook(report),rows=utils.sheet_to_json<unknown[]>(book.Sheets["Accounting handoff"],{header:1});
  expect(rows).toHaveLength(accountingHandoffRows(f.pkg).length);expect(rows.find(r=>r[0]==="received_invoice_version")![4]).toBe("00123.00");expect(rows.find(r=>r[0]==="accounting_import_row")!.slice(4,5)).toEqual(["00045.00"]);expect(rows.find(r=>r[0]==="accounting_import_row")![16]).toBe("00067.00");expect(rows.find(r=>r[0]==="received_invoice_version")![9]).toBe(25.01);expect(rows.find(r=>r[0]==="received_invoice_version")![15]).toBe(f.state.receivedInvoices![0].review_note);
  expect(book.Sheets["Approved task budgets"].C2).toMatchObject({t:"n",v:Number(f.state.baselines[0].content.tasks[0].cost)});expect(book.Sheets["Received invoices"].B2).toMatchObject({t:"s",v:"00123.00"});expect(book.Sheets["Closeout position"].B3).toMatchObject({t:"n",v:1,z:"0"});
  const details=utils.sheet_to_json<unknown[]>(book.Sheets["Accounting text details"],{header:1}).slice(1).filter(row=>row[0]===f.state.receivedInvoices![0].id&&row[1]==="evidence");
  expect(details.map(row=>row[4]).join("")).toBe(f.state.receivedInvoices![0].review_note);expect(details.map(row=>row[2])).toEqual(details.map((_,index)=>index+1));expect(book.Sheets["Accounting handoff"].P2.l?.Target).toBe("#'Accounting text details'!A2");

 });
});
