import {describe,it,expect} from 'vitest';
import type {SupabaseClient} from '@supabase/supabase-js';
import {publicReviewStillCurrent} from '@/lib/engagement/survey-responses';
import type {EngagementReviewSnapshot} from '@/lib/engagement/review-export';
const source:EngagementReviewSnapshot={schema:1,capturedAt:'2026-09-06',scope:'public',filters:{},campaign:{id:'campaign',title:'Demonstration',summary:null,configurationVersionId:null},items:[{id:'reply',parent_item_id:'parent',title:null,body:'Reviewed reply',status:'approved',submitted_by:null,photo_path:null,geometry:null,latitude:null,longitude:null,category_id:null}],sessions:[{id:'session',status:'approved'}],answers:[{id:'answer',session_id:'session',question_id:'q',question_prompt_snapshot:'Question then',question_type:'free_text',answer_text:'Reviewed answer',answer_json:{text:'Reviewed answer'}}],responses:[{id:'response',status:'published',theme_title:'Theme',you_said:'Reviewed reply',we_did:'Reviewed response',source_item_ids:['reply']}],definitions:[]};
function client(change?:{table:string;id:string;values:Record<string,unknown>},fail?:string){
 const rows:Record<string,Record<string,unknown>[]>={engagement_items:[...source.items,{id:'parent',parent_item_id:null,status:'approved'}],engagement_survey_response_sessions:source.sessions,engagement_survey_answers:source.answers,engagement_closeloop_entries:source.responses};
 const reads:Array<{table:string;projection:string;campaign:string;ids:string[]}>=[];
 return {reads,service:{from(table:string){return {select(projection:string){return {eq(column:string,campaign:string){expect(column).toBe('campaign_id');return {async in(idColumn:string,ids:string[]){expect(idColumn).toBe('id');reads.push({table,projection,campaign,ids});return {error:table===fail?{message:'read refused'}:null,data:rows[table].filter(row=>ids.includes(String(row.id))).map(row=>change?.table===table&&change.id===row.id?{...row,...change.values}:row)};}};}};}};}} as unknown as SupabaseClient};
}
describe('public report withdrawal',()=>{
 it('permits unchanged reviewed copies and checks exact projections and campaign scopes',async()=>{const {service,reads}=client();expect(await publicReviewStillCurrent(service,source)).toBe(true);expect(reads).toHaveLength(5);expect(reads.every(row=>row.campaign==='campaign')).toBe(true);expect(reads.find(row=>row.table==='engagement_survey_answers')?.projection.split(',')).toContain('answer_json');expect(reads.find(row=>row.table==='engagement_items')?.projection.split(',')).toContain('body');});
 for(const change of [{table:'engagement_items',id:'reply',values:{body:'Redacted'}},{table:'engagement_items',id:'parent',values:{status:'rejected'}},{table:'engagement_survey_response_sessions',id:'session',values:{status:'rejected'}},{table:'engagement_survey_answers',id:'answer',values:{answer_json:{reviewed_redaction:'Removed'}}},{table:'engagement_closeloop_entries',id:'response',values:{we_did:'Revised response'}}])it(`withdraws after ${change.table} ${change.id} changes`,async()=>{expect(await publicReviewStillCurrent(client(change).service,source)).toBe(false);});
 it('refuses a failed current-copy read',async()=>{expect(await publicReviewStillCurrent(client(undefined,'engagement_survey_answers').service,source)).toBe(false);});
});
