import {beforeEach,describe,it,expect,vi} from 'vitest';import type {SupabaseClient} from '@supabase/supabase-js';
const m=vi.hoisted(()=>({download:vi.fn(),single:vi.fn(),select:vi.fn(),eq:vi.fn()}));vi.mock('@/lib/engagement/review-export-download',()=>({downloadEngagementReview:m.download}));import {engagementBundleFilesAvailable} from '@/lib/engagement/review-bundle-access';
const entry={inclusion:{status:'included'},originalRecord:{sourceId:'report_artifacts',recordId:'artifact'},checksumSha256:'hash'},project={id:'project',workspace_id:'workspace'};const chain={select:m.select,eq:m.eq,maybeSingle:m.single},caller={from:()=>chain} as unknown as SupabaseClient;
beforeEach(()=>{vi.clearAllMocks();m.select.mockReturnValue(chain);m.eq.mockReturnValue(chain);m.single.mockResolvedValue({data:{report_id:'report',storage_path:'saved.pdf',metadata_json:{engagementReviewJobId:'job',sha256:'hash'}},error:null});m.download.mockResolvedValue(new Response('PDF'));});
describe('containing project bundle preserves engagement disclosure',()=>{
 it('rechecks exact original artifact under caller workspace and project scope',async()=>{expect(await engagementBundleFilesAvailable(caller,{entries:[entry]},project)).toBe(true);expect(m.select).toHaveBeenCalledWith('id,report_id,storage_path,metadata_json,reports!inner(workspace_id,project_id)');expect(m.eq).toHaveBeenCalledWith('reports.workspace_id','workspace');expect(m.eq).toHaveBeenCalledWith('reports.project_id','project');expect(m.download).toHaveBeenCalledWith(caller,'job','pdf',{reportId:'report',artifact:{path:'saved.pdf',checksum:'hash'}});});
 it('refuses a withheld or newly redacted contained report',async()=>{m.download.mockResolvedValue(new Response('',{status:404}));expect(await engagementBundleFilesAvailable(caller,{entries:[entry]},project)).toBe(false);});
 it('refuses inaccessible artifact metadata and never uses service access to bypass it',async()=>{m.single.mockResolvedValue({data:null,error:null});expect(await engagementBundleFilesAvailable(caller,{entries:[entry]},project)).toBe(false);expect(m.download).not.toHaveBeenCalled();});
 it('refuses a different retained rendering even when its report is readable',async()=>{expect(await engagementBundleFilesAvailable(caller,{entries:[{...entry,checksumSha256:'another'}]},project)).toBe(false);expect(m.download).not.toHaveBeenCalled();});
 it('allows unchanged ordinary bundles without inventing an engagement dependency',async()=>{expect(await engagementBundleFilesAvailable(caller,{entries:[]},project)).toBe(true);expect(m.select).not.toHaveBeenCalled();});
});
