import {beforeEach,describe,it,expect,vi} from 'vitest';import type {SupabaseClient} from '@supabase/supabase-js';
const m=vi.hoisted(()=>({download:vi.fn(),single:vi.fn(),select:vi.fn(),eq:vi.fn(),or:vi.fn(),coverage:vi.fn()}));vi.mock('@/lib/engagement/campaign-projects',()=>({loadProjectCampaignsForEvidence:m.coverage}));vi.mock('@/lib/engagement/review-export-download',()=>({downloadEngagementReview:m.download}));import {engagementBundleFilesAvailable} from '@/lib/engagement/review-bundle-access';
const entry={inclusion:{status:'included'},originalRecord:{sourceId:'report_artifacts',recordId:'artifact'},checksumSha256:'hash'},project={id:'project',workspace_id:'workspace'};const chain={select:m.select,eq:m.eq,or:m.or,maybeSingle:m.single},caller={from:()=>chain} as unknown as SupabaseClient;
beforeEach(()=>{vi.clearAllMocks();m.select.mockReturnValue(chain);m.eq.mockReturnValue(chain);m.or.mockReturnValue(chain);m.coverage.mockResolvedValue({data:[{id:"covered-campaign"}],error:null});m.single.mockResolvedValue({data:{reports:{workspace_id:'workspace',project_id:null,engagement_campaign_id:'covered-campaign'},report_id:'report',storage_path:'saved.pdf',metadata_json:{engagementReviewJobId:'job',sha256:'hash'}},error:null});m.download.mockResolvedValue(new Response('PDF'));});
describe('containing project bundle preserves engagement disclosure',()=>{
 it('rechecks exact original artifact under caller workspace and project scope',async()=>{expect(await engagementBundleFilesAvailable(caller,{entries:[entry]},project)).toBe(true);expect(m.select).toHaveBeenCalledWith('id, report_id, artifact_kind, storage_path, generated_at, metadata_json, reports!inner(workspace_id, project_id, engagement_campaign_id, title)');expect(m.eq).toHaveBeenCalledWith('reports.workspace_id','workspace');expect(m.or).toHaveBeenCalledWith('project_id.eq.project,engagement_campaign_id.in.(covered-campaign)',{referencedTable:'reports'});expect(m.download).toHaveBeenCalledWith(caller,'job','pdf',{reportId:'report',artifact:{path:'saved.pdf',checksum:'hash'}});});
 it('refuses incomplete coverage before reading artifact bytes',async()=>{m.coverage.mockResolvedValue({data:null,error:{message:'coverage unavailable'}});expect(await engagementBundleFilesAvailable(caller,{entries:[entry]},project)).toBe(false);expect(m.single).not.toHaveBeenCalled();expect(m.download).not.toHaveBeenCalled();});
 it('refuses a withheld or newly redacted contained report',async()=>{m.download.mockResolvedValue(new Response('',{status:404}));expect(await engagementBundleFilesAvailable(caller,{entries:[entry]},project)).toBe(false);});
 it('refuses inaccessible artifact metadata and never uses service access to bypass it',async()=>{m.single.mockResolvedValue({data:null,error:null});expect(await engagementBundleFilesAvailable(caller,{entries:[entry]},project)).toBe(false);expect(m.download).not.toHaveBeenCalled();});
 it('refuses a different retained rendering even when its report is readable',async()=>{expect(await engagementBundleFilesAvailable(caller,{entries:[{...entry,checksumSha256:'another'}]},project)).toBe(false);expect(m.download).not.toHaveBeenCalled();});
 it('allows unchanged ordinary bundles without inventing an engagement dependency',async()=>{expect(await engagementBundleFilesAvailable(caller,{entries:[]},project)).toBe(true);expect(m.select).not.toHaveBeenCalled();});
});
