import {beforeEach,describe,it,expect,vi} from 'vitest';import {NextRequest} from 'next/server';
const m=vi.hoisted(()=>({getUser:vi.fn(),access:vi.fn(),from:vi.fn(),download:vi.fn(),single:vi.fn(),select:vi.fn(),eq:vi.fn()}));
vi.mock('@/lib/supabase/server',()=>({createClient:async()=>({auth:{getUser:m.getUser},from:m.from}),createServiceRoleClient:()=>({from:m.from,storage:{from:()=>({download:m.download})}})}));
vi.mock('@/lib/engagement/api',()=>({loadCampaignAccess:m.access}));vi.mock('@/lib/observability/audit',()=>({createApiAuditLogger:()=>({info:vi.fn()})}));
import {GET} from '@/app/api/engagement/campaigns/[campaignId]/attachments/route';
const campaign='11111111-1111-4111-8111-111111111111',session='22222222-2222-4222-8222-222222222222',answer='33333333-3333-4333-8333-333333333333',path=`${campaign}/44444444-4444-4444-8444-444444444444.jpg`;
const call=(query=`sessionId=${session}&answerId=${answer}`)=>GET(new NextRequest(`http://localhost/api/engagement/campaigns/${campaign}/attachments?${query}`),{params:Promise.resolve({campaignId:campaign})});
beforeEach(()=>{vi.clearAllMocks();m.getUser.mockResolvedValue({data:{user:{id:'staff'}}});m.access.mockResolvedValue({allowed:true,error:null});const chain={select:m.select,eq:m.eq,maybeSingle:m.single};m.from.mockReturnValue(chain);m.select.mockReturnValue(chain);m.eq.mockReturnValue(chain);m.single.mockResolvedValue({data:{answer_json:{files:[{path}]}},error:null});m.download.mockResolvedValue({data:new Blob([new Uint8Array([255,216,255,0])]),error:null});});
describe('staff attachment access',()=>{
 it('reads the exact answer and session only after staff authorization, with no reusable signed URL',async()=>{const response=await call();expect(response.status).toBe(200);expect(m.access).toHaveBeenCalledWith(expect.anything(),campaign,'staff','engagement.write');expect(m.select).toHaveBeenCalledWith('answer_json');expect(m.eq).toHaveBeenCalledWith('id',answer);expect(m.eq).toHaveBeenCalledWith('session_id',session);expect(m.eq).toHaveBeenCalledWith('campaign_id',campaign);expect(m.download).toHaveBeenCalledWith(path);expect(response.headers.get('cache-control')).toBe('private, no-store');});
 for(const label of ['viewer','revoked','outside workspace'])it(`refuses ${label} before reading originals`,async()=>{m.access.mockResolvedValue({allowed:false,error:null});expect((await call()).status).toBe(404);expect(m.from).not.toHaveBeenCalled();expect(m.download).not.toHaveBeenCalled();});
 it('refuses anonymous access',async()=>{m.getUser.mockResolvedValue({data:{user:null}});expect((await call()).status).toBe(404);expect(m.access).not.toHaveBeenCalled();});
 it('refuses an attachment from another campaign',async()=>{m.single.mockResolvedValue({data:{answer_json:{files:[{path:path.replace(campaign,session)}]}},error:null});expect((await call()).status).toBe(404);expect(m.download).not.toHaveBeenCalled();});
 it('refuses removed current files and failed reads',async()=>{m.single.mockResolvedValue({data:{answer_json:{reviewed_redaction:'Withheld'}},error:null});expect((await call()).status).toBe(404);m.single.mockResolvedValue({data:null,error:{message:'Unavailable'}});expect((await call()).status).toBe(404);expect(m.download).not.toHaveBeenCalled();});
 it('scopes historical originals by campaign, response and history identity',async()=>{m.single.mockResolvedValue({data:{before_json:{answers:[{id:answer,answer_json:{files:[{path}]}}]}},error:null});expect((await call(`sessionId=${session}&answerId=${answer}&historyId=${answer}`)).status).toBe(200);expect(m.from).toHaveBeenCalledWith('engagement_survey_review_history');expect(m.eq).toHaveBeenCalledWith('id',answer);expect(m.eq).toHaveBeenCalledWith('session_id',session);expect(m.eq).toHaveBeenCalledWith('campaign_id',campaign);});
});
