import { describe, expect, it } from "vitest";
import { readGtfsClientProgress, readGtfsClientReview } from "@/lib/gtfs/managed-progress";
const id = (n: number) => `e3000000-0000-4000-8000-${String(n).padStart(12, "0")}`;
const scope = { workspaceId: id(1), requestId: id(2) };
const status = { schemaVersion: 1, workspaceId: id(1), requestId: id(2), versionId: id(3), feedId: id(4), state: "queued", stage: "pending", attempts: 0, leaseUntil: null, archiveConfirmed: false, submittedAt: "2026-10-10T12:00:00Z", isCurrent: false, failureCode: null, failureDetail: null, submitterAccessUnavailable: false };
const body = { managed: true, requestId: id(2), status, cancellation: null };
const cancellation = { command: id(5), workspaceId: id(1), requestId: id(2), state: "cancelled", versionId: null, versionCancellation: null, cancelledAt: "2026-10-10T12:00:00Z" };
const basis = { feedId: id(4), versionId: id(3), routeCount: 14, stopCount: 287, previousVersionId: null, previousRouteCount: null, previousStopCount: null };
const review = { managed: true, review: { basis, materialShrinkage: false, isCurrent: false } };
describe("transit browser progress boundaries", () => {
 it("keeps queued, missing and early cancelled distinct without claiming adoption", () => { expect(readGtfsClientProgress(body, scope)).toEqual({ status, cancellation: null }); expect(readGtfsClientProgress({ ...body, status: null }, scope)).toEqual({ status: null, cancellation: null }); expect(readGtfsClientProgress({ ...body, status: null, cancellation }, scope)).toEqual({ status: null, cancellation }); });
 it.each(["requestId", "workspaceId"])("refuses changed public status %s", field => { expect(() => readGtfsClientProgress({ ...body, status: { ...status, [field]: id(90) } }, scope)).toThrow("scope differs"); });
 it("refuses a different outer request and private fields", () => { expect(() => readGtfsClientProgress({ ...body, requestId: id(90) }, scope)).toThrow("request differs"); expect(() => readGtfsClientProgress({ ...body, status: { ...status, token: id(90) } }, scope)).toThrow(); });
 it("requires a completed stage and archive before showing ready", () => { expect(() => readGtfsClientProgress({ ...body, status: { ...status, state: "ready", archiveConfirmed: true } }, scope)).toThrow("stage or current"); expect(() => readGtfsClientProgress({ ...body, status: { ...status, state: "ready", stage: "ready" } }, scope)).toThrow("stage or current"); expect(readGtfsClientProgress({ ...body, status: { ...status, state: "ready", stage: "ready", archiveConfirmed: true } }, scope).status?.isCurrent).toBe(false); });
 it("requires a failure code and does not treat queued as current", () => { expect(() => readGtfsClientProgress({ ...body, status: { ...status, state: "failed", stage: "failed" } }, scope)).toThrow("stage or current"); expect(() => readGtfsClientProgress({ ...body, status: { ...status, isCurrent: true } }, scope)).toThrow("stage or current"); });
 it("requires active ownership evidence and no lease for inactive jobs", () => { expect(() => readGtfsClientProgress({ ...body, status: { ...status, state: "running" } }, scope)).toThrow("ownership"); expect(() => readGtfsClientProgress({ ...body, status: { ...status, leaseUntil: "2026-10-10T12:02:00Z" } }, scope)).toThrow("ownership"); });
 it("accepts a running attempt and a known cancelled version without inventing adoption", () => { const running = { ...status, state: "running", stage: "parsing", attempts: 1, leaseUntil: "2026-10-10T12:02:00Z" }; expect(readGtfsClientProgress({ ...body, status: running }, scope).status).toEqual(running); const closed = { ...status, state: "cancelled", stage: "failed", failureCode: "abandoned" }; expect(readGtfsClientProgress({ ...body, status: closed, cancellation: { ...cancellation, versionId: id(3) } }, scope).status).toEqual(closed); });
 it.each(["requestId", "workspaceId"])("refuses changed cancellation %s", field => { expect(() => readGtfsClientProgress({ ...body, status: null, cancellation: { ...cancellation, [field]: id(90) } }, scope)).toThrow("scope differs"); });
 it("refuses a cancellation claiming another version closure", () => { const terminal = { command: id(5), version: id(90), state: "cancelled", closure: { recorded: true, feedStatusChanged: false }, cleanupPending: false, closedAt: "2026-10-10T12:00:00Z" }; expect(() => readGtfsClientProgress({ ...body, status: null, cancellation: { ...cancellation, versionId: id(3), versionCancellation: terminal } }, scope)).toThrow("closure differs"); });
 it("refuses conflicting cancellation and active processing", () => { expect(() => readGtfsClientProgress({ ...body, cancellation }, scope)).toThrow("processing differ"); });
 it("refuses unavailable response bodies and invalid local scope", () => { expect(() => readGtfsClientProgress({ error: "unavailable" }, scope)).toThrow(); expect(() => readGtfsClientProgress({ ...body, requestId: "invalid", status: null }, { ...scope, requestId: "invalid" })).toThrow(); expect(() => readGtfsClientProgress({ ...body, managed: false }, scope)).toThrow(); });
});
describe("transit browser review boundaries", () => {
 it("reads exact completed counts without inventing a predecessor", () => { expect(readGtfsClientReview(review, { feedId: id(4), versionId: id(3) })).toEqual(review.review); });
 it.each(["feedId", "versionId"])("refuses a different reviewed %s", field => { expect(() => readGtfsClientReview({ ...review, review: { ...review.review, basis: { ...basis, [field]: id(90) } } }, { feedId: id(4), versionId: id(3) })).toThrow("scope differs"); });
 it("requires complete predecessor counts", () => { expect(() => readGtfsClientReview({ ...review, review: { ...review.review, basis: { ...basis, previousVersionId: id(90) } } }, { feedId: id(4), versionId: id(3) })).toThrow("predecessor differs"); });
 it("refuses concealed shrinkage or an invented current version", () => { expect(() => readGtfsClientReview({ ...review, review: { ...review.review, basis: { ...basis, previousVersionId: id(9), previousRouteCount: 20, previousStopCount: 500 } } }, { feedId: id(4), versionId: id(3) })).toThrow("shrinkage or current"); expect(() => readGtfsClientReview({ ...review, review: { ...review.review, isCurrent: true } }, { feedId: id(4), versionId: id(3) })).toThrow("shrinkage or current"); });
 it("discloses a material reduction and preserves a current version review", () => { const smaller = { ...review.review, basis: { ...basis, previousVersionId: id(9), previousRouteCount: 20, previousStopCount: 500 }, materialShrinkage: true }; expect(readGtfsClientReview({ ...review, review: smaller }, { feedId: id(4), versionId: id(3) })).toEqual(smaller); const current = { ...review.review, basis: { ...basis, previousVersionId: id(3), previousRouteCount: 14, previousStopCount: 287 }, isCurrent: true }; expect(readGtfsClientReview({ ...review, review: current }, { feedId: id(4), versionId: id(3) })).toEqual(current); });
});
