// @vitest-environment node
import { createClient } from "@supabase/supabase-js";
import { mkdtemp, readFile, writeFile, rm } from "node:fs/promises";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { afterEach, describe, expect, it, vi } from "vitest";
import { cancelGtfsRequest, readGtfsRequestCancellation, verifyGtfsRequestCancellation } from "@/lib/gtfs/managed-request-cancellation";
const id = (n: number) => `e6000000-0000-4000-8000-${String(n).padStart(12, "0")}`;
const scope = { workspaceId: id(1), requestId: id(2), actorId: id(3) };
const receipt = { command: id(4), workspaceId: id(1), requestId: id(2), state: "cancelled" as const, versionId: null, versionCancellation: null, cancelledAt: "2026-10-10T12:00:00Z" };
const directories: string[] = [];
afterEach(async () => { for (const path of directories.splice(0)) await rm(path, { recursive: true, force: true }); });
async function fixture() {
 const directory = await mkdtemp(join(tmpdir(), "openplan-request-cancellation-")); directories.push(directory);
 const controller = new AbortController(), command = { commandId: id(4), reason: "Planner cancelled this request" };
 const transport = vi.fn<typeof fetch>(async (_input, init) => { const saved = JSON.parse(await readFile(join(directory, "pending.json"), "utf8")); expect(saved.binding.command).toEqual(command); expect(saved.binding.scope).toEqual(scope); expect(init?.signal).toBeDefined(); return Response.json(receipt); });
 const service = createClient("http://127.0.0.1:54321", "synthetic-key", { auth: { persistSession: false, autoRefreshToken: false }, global: { fetch: transport } });
 const options = { directory, installationId: id(5), target: "http://127.0.0.1:54321", scope, command, service, signal: controller.signal, deadlineMs: 100 };
 return { directory, options, controller, transport, run: () => cancelGtfsRequest(options) };
}
describe("retained request cancellation commands", () => {
 it("retains exact request command before dispatch and rechecks SQL on replay", async () => { const f = await fixture(); expect(await f.run()).toEqual(receipt); expect(await f.run()).toEqual(receipt); expect(f.transport).toHaveBeenCalledTimes(2); expect(String(f.transport.mock.calls[0][0])).toMatch(/\/cancel_gtfs_submission$/); expect(JSON.parse(String(f.transport.mock.calls[0][1]?.body))).toEqual({ p_workspace: id(1), p_request: id(2), p_actor: id(3), p_command: id(4), p_reason: "Planner cancelled this request" }); });
 it("recovers an unknown reply with the same command UUID", async () => { const f = await fixture(), normal = f.transport.getMockImplementation()!; f.transport.mockImplementationOnce(async (input, init) => { await normal(input, init); throw new Error("lost reply"); }); await expect(f.run()).rejects.toThrow("acknowledgement is unavailable"); expect(JSON.parse(await readFile(join(f.directory, "pending.json"), "utf8")).receipt).toBeNull(); expect(await f.run()).toEqual(receipt); expect(f.transport.mock.calls.map(call => JSON.parse(String(call[1]?.body)).p_command)).toEqual([id(4), id(4)]); });
 it.each(["installationId", "target", "workspaceId", "requestId", "actorId", "commandId", "reason"])("refuses changed retained %s before dispatch", async field => { const f = await fixture(); await f.run(); f.transport.mockClear(); if (field === "installationId") f.options.installationId = id(90); else if (field === "target") f.options.target = "http://other.invalid"; else if (["workspaceId", "requestId", "actorId"].includes(field)) f.options.scope = { ...scope, [field]: id(90) }; else f.options.command = { ...f.options.command, [field]: field === "reason" ? "Changed reason" : id(90) }; await expect(f.run()).rejects.toThrow("binding differs"); expect(f.transport).not.toHaveBeenCalled(); });
 it.each(["command", "workspaceId", "requestId"])("refuses a changed %s receipt", async field => { const f = await fixture(); f.transport.mockResolvedValue(Response.json({ ...receipt, [field]: id(90) })); await expect(f.run()).rejects.toThrow("scope differs"); });
 it("refuses a changed acknowledged cancellation time", async () => { const f = await fixture(); await f.run(); f.transport.mockResolvedValue(Response.json({ ...receipt, cancelledAt: "2026-10-10T12:00:01Z" })); await expect(f.run()).rejects.toThrow("cancellation changed"); });
 it("refuses a tampered retained receipt before replay", async () => { const f = await fixture(); await f.run(); const path = join(f.directory, "pending.json"), saved = JSON.parse(await readFile(path, "utf8")); saved.receipt.requestId = id(90); await writeFile(path, JSON.stringify(saved)); f.transport.mockClear(); await expect(f.run()).rejects.toThrow("scope differs"); expect(f.transport).not.toHaveBeenCalled(); });
 it("stops pre-cancelled commands before files or transport", async () => { const f = await fixture(); f.controller.abort(); await expect(f.run()).rejects.toThrow(); expect(f.transport).not.toHaveBeenCalled(); await expect(readFile(join(f.directory, "pending.json"))).rejects.toMatchObject({ code: "ENOENT" }); });
 it("bounds an uncooperative acknowledgement", async () => { const f = await fixture(); f.options.deadlineMs = 20; f.transport.mockImplementation(async () => { await new Promise(resolve => setTimeout(resolve, 200)); return Response.json(receipt); }); const start = Date.now(); await expect(f.run()).rejects.toThrow("acknowledgement is unavailable"); expect(Date.now() - start).toBeLessThan(150); });
 it("refuses relative command directories", async () => { const f = await fixture(); f.options.directory = "relative-request-command"; await expect(f.run()).rejects.toThrow(); expect(f.transport).not.toHaveBeenCalled(); });
 it.each(["http://user:password@example.invalid", "file:///tmp/feed", "http://example.invalid/?secret=1", "http://example.invalid/#fragment"])("refuses invalid target %s", async target => { const f = await fixture(); f.options.target = target; await expect(f.run()).rejects.toThrow("target is invalid"); expect(f.transport).not.toHaveBeenCalled(); });
 it("refuses concurrent command dispatch under its private lock", async () => { const f = await fixture(), normal = f.transport.getMockImplementation()!; f.transport.mockImplementation(async (input, init) => { await new Promise(resolve => setTimeout(resolve, 20)); return normal(input, init); }); const results = await Promise.allSettled([f.run(), f.run()]); expect(results.filter(result => result.status === "fulfilled")).toHaveLength(1); expect(f.transport).toHaveBeenCalledTimes(1); });
});
describe("request cancellation receipt and member status", () => {
 const terminal = { command: id(4), version: id(6), state: "cancelled", closure: { recorded: true, feedStatusChanged: false }, cleanupPending: true, closedAt: "2026-10-10T12:00:00Z" };
 it("keeps early cancellation separate from a known version closure", () => { expect(verifyGtfsRequestCancellation(receipt, scope)).toEqual(receipt); const known = { ...receipt, versionId: id(6), versionCancellation: terminal }; expect(verifyGtfsRequestCancellation(known, scope)).toEqual(known); });
 it.each(["command", "version"])("refuses a changed nested terminal %s", field => { expect(() => verifyGtfsRequestCancellation({ ...receipt, versionId: id(6), versionCancellation: { ...terminal, [field]: id(90) } }, scope)).toThrow("terminal receipt differs"); });
 it("refuses a terminal receipt without its known version", () => { expect(() => verifyGtfsRequestCancellation({ ...receipt, versionCancellation: terminal }, scope)).toThrow("terminal receipt differs"); });
 it("refuses an unrecorded terminal closure and unknown private fields", () => { expect(() => verifyGtfsRequestCancellation({ ...receipt, versionId: id(6), versionCancellation: { ...terminal, closure: { recorded: false, feedStatusChanged: false } } }, scope)).toThrow(); expect(() => verifyGtfsRequestCancellation({ ...receipt, token: id(90) }, scope)).toThrow(); });
 function read(raw: unknown, error = false) { const transport = vi.fn<typeof fetch>(async () => error ? Response.json({ code: "42501", message: "Synthetic private detail" }, { status: 403 }) : Response.json(raw)); const service = createClient("http://127.0.0.1:54321", "synthetic-key", { auth: { persistSession: false, autoRefreshToken: false }, global: { fetch: transport } }); return { transport, run: () => readGtfsRequestCancellation(service, scope, new AbortController().signal) }; }
 it("reads scoped membership without issuing cancellation", async () => { const f = read(receipt); expect(await f.run()).toEqual(receipt); expect(String(f.transport.mock.calls[0][0])).toMatch(/\/read_gtfs_submission_cancellation$/); expect(JSON.parse(String(f.transport.mock.calls[0][1]?.body))).toEqual({ p_workspace: id(1), p_request: id(2), p_actor: id(3) }); });
 it("preserves a null reservation and refuses an unavailable read", async () => { expect(await read(null).run()).toBeNull(); await expect(read(null, true).run()).rejects.toThrow("acknowledgement is unavailable"); });
 it("refuses a different request from the cancellation lookup", async () => { await expect(read({ ...receipt, requestId: id(90) }).run()).rejects.toThrow("scope differs"); });
});
