import { describe, expect, it, vi } from "vitest";
import { retainGtfsClientDecision, readGtfsClientDecisions, dismissGtfsClientDecision, gtfsClientDecisionRequest, type GtfsClientDecision } from "@/lib/gtfs/managed-client-decision";
const id = (n: number) => `e4000000-0000-4000-8000-${String(n).padStart(12, "0")}`;
const scope = { installationId: id(1), workspaceId: id(2), actorId: id(3) };
const cancel = { operation: "cancel_request" as const, requestId: id(4), commandId: id(5), reason: "Planner cancelled" };
const basis = { feedId: id(6), versionId: id(7), routeCount: 14, stopCount: 287, previousVersionId: null, previousRouteCount: null, previousStopCount: null };
const adopt = { operation: "adopt" as const, versionId: id(7), commandId: id(8), basis, acceptMaterialShrinkage: false };
function fixture() { const values = new Map<string, string>(), store = { getItem: vi.fn((key: string) => values.get(key) ?? null), setItem: vi.fn((key: string, value: string) => { values.set(key, value); }) }; return { values, store, key: `openplan.gtfs.decisions:${id(1)}:${id(2)}:${id(3)}` }; }
describe("browser-retained transit decisions", () => {
 it("retains exact cancellation and adoption before deriving transport", () => { const f = fixture(); retainGtfsClientDecision(f.store, scope, cancel); retainGtfsClientDecision(f.store, scope, adopt); expect(readGtfsClientDecisions(f.store, scope)).toEqual([cancel, adopt]); expect(JSON.parse(f.values.get(f.key)!)).toEqual({ schemaVersion: 1, binding: scope, decisions: [cancel, adopt] }); });
 it("replays an exact command and refuses changed reason or reviewed counts under its UUID", () => { const f = fixture(); retainGtfsClientDecision(f.store, scope, cancel); expect(retainGtfsClientDecision(f.store, scope, cancel)).toEqual(cancel); expect(() => retainGtfsClientDecision(f.store, scope, { ...cancel, reason: "Changed reason" })).toThrow("different decision"); retainGtfsClientDecision(f.store, scope, adopt); expect(() => retainGtfsClientDecision(f.store, scope, { ...adopt, basis: { ...basis, stopCount: 200 } })).toThrow("different decision"); expect(readGtfsClientDecisions(f.store, scope)).toEqual([cancel, adopt]); });
 it("keeps a new explicit review command beside its earlier unknown command", () => { const f = fixture(); retainGtfsClientDecision(f.store, scope, adopt); const next = { ...adopt, commandId: id(9), basis: { ...basis, previousVersionId: id(10), previousRouteCount: 20, previousStopCount: 300 }, acceptMaterialShrinkage: true }; retainGtfsClientDecision(f.store, scope, next); expect(readGtfsClientDecisions(f.store, scope)).toEqual([adopt, next]); });
 it.each(["installationId", "workspaceId", "actorId"] as const)("isolates another %s and refuses a tampered binding", field => { const f = fixture(); retainGtfsClientDecision(f.store, scope, cancel); expect(readGtfsClientDecisions(f.store, { ...scope, [field]: id(90) })).toEqual([]); const raw = JSON.parse(f.values.get(f.key)!); raw.binding[field] = id(90); f.values.set(f.key, JSON.stringify(raw)); expect(() => readGtfsClientDecisions(f.store, scope)).toThrow("scope differs"); });
 it("refuses unavailable and silent browser storage", () => { const f = fixture(); f.store.setItem.mockImplementation(() => { throw new Error("storage unavailable"); }); expect(() => retainGtfsClientDecision(f.store, scope, cancel)).toThrow("storage unavailable"); f.store.setItem.mockImplementation(() => {}); expect(() => retainGtfsClientDecision(f.store, scope, cancel)).toThrow("could not be retained"); });
 it("bounds history without evicting earlier decisions", () => { const f = fixture(); f.values.set(f.key, " ".repeat(65537)); expect(() => readGtfsClientDecisions(f.store, scope)).toThrow("browser bound"); f.values.set(f.key, JSON.stringify({ schemaVersion: 1, binding: scope, decisions: Array.from({ length: 100 }, (_, n) => ({ ...cancel, commandId: id(n + 100) })) })); expect(() => retainGtfsClientDecision(f.store, scope, cancel)).toThrow(); expect(JSON.parse(f.values.get(f.key)!).decisions).toHaveLength(100); });
 it("refuses oversized serialized decisions before replacing browser history", () => { const f = fixture(), decisions: GtfsClientDecision[] = []; const record = { schemaVersion: 1, binding: scope, decisions }; for (let n = 100; ; n++) { const next = { ...cancel, commandId: id(n), reason: "x".repeat(2000) }; decisions.push(next); if (JSON.stringify(record).length > 65536) { decisions.pop(); break; } } const raw = JSON.stringify(record); f.values.set(f.key, raw); expect(() => retainGtfsClientDecision(f.store, scope, { ...cancel, reason: "x".repeat(2000) })).toThrow("browser bound"); expect(f.values.get(f.key)).toBe(raw); expect(f.store.setItem).not.toHaveBeenCalled(); });
 it("refuses duplicate command IDs in saved history", () => { const f = fixture(); f.values.set(f.key, JSON.stringify({ schemaVersion: 1, binding: scope, decisions: [cancel, cancel] })); expect(() => readGtfsClientDecisions(f.store, scope)).toThrow("scope differs"); });
 it("refuses a different version or partial predecessor basis", () => { expect(() => gtfsClientDecisionRequest(scope, { ...adopt, basis: { ...basis, versionId: id(90) } })).toThrow("basis differs"); expect(() => gtfsClientDecisionRequest(scope, { ...adopt, basis: { ...basis, previousVersionId: id(90) } })).toThrow("basis differs"); });
 it("derives exact routes without caller actor, arbitrary paths or approval overrides", () => { const cancelled = gtfsClientDecisionRequest(scope, cancel), adopted = gtfsClientDecisionRequest(scope, adopt); expect(cancelled.path).toBe(`/api/gtfs/submissions/${id(4)}/cancel`); expect(JSON.parse(cancelled.init.body)).toEqual({ workspaceId: id(2), commandId: id(5), reason: "Planner cancelled" }); expect(adopted.path).toBe(`/api/gtfs/versions/${id(7)}/adopt`); expect(JSON.parse(adopted.init.body)).toEqual({ workspaceId: id(2), command: { operation: "adopt", commandId: id(8), basis, acceptMaterialShrinkage: false } }); expect(() => gtfsClientDecisionRequest(scope, { ...cancel, path: "/api/workspaces" } as unknown as GtfsClientDecision)).toThrow(); });
 it("dismisses browser history without retracting the server command", () => { const f = fixture(); retainGtfsClientDecision(f.store, scope, cancel); retainGtfsClientDecision(f.store, scope, adopt); expect(dismissGtfsClientDecision(f.store, scope, id(5))).toEqual([adopt]); });
 it.each(["installationId", "workspaceId", "actorId"] as const)("refuses invalid current %s before reading storage", field => { const f = fixture(); expect(() => readGtfsClientDecisions(f.store, { ...scope, [field]: "invalid" })).toThrow(); expect(f.store.getItem).not.toHaveBeenCalled(); });
});
