import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

/*
  LABELS ARE SENTENCE CASE.

  Nathaniel, October 10, 2026: the app had "way too many subtitles, subtext,
  unnecessary stuff." About 620 small labels were set in tracked capitals, so
  every card, tile and chip shouted at the same volume and none stood out. The
  overhaul (docs/reviews/2026-10-10-ui-overhaul/PLAN.md, section 2) removed the
  capitals and the letter-spacing; hierarchy now comes from weight and ink.

  Scope is deliberate. The three app stylesheets are checked whole. Components
  are checked by an explicit list, the files the overhaul changed, so another
  lane adding a class elsewhere does not fail this test. Blind categories:
  files not on the list, capitals typed into the string itself, and exported
  documents (reports, invoices, applications), which keep their own styles.
*/
const STYLESHEETS = ["src/app/globals.css", "src/app/cartographic.css", "src/app/workspace-gis.css"];

const SENTENCE_CASE_FILES = [
  "src/app/(app)/aerial/missions/[missionId]/edit/page.tsx",
  "src/app/(app)/county-runs/[countyRunId]/_components/county-run-behavioral-kpis.tsx",
  "src/app/(app)/county-runs/page.tsx",
  "src/app/(app)/dashboard/page.tsx",
  "src/app/(app)/data-hub/page.tsx",
  "src/app/(app)/error.tsx",
  "src/app/(app)/explore/_components/explore-current-result-card.tsx",
  "src/app/(app)/explore/_components/explore-disclosure-card.tsx",
  "src/app/(app)/explore/_components/explore-geospatial-briefing.tsx",
  "src/app/(app)/explore/_components/explore-hover-inspector.tsx",
  "src/app/(app)/explore/_components/explore-run-comparison-card.tsx",
  "src/app/(app)/explore/_components/explore-workbench.tsx",
  "src/app/(app)/help/page.tsx",
  "src/app/(app)/invoicing/_components/invoicing-cash-strip.tsx",
  "src/app/(app)/invoicing/_components/receivables-lane.tsx",
  "src/app/(app)/invoicing/_components/reimbursement-lane.tsx",
  "src/app/(app)/invoicing/page.tsx",
  "src/app/(app)/land-use-plans/page.tsx",
  "src/app/(app)/models/[modelId]/page.tsx",
  "src/app/(app)/models/_components/network-packages-panel.tsx",
  "src/app/(app)/models/page.tsx",
  "src/app/(app)/plans/[planId]/page.tsx",
  "src/app/(app)/programs/[programId]/_components/program-overview-cards.tsx",
  "src/app/(app)/programs/[programId]/measure/page.tsx",
  "src/app/(app)/programs/[programId]/page.tsx",
  "src/app/(app)/programs/page.tsx",
  "src/app/(app)/projects/[projectId]/_components/project-delivery-board.tsx",
  "src/app/(app)/projects/[projectId]/_components/project-funding-panel.tsx",
  "src/app/(app)/projects/[projectId]/_components/project-posture-header.tsx",
  "src/app/(app)/projects/[projectId]/_components/project-posture-unified.tsx",
  "src/app/(app)/projects/[projectId]/_components/project-risk-decision-log.tsx",
  "src/app/(app)/projects/[projectId]/_components/project-spine-board.tsx",
  "src/app/(app)/projects/[projectId]/_components/project-spine-crosslink-board.tsx",
  "src/app/(app)/projects/[projectId]/_components/project-spine-readiness-rollup.tsx",
  "src/app/(app)/projects/page.tsx",
  "src/app/(app)/reports/[reportId]/_components/report-composition-audit.tsx",
  "src/app/(app)/reports/[reportId]/_components/report-navigation-preview.tsx",
  "src/app/(app)/reports/[reportId]/_components/report-packet-review.tsx",
  "src/app/(app)/reports/[reportId]/_components/report-provenance-audit.tsx",
  "src/app/(app)/reports/page.tsx",
  "src/app/(app)/rtp/[rtpCycleId]/_components/rtp-financial-element-section.tsx",
  "src/app/(app)/rtp/[rtpCycleId]/document/page.tsx",
  "src/app/(app)/rtp/[rtpCycleId]/extraction/page.tsx",
  "src/app/(app)/rtp/[rtpCycleId]/page.tsx",
  "src/app/(app)/rtp/_components/rtp-cycle-registry-table.tsx",
  "src/app/(app)/rtp/_components/rtp-registry-advisory-panel.tsx",
  "src/app/(app)/safety/page.tsx",
  "src/app/(app)/scenarios/[scenarioSetId]/_components/scenario-linked-reports-section.tsx",
  "src/app/(app)/scenarios/[scenarioSetId]/page.tsx",
  "src/app/(app)/scenarios/page.tsx",
  "src/app/(auth)/forgot-password/page.tsx",
  "src/app/(auth)/layout.tsx",
  "src/app/(auth)/reset-password/page.tsx",
  "src/app/(auth)/sign-in/page.tsx",
  "src/app/(auth)/sign-up/page.tsx",
  "src/app/(public)/examples/page.tsx",
  "src/app/(public)/layout.tsx",
  "src/app/(published)/measure/[shareToken]/page.tsx",
  "src/app/(published)/plan/[shareToken]/document/page.tsx",
  "src/app/(published)/plan/[shareToken]/page.tsx",
  "src/app/(published)/published-plans/[planId]/page.tsx",
  "src/app/(published)/review/land-use-plans/[shareToken]/page.tsx",
  "src/app/error.tsx",
  "src/app/layout.tsx",
  "src/components/aerial/aerial-evidence-package-creator.tsx",
  "src/components/aerial/aerial-mission-creator.tsx",
  "src/components/aerial/aerial-mission-launcher.tsx",
  "src/components/aerial/aerial-processing-jobs-panel.tsx",
  "src/components/aerial/aerial-processing-request.tsx",
  "src/components/assistant/app-copilot.tsx",
  "src/components/ceqa/ceqa-vmt-screen-body.tsx",
  "src/components/county-runs/county-run-detail-client.tsx",
  "src/components/county-runs/county-run-modeling-evidence.tsx",
  "src/components/county-runs/county-run-validation-prep.tsx",
  "src/components/county-runs/county-runs-page-client.tsx",
  "src/components/dashboard/dashboard-insights.tsx",
  "src/components/data-hub/title-vi-service-equity-panel.tsx",
  "src/components/geographies/census-tract-coverage-control.tsx",
  "src/components/grants/bca-screening-body.tsx",
  "src/components/grants/funding-award-closeout-control.tsx",
  "src/components/grants/funding-opportunity-application-workspace.tsx",
  "src/components/grants/funding-opportunity-narrative-draft-panel.tsx",
  "src/components/grants/grants-funding-need-editor-section.tsx",
  "src/components/grants/grants-opportunity-creator-section.tsx",
  "src/components/grants/grants-opportunity-registry-card.tsx",
  "src/components/grants/narrative-grounding-line.tsx",
  "src/components/invoicing/client-invoice-composer.tsx",
  "src/components/invoicing/invoice-funding-award-linker.tsx",
  "src/components/invoicing/invoice-record-composer.tsx",
  "src/components/invoicing/receivable-aging-strip.tsx",
  "src/components/invoicing/reimbursement-worksheet-download.tsx",
  "src/components/invoicing/staff-and-rates-panel.tsx",
  "src/components/invoicing/time-entry-composer.tsx",
  "src/components/jurisdiction-readiness/jurisdiction-readiness-panel.tsx",
  "src/components/land-use-plans/land-use-plan-workbench.tsx",
  "src/components/measures/allocation-rule-builder.tsx",
  "src/components/measures/basis-value-editor.tsx",
  "src/components/measures/measure-form-shell.tsx",
  "src/components/measures/measure-fund-panel.tsx",
  "src/components/measures/moe-editor.tsx",
  "src/components/models/analysis-sequence-strip.tsx",
  "src/components/models/demand-agreement-map.tsx",
  "src/components/models/model-detail-controls.tsx",
  "src/components/models/model-linked-records.tsx",
  "src/components/models/model-run-ceqa-vmt-screen.tsx",
  "src/components/models/model-run-emissions-panel.tsx",
  "src/components/models/model-run-engagement-panel.tsx",
  "src/components/models/model-run-equity-panel.tsx",
  "src/components/models/model-run-evidence-panel.tsx",
  "src/components/models/model-run-manager.tsx",
  "src/components/models/model-run-screening-grade-note.tsx",
  "src/components/models/model-run-trip-gen-screen.tsx",
  "src/components/models/model-run-zone-resolution-panel.tsx",
  "src/components/models/project-comparison-starter.tsx",
  "src/components/models/traffic-volume-map.tsx",
  "src/components/nav/nav-link-pill.tsx",
  "src/components/nav/nav-registry.ts",
  "src/components/onboarding/first-run-checklist.tsx",
  "src/components/onboarding/onboarding-wizard.tsx",
  "src/components/operations/pilot-workflow-handoff.tsx",
  "src/components/operations/workspace-command-board.tsx",
  "src/components/programs/funding-opportunity-decision-controls.tsx",
  "src/components/projects/planning-context-strip.tsx",
  "src/components/projects/project-estimated-cost-editor.tsx",
  "src/components/projects/project-funding-award-creator.tsx",
  "src/components/projects/project-funding-profile-editor.tsx",
  "src/components/projects/project-map-presence.tsx",
  "src/components/projects/project-portfolio-importer.tsx",
  "src/components/projects/project-portfolio-table.tsx",
  "src/components/projects/project-spend-entry-form.tsx",
  "src/components/projects/project-stage-gate-board.tsx",
  "src/components/projects/rtp-priority-score-editor.tsx",
  "src/components/projects/stage-gate-decision-recorder.tsx",
  "src/components/projects/work-plan-template-applier.tsx",
  "src/components/reports/land-use-plan-report-detail.tsx",
  "src/components/reports/report-creator.tsx",
  "src/components/reports/report-detail-controls.tsx",
  "src/components/reports/report-narrative-draft-panel.tsx",
  "src/components/reports/report-packet-command-queue.tsx",
  "src/components/reports/report-read-failure-notice.tsx",
  "src/components/reports/rtp-report-detail.tsx",
  "src/components/rtp/extraction-candidate-card.tsx",
  "src/components/rtp/rtp-chapter-draft-assist.tsx",
  "src/components/rtp/rtp-cycle-details-editor.tsx",
  "src/components/rtp/rtp-cycle-phase-controls.tsx",
  "src/components/rtp/rtp-financial-ledger-editor.tsx",
  "src/components/rtp/rtp-horizon-band-editor.tsx",
  "src/components/rtp/rtp-performance-measure-editor.tsx",
  "src/components/rtp/rtp-registry-packet-bulk-actions.tsx",
  "src/components/rtp/rtp-registry-packet-bulk-artifact-actions.tsx",
  "src/components/rtp/transcribed-chapter-draft-card.tsx",
  "src/components/scenarios/scenario-entry-registry.tsx",
  "src/components/theme-controls.tsx",
  "src/components/theme-provider.tsx",
  "src/components/theme-toggle.tsx",
  "src/components/top-nav.tsx",
  "src/components/ui/badge.tsx",
  "src/components/ui/chip-multi-select.tsx",
  "src/components/ui/confirm-dialog.tsx",
  "src/components/ui/data-table.tsx",
  "src/components/ui/guided-flow.tsx",
  "src/components/ui/inspector.tsx",
  "src/components/ui/status-badge.tsx",
  "src/components/workspaces/invitation-decision.tsx",
  "src/components/workspaces/workspace-stage-gate-panel.tsx",
];

const UPPERCASE_CLASS = /(?<![\w-])(?:[a-z0-9]+:)*uppercase(?![\w-])/g;
const WIDE_TRACKING_CLASS = /(?<![\w-])(?:[a-z0-9]+:)*tracking-(?:\[(?!-)[^\]\s]+\]|wide|wider|widest)(?![\w-])/g;

describe("labels are sentence case", () => {
  it.each(STYLESHEETS)("%s sets no text in capitals", (file) => {
    expect(readFileSync(file, "utf8").match(/text-transform:\s*uppercase/g) ?? []).toEqual([]);
  });

  it.each(SENTENCE_CASE_FILES)("%s uses no uppercase or wide-tracking class", (file) => {
    const source = readFileSync(file, "utf8");
    expect(source.match(UPPERCASE_CLASS) ?? []).toEqual([]);
    expect(source.match(WIDE_TRACKING_CLASS) ?? []).toEqual([]);
  });
});
